### ISSUE TITLE
torchscript model second time forward is very slow

### ISSUE THREAD

**Issue by Sanster** [Sanster/lama-cleaner#1]

**Comment by Sanster** [comment]
![image](https://user-images.githubusercontent.com/3998421/141799179-8171592d-71ce-4a5e-ba3b-639f7d001f5f.png)

**Comment by omar16100** [comment]
What time are you getting on which hardware?

**Comment by kanttouchthis** [comment]
Here are my times in seconds using my code, on a GTX 1080. Only the ```model(...)``` part is timed. This seems to be an issue with LaMa or pytorch
![Screenshot 2021-12-29 214218](https://user-images.githubusercontent.com/90077736/147701934-942fdab3-dc1f-451a-a0f2-7772b13b6678.png)

**Comment by Sanster** [comment]
My device is RTX TITAN. Torchscript convert script https://github.com/saic-mdal/lama/pull/63

**Comment by Sanster** [comment]
I tested it again and the real problem is that the **same picture** is very slow in the second forward

**Comment by Sanster** [comment]
This is a feature of TorchScript(as of 1.7)!!! https://github.com/pytorch/pytorch/issues/50796#issuecomment-769272059

**Comment by Sanster** [comment]
Related issue https://discuss.pytorch.org/t/second-forward-call-of-torchscripted-module-breaks-on-cuda/124291

**Comment by Sanster** [comment]
Related issue https://discuss.pytorch.org/t/second-forward-call-of-torchscripted-module-breaks-on-cuda/124291
