### ISSUE TITLE
One-click installer 

### ISSUE THREAD

**Issue by divamgupta** [Sanster/lama-cleaner#100]
Nice work on Lama Cleaner. Its a really useful tool! 

I had a question, how did you create a portable conda environment for  the one-click macos installer. 

Thanks

**Comment by Sanster** [comment]
You can check [pack.sh](https://github.com/Sanster/lama-cleaner/blob/main/scripts/pack.sh) script, the key is the use of the `conda pack` command, it makes distribution  really easy. But the disadvantage is also obvious, the installation package itself is very large 🥲
