### ISSUE TITLE
Prebuilt docker image link broken

### ISSUE THREAD

**Issue by bbecausereasonss** [Sanster/lama-cleaner#101]
As title says

**Comment by Sanster** [comment]
fixed

**Comment by bbecausereasonss** [comment]
Still says 404.

https://github.com/Sanster/lama-cleaner/blob/main

**Comment by Sanster** [comment]
Didn't realize you were talking about this link 😅 , fixed now

**Comment by bbecausereasonss** [comment]
I must be really dumb. Do I need to run some commands to download the image? Because now the link is only taking me to the same page/section that mentions the link but not to any download for an image. lol

**Comment by Sanster** [comment]
No, `docker run ....` command will automatically download the image from the docker hub

**Comment by bbecausereasonss** [comment]
Thanks!
