### ISSUE TITLE
How to change the directory of ". cache/huggingface/diffusers/models" to my favorite file location

### ISSUE THREAD

**Issue by gaoxuxu110** [Sanster/lama-cleaner#102]

**Comment by Sanster** [comment]
looks like  it‘s controlled by **HF_HOME** environment variable https://github.com/huggingface/diffusers/blob/d37f08da723cba38965b2df8b21a8136af9f358f/src/diffusers/utils/__init__.py#L58

**Comment by Tobe2d** [comment]
Is there away to make it download the models by default in the same folder of lama, so it is self contained?
For example download all models in:
 \lama-cleaner\models\diffusers
                                     \LaMa
                                     \LDM
                                      \ZITS

**Comment by Sanster** [comment]
By default lama-cleaner will download model(except sd1.5) to TORCH_HOME=~/.cache/torch/hub/checkpoints/, you can set **TORCH_HOME** to other folder

**Comment by neoOpus** [comment]
use Softlinks

**Comment by Tobe2d** [comment]
> use Softlinks

How do you do that? Any example will be appreciated

**Comment by Sanster** [comment]
sorry for the late replay, please check https://github.com/Sanster/lama-cleaner/blob/main/scripts/README.md#qa

**Comment by neoOpus** [comment]
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

**Comment by HZQ950419** [comment]
use `export XDG_CACHE_HOME="path/to/folder"` or put it in your `~/.bashrc file

**Comment by Najne** [comment]
> use SymLinks

Bro you just saved my life
