### ISSUE TITLE
Did not find CUDA device on your computer

### ISSUE THREAD

**Issue by gaoxuxu110** [Sanster/lama-cleaner#104]
I have installed cuda, but the WARNING--
            “Did not find CUDA device on your computer, fallback to cpu                              tasks.py:86
            Start as desktop app? [y/n] (y):”
so，How to use GPU to run this program

**Comment by Yishaqel** [comment]
I get the same problem.

**Comment by Sanster** [comment]
By default, installer will install pytorch-cu113, it’s looks like it didn’t match your GPU and NVIDIA driver version.

If you can provide the following information, I can suggest the correct PyTorch
 version (we need a way to auto find this…).

- What GPU are you using?
- Your current graphics card driver: https://www.nvidia.com/en-gb/drivers/drivers-faq/

**Comment by Yishaqel** [comment]
I am using the 2070 Super graphics card and 522.25 drivers

**Comment by gaoxuxu110** [comment]
> By default, installer will install pytorch-cu113, it’s looks like it didn’t match your GPU and NVIDIA driver version.
> 
> If you can provide the following information, I can suggest the correct PyTorch version (we need a way to auto find this…).
> 
> * What GPU are you using?
> * Your current graphics card driver: https://www.nvidia.com/en-gb/drivers/drivers-faq/

I am using the 3070ti graphics card and 526.47 drivers released 10/27/2022

**Comment by jinmingyi1998** [comment]
> > By default, installer will install pytorch-cu113, it’s looks like it didn’t match your GPU and NVIDIA driver version.
> > 
> > If you can provide the following information, I can suggest the correct PyTorch version (we need a way to auto find this…).
> > 
> > * What GPU are you using?
> > * Your current graphics card driver: https://www.nvidia.com/en-gb/drivers/drivers-faq/
> 
> I am using the 3070ti graphics card and 526.47 drivers released 10/27/2022

make sure you have cuda runtime with pytorch. 

how did you install , pure pip/conda/docker.

 if you just pip install, you need cuda installed in system.(check with `nvidia-smi`) 

if you install with conda, you can install cudatoolkit in conda, also you can still use system cuda.

**Comment by gaoxuxu110** [comment]
> > > By default, installer will install pytorch-cu113, it’s looks like it didn’t match your GPU and NVIDIA driver version.
> > > If you can provide the following information, I can suggest the correct PyTorch version (we need a way to auto find this…).
> > > 
> > > * What GPU are you using?
> > > * Your current graphics card driver: https://www.nvidia.com/en-gb/drivers/drivers-faq/
> > 
> > 
> > I am using the 3070ti graphics card and 526.47 drivers released 10/27/2022
> 
> make sure you have cuda runtime with pytorch.
> 
> how did you install , pure pip/conda/docker.
> 
> if you just pip install, you need cuda installed in system.(check with `nvidia-smi`)
> 
> if you install with conda, you can install cudatoolkit in conda, also you can still use system cuda.

I installed by [One Click Installer] and all files were automatically installed by the program.Here is Environment information：
git version 2.34.1.windows.1
conda 22.9.0
/h/Deepfacelab/lama-cleaner/installer/python
Python 3.10.6
/h/Deepfacelab/lama-cleaner/installer/Scripts/pip
pip 22.2.2 from H:\Deepfacelab\lama-cleaner\installer\lib\site-packages\pip (python 3.10)
diffusers              0.6.0
lama-cleaner           0.24.4
opencv-python          4.6.0.66
torch                  1.13.0

**Comment by Sanster** [comment]
There is something wrong with the `win_config.bat` script, it didn't install a CUDA version of pytorch 😅 , please change it to the follow content and re-execute it

```
@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call conda-unpack

@call conda install -y cudatoolkit=11.3 -c pytorch
@call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
@call pip3 install -U lama-cleaner


@call invoke config
```

**Comment by jinmingyi1998** [comment]
> > > > By default, installer will install pytorch-cu113, it’s looks like it didn’t match your GPU and NVIDIA driver version.
> > > > If you can provide the following information, I can suggest the correct PyTorch version (we need a way to auto find this…).
> > > > 
> > > > * What GPU are you using?
> > > > * Your current graphics card driver: https://www.nvidia.com/en-gb/drivers/drivers-faq/
> > > 
> > > 
> > > I am using the 3070ti graphics card and 526.47 drivers released 10/27/2022
> > 
> > make sure you have cuda runtime with pytorch.
> > 
> > how did you install , pure pip/conda/docker.
> > 
> > if you just pip install, you need cuda installed in system.(check with `nvidia-smi`)
> > 
> > if you install with conda, you can install cudatoolkit in conda, also you can still use system cuda.
> 
> I installed by [One Click Installer] and all files were automatically installed by the program.
> 
> Here is Environment information：
> ```
> git version 2.34.1.windows.1
> conda 22.9.0
> /h/Deepfacelab/lama-cleaner/installer/python
> Python 3.10.6
> /h/Deepfacelab/lama-cleaner/installer/Scripts/pip
> pip 22.2.2 from H:\Deepfacelab\lama-cleaner\installer\lib\site-packages\pip (python 3.10)
> diffusers              0.6.0
> lama-cleaner           0.24.4
> opencv-python          4.6.0.66
> torch                  1.13.0
> ```

torch version is 1.13, it seems a cpu version.

one click installer is a stand-alone runtime environment with conda. it will install cudatoolkit and pytorch gpu version. can you go into that conda env to check `conda list`

**Comment by gaoxuxu110** [comment]
> torch version is 1.13, it seems a cpu version.
> 
> one click installer is a stand-alone runtime environment with conda. it will install cudatoolkit and pytorch gpu version. can you go into that conda env to check `conda list`

`@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call conda-unpack

@call conda install -y cudatoolkit=11.3 -c pytorch
@call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
@call pip3 install -U lama-cleaner


@call invoke config`
👆👆👆👆👆👆
Solve my problem perfectly

**Comment by jinmingyi1998** [comment]
> @jinmingyi1998 
> 
> There is something wrong with the `win_config.bat` script, it didn't install a CUDA version of pytorch 😅 , please change it to the follow content and re-execute it
> ```
> @echo off
> 
> set PATH=C:\Windows\System32;%PATH%
> 
> @call installer\Scripts\activate.bat
> 
> @call conda-unpack
> 
> @call conda install -y cudatoolkit=11.3 -c pytorch
> @call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
> @call pip3 install -U lama-cleaner
> 
> 
> @call invoke config
> ```
> 👆👆👆👆👆👆
> Solve my problem perfectly
> 

already in pr !105

**Comment by ffdown** [comment]
> There is something wrong with the script, it didn't install a CUDA version of pytorch 😅 , please change it to the follow content and re-execute it`win_config.bat`
> 
> ```
> @echo off
> 
> set PATH=C:\Windows\System32;%PATH%
> 
> @call installer\Scripts\activate.bat
> 
> @call conda-unpack
> 
> @call conda install -y cudatoolkit=11.3 -c pytorch
> @call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
> @call pip3 install -U lama-cleaner
> 
> 
> @call invoke config
> ```

does not help this change. Installs CPU driver although I have 4090 with the latest driver.

**Comment by ffdown** [comment]
> > There is something wrong with the script, it didn't install a CUDA version of pytorch 😅 , please change it to the follow content and re-execute it`win_config.bat`
> > ```
> > @echo off
> > 
> > set PATH=C:\Windows\System32;%PATH%
> > 
> > @call installer\Scripts\activate.bat
> > 
> > @call conda-unpack
> > 
> > @call conda install -y cudatoolkit=11.3 -c pytorch
> > @call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
> > @call pip3 install -U lama-cleaner
> > 
> > 
> > @call invoke config
> > ```
> 
> nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0
> 
> does not help this change. Installs CPU driver although I have 4090 with the latest driver.

this answer fix it =)) 

`@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call conda-unpack

@call conda install -y -c conda-forge cudatoolkit=11.7
@call pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
@call pip3 install xformers==0.0.16
@call pip3 install -U lama-cleaner
@call lama-cleaner --install-plugins-package

@call lama-cleaner --config-installer --installer-config %0\..\installer_config.json

PAUSE`

**Comment by lhj5426** [comment]
I also encountered the same issue, and I successfully resolved it following the solution provided above. Thank you very much.！！！！！！
