### ISSUE TITLE
any chancefor self contained windows build? its a pita to get it working

### ISSUE THREAD

**Issue by 2blackbar** [Sanster/lama-cleaner#11]
Anyone managed to get it work on win10? what are exact steps ?

**Comment by Eidenz** [comment]
Use Anaconda. It will allow you to setup the project without any trouble.

Once you installed it, create a python 3.6 environment, and everything should install without any error.
I would also highly recommend using Git Bash instead of the default  windows CMD, as it understands most linux commands.

**Comment by 2blackbar** [comment]
what versions ? the thing is.. i have so much various ai setups going, one breaks the other, so i dont reeeeealy want to crap up another one on top, how much disk space lama and 3.6 env will take up?

**Comment by Eidenz** [comment]
Anaconda is specifically made to prevent projects from breaking each others. It creates **separated** virtual environments.

I don't really remember how much space it takes, but it's rly not much. Probably less than 3GB for the whole env.

**Comment by 2blackbar** [comment]
allright i have env 3.6 in conda, now the frontent, how to set it up?  i got yarn like this:
conda install -c conda-forge yarn
what now ?

**Comment by Eidenz** [comment]
All you have to do with conda is this:
`conda create -n someName python=3.6`
`conda activate someName`
`pip install -r requirements.txt`
`python main.py --device=cuda --port=8080` for CUDA GPU or `python main.py --device=cpu --port=8080` for CPU

That's all. Your lama-cleaner is running on localhost:8080

**Comment by 2blackbar** [comment]
success !!! thanks a lot Eidenz! that was very helpful, il save these steps in txt file for future use, it works very nice !

**Comment by 2blackbar** [comment]
Ok on another cpu, fresh win10 install, only anaconda installed, after setting up env im getting this when i run it    
`AssertionError: Torch not compiled with CUDA enabled`
What am i missing ? i just piped reqs so it should work with cuda ?
