### ISSUE TITLE
Do you support custom MASK?

### ISSUE THREAD

**Issue by Shi-Guang-0901** [Sanster/lama-cleaner#112]
Hi,

**Comment by Sanster** [comment]
You mean upload a mask image?

**Comment by Shi-Guang-0901** [comment]
yes, smearing with a brush is not accurate enough.

**Comment by strandborg** [comment]
Agreed, manual mask image upload would be useful

**Comment by Edwardpillwin** [comment]
Yes, it is useful

**Comment by Sanster** [comment]
https://github.com/Sanster/lama-cleaner/releases/tag/0.26.0

**Comment by SunSoul** [comment]
> https://github.com/Sanster/lama-cleaner/releases/tag/0.26.0

Hi, Is there anything I need to pay attention about mask images? I use the mask image from : 
[segment-anything](https://github.com/facebookresearch/segment-anything)

it works wrong, then i find the mask image from [segment-anything] is a grayscale image, so i convert it to RGB, but it still works wrong.

**Comment by Edwardpillwin** [comment]
> > https://github.com/Sanster/lama-cleaner/releases/tag/0.26.0
> 
> Test use assets/dog.jpg, by "background". Hi, Is there anything I need to pay attention about mask images? I use the mask image from : [segment-anything](https://github.com/facebookresearch/segment-anything)
> 
> it works wrong, remove dog success , but it filled with other object there. i find the mask image from [segment-anything] is a grayscale image, so i convert it to RGB, but it still works wrong.

maybe you can show some results to compare

**Comment by Sanster** [comment]
@SunSoul Can you share a picture of your results? If you directly use the results of segment-anything, the LaMa model's performance is indeed not good. To achieve better results, you need to perform a dilation operation on the mask result of segment-anything.  https://github.com/Sanster/lama-cleaner/blob/37e9137ac70ef9021224a7c3037b21d35b835a01/lama_cleaner/plugins/interactive_seg.py#L68

By the way, segment-anything is already supported in lama-cleaner [1.1.1](https://github.com/Sanster/lama-cleaner/releases), here is a [demo video](https://twitter.com/sfjccz/status/1643992289294057472?s=20). You can start server with following command line args:

```bash
--enable-interactive-seg --interactive-seg-model=vit_l  --interactive-seg-device=cpu
```

**Comment by SunSoul** [comment]
> > > https://github.com/Sanster/lama-cleaner/releases/tag/0.26.0
> > 
> > 
> > 测试使用资产/狗.jpg，按“背景”。嗨，关于掩码图像，我有什么需要注意的吗？我使用来自：[分段的](https://github.com/facebookresearch/segment-anything)蒙版图像
> > 它工作错误，删除狗成功，但它充满了其他对象。我发现 [segment-anything] 中的蒙版图像是灰度图像，所以我将其转换为 RGB，但它仍然工作错误。
> 
> 也许您可以显示一些结果进行比较

Just now I was re-editing the issue, thanks!

**Comment by SunSoul** [comment]
> @SunSoul Can you share a picture of your results? If you directly use the results of segment-anything, the LaMa model's performance is indeed not good(The mask should be slightly larger than the target area to be inpainted.). To achieve better results, you need to perform a dilation operation on the mask result of segment-anything.
> 
> https://github.com/Sanster/lama-cleaner/blob/37e9137ac70ef9021224a7c3037b21d35b835a01/lama_cleaner/plugins/interactive_seg.py#L68
> 
> By the way, segment-anything is already supported in lama-cleaner [1.1.1](https://github.com/Sanster/lama-cleaner/releases), here is a [demo video](https://twitter.com/sfjccz/status/1643992289294057472?s=20). You can start server with following command line args:
> 
> ```shell
> --enable-interactive-seg --interactive-seg-model=vit_l  --interactive-seg-device=cpu
> ```

Just now I was re-editing the issue!
I'll test it, thanks!

**Comment by SunSoul** [comment]
> @SunSoul Can you share a picture of your results? If you directly use the results of segment-anything, the LaMa model's performance is indeed not good(The mask should be slightly larger than the target area to be inpainted.). To achieve better results, you need to perform a dilation operation on the mask result of segment-anything.
> 
> https://github.com/Sanster/lama-cleaner/blob/37e9137ac70ef9021224a7c3037b21d35b835a01/lama_cleaner/plugins/interactive_seg.py#L68
> 
> By the way, segment-anything is already supported in lama-cleaner [1.1.1](https://github.com/Sanster/lama-cleaner/releases), here is a [demo video](https://twitter.com/sfjccz/status/1643992289294057472?s=20). You can start server with following command line args:
> 
> ```shell
> --enable-interactive-seg --interactive-seg-model=vit_l  --interactive-seg-device=cpu
> ```

Just now I was re-editing the issue!
I'll test it, thanks!

> > > https://github.com/Sanster/lama-cleaner/releases/tag/0.26.0
> > 
> > 
> > Test use assets/dog.jpg, by "background". Hi, Is there anything I need to pay attention about mask images? I use the mask image from : [segment-anything](https://github.com/facebookresearch/segment-anything)
> > it works wrong, remove dog success , but it filled with other object there. i find the mask image from [segment-anything] is a grayscale image, so i convert it to RGB, but it still works wrong.
> 
> maybe you can show some results to compare

Just now I was re-editing the issue, thanks!

**Comment by SunSoul** [comment]
> > > https://github.com/Sanster/lama-cleaner/releases/tag/0.26.0
> > 
> > 
> > Test use assets/dog.jpg, by "background". Hi, Is there anything I need to pay attention about mask images? I use the mask image from : [segment-anything](https://github.com/facebookresearch/segment-anything)
> > it works wrong, remove dog success , but it filled with other object there. i find the mask image from [segment-anything] is a grayscale image, so i convert it to RGB, but it still works wrong.
> 
> maybe you can show some results to compare

Just now I was re-editing the issue, thanks!

**Comment by SunSoul** [comment]
@Sanster  works very well, thank you !
