### ISSUE TITLE
I try to use sd1.5 model, I got an ERROR when win_start.bat start

### ISSUE THREAD

**Issue by SpiderDKing** [Sanster/lama-cleaner#115]
OSError: There was a specific connection error when trying to load runwayml/stable-diffusiion-inpainting:
<class 'requests.exceptions.HTTPError'>(Request ID: 1106qiKbyRkEukjKYr4S0)
Might my net caused this error?

**Comment by Sanster** [comment]
Have you completed the following two steps?

1.  To use this sd1.5 model you need to [accepting the terms](https://huggingface.co/runwayml/stable-diffusion-inpainting), and get an access token from here [huggingface access token](https://huggingface.co/docs/hub/security-tokens).
2. Run `win_config.bat`

**Comment by SpiderDKing** [comment]
ok. Thanks, it is running. I have not accepted the terms
