### ISSUE TITLE
Select for image size is almost invisible with some pictures

### ISSUE THREAD

**Issue by Eidenz** [Sanster/lama-cleaner#12]
The transparency effect can make it quite hard to read the sizes with some pictures. See the attached image.
![lama](https://user-images.githubusercontent.com/27901016/153366967-52d8a46c-88d8-441a-ae62-779ac5522663.png)

**Comment by Sanster** [comment]
Any suggestion？One way is to change the color of selected text, but I don't think this is good enought

<img width="205" alt="image" src="https://user-images.githubusercontent.com/3998421/153755650-fa6fbac9-c3d3-4945-8d9d-a511d6c11c46.png">

**Comment by Eidenz** [comment]
Well, I don't really see anything better if you want to keep the transparency. And yet, this will result in a new problem with some pictures that have lime color on the bottom..

Maybe trying a select panel without transparency, or very light instead of the almost fully-transparent one?

**Comment by blessedcoolant** [comment]
I've addressed this in my GUI overhaul (#25) that is currently being reviewed. If it gets merged, this can be closed.

![Untitled-1](https://user-images.githubusercontent.com/54517381/160896278-5934f3fd-b978-4cbf-8bf3-2a846b785da4.jpg)

**Comment by Sanster** [comment]
Light theme
<img width="698" alt="image" src="https://user-images.githubusercontent.com/3998421/162009521-92b67528-efd2-4e1d-ab1b-1548fbaad7b7.png">

Dark theme
<img width="699" alt="image" src="https://user-images.githubusercontent.com/3998421/162009460-43746978-881d-49af-ae11-7246e4d869bb.png">
