### ISSUE TITLE
zits model empty response

### ISSUE THREAD

**Issue by Edwardpillwin** [Sanster/lama-cleaner#121]
![image](https://user-images.githubusercontent.com/73528476/201452768-a877637b-4af3-4787-bb7a-5d9cd02f6da7.png)
I have download the zits model and run gui in cpu mode, but get an empty response after drawing, why?(It works with lama,ldm)
Thank  you very much!

**Comment by Sanster** [comment]
Empty Response may be caused by some errors(I really should pass the error to the frontend😅), please check the message in the terminal.

**Comment by Edwardpillwin** [comment]
![image](https://user-images.githubusercontent.com/73528476/201453220-d3b1d1ec-f470-4cb8-ae4a-183e717a64e6.png)
![image](https://user-images.githubusercontent.com/73528476/201453362-5a7d7582-a8ca-4a39-ba7f-f064e1318952.png)
![image](https://user-images.githubusercontent.com/73528476/201453308-c2e100e5-44fa-4f4c-8145-45f364c51aef.png)

Thank you for your response, I think it is because we need to add `from skimage import color` in zits.py

**Comment by Edwardpillwin** [comment]
I have slove this problem.
Add
```
from skimage import color
from skimage import feature
```
in zits.py
