### ISSUE TITLE
why is the result different？

### ISSUE THREAD

**Issue by seawater668** [Sanster/lama-cleaner#123]
run lama-cleaner --model=lama --device=cpu --port=8080 The result is as shown on the right

 run python /lama-cleaner/lama_cleaner/model/lama.py The result is as shown on the  left

![Image_20221115164501](https://user-images.githubusercontent.com/29244715/201872313-cfb6be67-ca83-4b89-8d8a-0e5b5fd466f9.png)

Why is the part marked by the red circle so different, the mask of the same area？

**Comment by Sanster** [comment]
Might be related to `hd_strategy`, by default (on the frontend) the `CROP` strategy is used. If you run `lama.py` directly, it uses the original image size

```
    hdStrategy: HDStrategy.CROP,
    hdStrategyCropTrigerSize: 1280, # only perform crop when image size larger then 1280
    hdStrategyCropMargin: 196
```

**Comment by seawater668** [comment]
@Sanster I modified and ran lama.py according to the above parameters you mentioned, but the result is still the same as before. What's going on? Did you do anything to the image?

**Comment by Sanster** [comment]
Can you add a breakpoint (before model forward)[https://github.com/Sanster/lama-cleaner/blob/964795ceb5a032ccad842ba57dd276387958f5ae/lama_cleaner/model/lama.py#L54] to check the difference(shape and value) between the image/mask coming from the front-end and the image/mask in your script?

**Comment by seawater668** [comment]
@Sanster 
 print("image.shape:",image.shape)
print("mask.shape:", mask.shape)
inpainted_image = self.model(image, mask)
print("inpainted_image :", inpainted_image .shape)

run：
image.shape: torch.Size([1, 3, 512, 512])
mask.shape: torch.Size([1, 1, 512, 512])
inpainted_image : torch.Size([1, 3, 512, 512])

**Comment by seawater668** [comment]
@Sanster 
run lama-cleaner --model=lama --device=cpu --port=8080 
Why can't the code be modified locally?

**Comment by Sanster** [comment]
Because it's installed by pip, the source code of pip installed package is under python's site-packages directory

**Comment by seawater668** [comment]
@Sanster Why are local results different from online results?
