### ISSUE TITLE
how to use the lama model when I have downloaded the "big-lama.pt" ?

### ISSUE THREAD

**Issue by miss-fang** [Sanster/lama-cleaner#124]
I have downloaded the "big-lama.pt" and move it to checkpoints directory.
but when I run "lama-cleaner --model=lama --device=cpu --port=8080 ", it started to downloading file again( and the download task will never be finished)...
so how can I use it directly?

**Comment by Sanster** [comment]
Please check directory path, it should be ~/.cache/torch/hub/checkpoints

**Comment by Sanster** [comment]
The model is downloaded from GitHub, maybe you can set up a VPN proxy in the terminal
