### ISSUE TITLE
how to create a public link

### ISSUE THREAD

**Issue by demirklvc** [Sanster/lama-cleaner#125]
hello i got it running on an windows pc. how can i create an public link so i can use it via web brwoser onc mac for example? best wishes @Sanster

**Comment by demirklvc** [comment]
please @Sanster

**Comment by Sanster** [comment]
How did you install lama-cleaner? If you installed it from `pip`, you can add `--host=0.0.0.0` when starting the server in the terminal. If you install by the one-click installer, you should first config it **not** start as a desktop app, and modify [tasks.py](https://github.com/Sanster/lama-cleaner/blob/964795ceb5a032ccad842ba57dd276387958f5ae/scripts/user_scripts/tasks.py#L128) add `--host=0.0.0.0` to the start command:

```python
c.run(
    f"lama-cleaner --model {model} --device {device} --hf_access_token={hf_access_token} --port {port} --host=0.0.0.0"
)
```

Once the server starts, find the IP address of your PC, and use it on your Mac via the web browser(This approach assumes your windows PC and Mac are in the same network). 

If you want a 'real' public link, you can check [ngrok](https://ngrok.com/)
