### ISSUE TITLE
Can't figure out how to run the frontend. The instructions don't work for me.

### ISSUE THREAD

**Issue by inhahe** [Sanster/lama-cleaner#129]
I'm on Ubuntu 22.04, Python 3.9

First, the instructions say to `cd lama_cleaner/app/ && yarn`
But I have no directory lama_cleaner anywhere, even after running `pip install lama-cleaner` and successfully starting lama-cleaner.
The closest thing I have to it is miniconda/bin/lama-cleaner, which isn't a directory.
So I went to a backup drive where I had a backup from when I had previously unzipped lama-cleaner on Windows and again tried `cd lama_cleaner/app/ && yarn`, and it said there was no such thing as yarn, but I could get it by installing something called cmdtest. So I installed that. Then I did `cd lama_cleaner/app/ && yarn` again, and it said, "00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one." So I tried `yarn build`, and it said, "00h00m00s 0/0: : ERROR: [Errno 21] Is a directory: 'build'". 
`yarn start` doesn't work either; it says "00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'".

The yarn commands didn't work under Windows either. On Windows I had tried `pip install yarn`, just in case the yarn I'm supposed to be running has to do with the Python package called yarn. I got 
"ERROR: Could not find a version that satisfies the requirement yarn (from versions: none)
ERROR: No matching distribution found for yarn"

**Comment by Sanster** [comment]
```bash
git clone https://github.com/Sanster/lama-cleaner.git
```

**Comment by Sanster** [comment]
yarn's [getting-started](https://yarnpkg.com/getting-started) meight be helpful
