### ISSUE TITLE
OpenCL version?

### ISSUE THREAD

**Issue by Casul51** [Sanster/lama-cleaner#13]
Is it going to have OpenCL version? (AMD GPU support?)

**Comment by Sanster** [comment]
Sorry, it won't be supported. Pytorch do [support AMD GPU](https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/)，but I don't have an AMD GPU to test it.

**Comment by mjc619** [comment]
I have no issues with running LAMA on the CPU, but depending on your OS setup you can set up a virtual instance inside WSL2 and use DirectML as the backend.
