### ISSUE TITLE
Something went wrong: TypeError: Failed to Fetch

### ISSUE THREAD

**Issue by lucasbr15** [Sanster/lama-cleaner#131]
Hello, I am trying to use Lama to remove a watermark, but I am getting the following error: "Something went wrong: TypeError: Failed to Fetch". I have tried all the templates, but I am still getting the same error.

Yesterday I had downloaded and tested Lama, it worked perfectly. I deleted it, and today I decided to download it again, but I am getting this error now.

I am using the "One click" version.

What could be causing this error?

Thanks.
![Screenshot_1](https://user-images.githubusercontent.com/97372669/202362431-b59c8ddd-e24e-41bc-82a2-443c8cf76a91.png)

**Comment by lucasbr15** [comment]
Hmm, I noticed that this error is happening because it is closing alone, see:
![Screenshot_2](https://user-images.githubusercontent.com/97372669/202363270-8c78a6e9-b7c7-4995-8f78-b420f67c6b24.png)

**Comment by lucasbr15** [comment]
Another observation is that when using mud-cleaner --model=mud --device=cuda --port=8080 it works normally, the problem is in the One Click alternative.

**Comment by Nondixistiamor** [comment]
Ver.1.1.2 also got the problem **"Something went wrong: TypeError: Failed to fetch"** from MacOS 13.3.1 CPU mode.
