### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by hq22-q** [Sanster/lama-cleaner#133]
After the area is selected, it can't be modified. It would be great if it could be adjusted

**Comment by Sanster** [comment]
You can enable `Manual Inpainting Mode` to gain some adjustability, it support undo/redo mask stroke, check https://github.com/Sanster/lama-cleaner/issues/116#issuecomment-1309638110

**Comment by hq22-q** [comment]
thank you ,I have deployed it on my server  (http://125.124.156.80:83/), and I want to access it with my phone, but the webpage (setting) isnot adaptive on the browser😗.This project is so interesting ,haha😁

**Comment by Sanster** [comment]
Unfortunately, it is not supported on phones, zooming, panning, and erasing on the touch screen is too complicated. 🥲
