### ISSUE TITLE
error:03000086:digital envelope routines::initialization error

### ISSUE THREAD

**Issue by inhahe** [Sanster/lama-cleaner#135]
I just installed yarn. 

When trying to run the frontend using "yarn start" or trying to do "yarn build" on Windows 10, I get an error:
 
D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app>"C:\Program Files\nodejs\node_modules\corepack\shims\yarn" start
i ｢wds｣: Project is running at http://192.168.56.1/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\public
i ｢wds｣: 404s will fallback to /
Starting the development server...

D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\py\lama-cleaner\lama-cleaner-main\lama-cleaner-main\lama_cleaner\app\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

------------------------

I want to modify the server code to not be a server and to run on automatically modified images with automatically generated masks, the only reason I'm trying to run the frontend is to try to figure out some default/good values for some of the config variables:

config = Config(
        ldm_steps=form["ldmSteps"],
        ldm_sampler=form["ldmSampler"],
        hd_strategy=form["hdStrategy"],
        zits_wireframe=form["zitsWireframe"],
        hd_strategy_crop_margin=form["hdStrategyCropMargin"],
        hd_strategy_crop_trigger_size=form["hdStrategyCropTrigerSize"],
        hd_strategy_resize_limit=form["hdStrategyResizeLimit"],
        prompt=form["prompt"],
        use_croper=form["useCroper"],
        croper_x=form["croperX"],
        croper_y=form["croperY"],
        croper_height=form["croperHeight"],
        croper_width=form["croperWidth"],
        sd_mask_blur=form["sdMaskBlur"],
        sd_strength=form["sdStrength"],
        sd_steps=form["sdSteps"],
        sd_guidance_scale=form["sdGuidanceScale"],
        sd_sampler=form["sdSampler"],
        sd_seed=form["sdSeed"],
        cv2_flag=form["cv2Flag"],
        cv2_radius=form['cv2Radius']
    )

**Comment by Sanster** [comment]
I found a nice project that may meet your needs.  https://github.com/saic-mdal/lama/issues/69#issue-1084159589



![](https://user-images.githubusercontent.com/42510606/146686067-b762d541-6bbe-45e0-b315-952a2f4632b2.gif)

**Comment by inhahe** [comment]
Thanks, I already tried that one. The results didn't come out like I'd
hoped (could have possibly been an error in how I did it). Basically, I
shrank an image, created a mask that highlighted the border (between the
shrunken image and the perimeter of the original size), then had the
program inpaint, then repeated the process 100 times. My intention was to
have the AI "zoom out" way beyond the original confines of the picture and
see what happens. All I got was noisy grey, though.

**Comment by fiskbil** [comment]
Change your `package.json` file so that the `scripts` section says
```
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "cross-env GENERATE_SOURCEMAP=false react-scripts --openssl-legacy-provider build",
```
This will fix this this issue. Alternatively downgrade to node.js v16.

**Comment by inhahe** [comment]
Thanks guys.

@Sanster It looks like stablediffusion-infinity has no instructions for installation or use. I might not be able to figure it out. I noticed that lama-cleaner has stablediffusion as one of its available models (sd15). Maybe that will work for me?

**Comment by Sanster** [comment]
In fact, if you don't want to develop front-end code, you do not need to compile front-end code, it's pre-compiled in the git repository, just start the server from the git repository root dir

```bash
python3 main.py --model lama
```
