### ISSUE TITLE
something wrong with dependencies

### ISSUE THREAD

**Issue by moliyadi007** [Sanster/lama-cleaner#138]
ERROR: Cannot install lama-cleaner==0.10.0, lama-cleaner==0.11.0, lama-cleaner==0.12.0, lama-cleaner==0.13.0, lama-cleaner==0.14.0, lama-cleaner==0.15.0, lama-cleaner==0.16.0, lama-cleaner==0.17.0, lama-cleaner==0.18.0, lama-cleaner==0.19.0, lama-cleaner==0.20.0, lama-cleaner==0.20.1, lama-cleaner==0.21.0, lama-cleaner==0.22.0, lama-cleaner==0.23.0, lama-cleaner==0.24.0, lama-cleaner==0.24.1, lama-cleaner==0.24.2, lama-cleaner==0.24.3, lama-cleaner==0.24.4, lama-cleaner==0.24.5, lama-cleaner==0.25.0, lama-cleaner==0.26.0, lama-cleaner==0.26.1, lama-cleaner==0.26.2, lama-cleaner==0.9.0, lama-cleaner==0.9.1, lama-cleaner==0.9.2 and lama-cleaner==0.9.3 because these package versions have conflicting dependencies.

**Comment by Sanster** [comment]
The same problem as  https://github.com/Sanster/lama-cleaner/issues/114, but currently doesn't know how to solve it.

Can you try installing lama-cleaner in a new `conda` or `pyenv` environment?

**Comment by Sanster** [comment]
please use python 3.7~3.9
