### ISSUE TITLE
能否增加API

### ISSUE THREAD

**Issue by FynnFbc** [Sanster/lama-cleaner#139]

**Comment by FynnFbc** [comment]
使用python 做自动化处理的时候直接调用API进行处理图片，批量处理

**Comment by FynnFbc** [comment]
When using python to do automatic processing, directly call the API for processing images, batch processing

**Comment by yier2333** [comment]
> 使用python 做自动化处理的时候直接调用API进行处理图片，批量处理

批量化的方法你找到了吗？我也想做这个，就是直接python代码里面输入原图和mask做clean，不想要这个界面，你最后解决了吗

**Comment by FynnFbc** [comment]
> > 使用python 做自动化处理的时候直接调用API进行处理图片，批量处理
> 
> 批量化的方法你找到了吗？我也想做这个，就是直接python代码里面输入原图和mask做clean，不想要这个界面，你最后解决了吗

你可以分析web server中的api是如何使用的，我不知道如何做mask，没有继续往下研究了

**Comment by phcbest** [comment]
api.py  里面都有,
![image](https://github.com/Sanster/IOPaint/assets/44636532/61ffac08-f623-43d4-b39d-ed93f0143ec6)

**Comment by Sanster** [comment]
开启后端服务后可以访问 `localhost:8080/docs` 查看 api 文档

<img width="1430" alt="image" src="https://github.com/Sanster/IOPaint/assets/3998421/6e6bb083-1f7e-498c-a334-8d3fe1eb0edd">
