### ISSUE TITLE
Can we add API?

### ISSUE THREAD

**Issue by FynnFbc** [Sanster/lama-cleaner#140]
When using python to do automatic processing, directly call the API for processing images, batch processing

**Comment by Sanster** [comment]
There is already an API [here](https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/server.py#L92), you can check the meaning of arg in `Config` at [here](https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/schema.py)

**Comment by innat-asj** [comment]
@Sanster Links are broken.

**Comment by Sanster** [comment]
code: https://github.com/Sanster/IOPaint/blob/main/iopaint/api.py

You can visit `http://127.0.0.1:8080/docs` to see the api document, after run `iopaint start`
