### ISSUE TITLE
GUI模式下，一段时间没有使用的话，后台就会自动退出

### ISSUE THREAD

**Issue by Summersoff** [Sanster/lama-cleaner#141]
显示App closed，但是并没有
![image](https://user-images.githubusercontent.com/44570237/203081500-1b1e9960-15b7-4f7b-9f40-b499ae3b16d4.png)

**Comment by Sanster** [comment]
close 之前是不是最小化了窗口几分钟或者切到了别的窗口几分钟？

**Comment by Summersoff** [comment]
对的，一般处于后台一段时间就会退出，几分钟这样

**Comment by Sanster** [comment]
notes to myself:
- related issue in flaskwegui: https://github.com/ClimenteA/flaskwebgui/issues/66
- [How can I make setInterval also work when a tab is inactive in Chrome?](https://stackoverflow.com/questions/5927284/how-can-i-make-setinterval-also-work-when-a-tab-is-inactive-in-chrome)

**Comment by Sanster** [comment]
fixed in https://github.com/Sanster/lama-cleaner/commit/0673fce4ec21fcc677dbdfa713423d9647c74d76


@Summersoff  可以升级到 `0.27.2` 再试试

**Comment by Summersoff** [comment]
看起来没问题了
