### ISSUE TITLE
How to use manga inpainter?

### ISSUE THREAD

**Issue by bropines** [Sanster/lama-cleaner#142]
![browser_2RguN1YvPe](https://user-images.githubusercontent.com/57861007/203314367-cfd1e3ed-8a2d-4e3b-b976-5c84a2b28596.png)
Or has it not been added to the GUI yet?

**Comment by Sanster** [comment]
hi, you can upgrade to the latest version to use it. 

```bash
pip install lama-cleaner==0.27.1
```

**Comment by bropines** [comment]
> hi, you can upgrade to the latest version to use it.
> 
> ```shell
> pip install lama-cleaner==0.27.1
> ```
I did so. the manga button did not appear.

**Comment by bropines** [comment]
Okay, after a full removal and installation, it was fixed. Sorry
