### ISSUE TITLE
sd效果没有runwayml的好

### ISSUE THREAD

**Issue by ljjsimon** [Sanster/lama-cleaner#144]
大佬，你有没有发现sd模型边缘处理效果没有runwayml官方的 https://app.runwayml.com/ai-tools/erase-and-replace 这个好。能一起研究下为什么么

**Comment by Sanster** [comment]
不考虑权重是否一致的问题的话，可能是一些后处理的区别？等这个 PR 合并了以后会有改善 https://github.com/runwayml/stable-diffusion/issues/21
