### ISSUE TITLE
I already have different SD models locally. Where do I have to place them to use them?

### ISSUE THREAD

**Issue by BrahRah** [Sanster/lama-cleaner#147]
Automatic1111 has a models folder where all the models can be placed in. I could not find something like that for LC.

**Comment by Sanster** [comment]
`.ckpt` model is not supported. The cache directories for different models:

- lama/ldm/zits/mat/fcf: ~/.cache/torch
- sd1.5: ~/.cache/huggingface

**Comment by BrahRah** [comment]
thanks
