### ISSUE TITLE
Models not workig.

### ISSUE THREAD

**Issue by BrahRah** [Sanster/lama-cleaner#148]
lama-cleaner --model=sd1.5 --device=cuda --port=8080
lama-cleaner --model=manga --device=cuda --port=8080

throw: lama-cleaner: error: argument --model: invalid choice:

Are they currently being added like mat?

**Comment by Sanster** [comment]
Yes, please update to the latest version `pip install lama-cleaner==0.27.2`

**Comment by BrahRah** [comment]
Ahh ic I've updated with git pull.
