### ISSUE TITLE
LDM Running out of memory

### ISSUE THREAD

**Issue by blessedcoolant** [Sanster/lama-cleaner#15]
I understand that the LDM model is intensive but I think something peculiar is happening. It always OOM's on the 3rd stroke. I tried lowering the steps but it doesn't matter. No matter what the step size is or the stroke size is, the model crashes on the 3rd stroke with an OOM.

Wondering if there might be a fix for that? I'm on a RTX3080.

**Comment by blessedcoolant** [comment]
Most likely coz

**Comment by Sanster** [comment]
I can't reproduce the problem.

**Comment by Sanster** [comment]
Add `torch.cuda.empty_cache()` after model forward helps to reduce GPU memory.

https://github.com/Sanster/lama-cleaner/commit/61fcffda94fb23ae22a3297116b37a49d62bd2e8#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R78

**Comment by Sanster** [comment]
When I tested on 3090 (24G), I found that the peak GPU memory usage still easily exceeded 8G

**Comment by Sanster** [comment]
Another option is to use fp16 for inference, but this requires reconverting the torchscript model, and the current model reports an error when using fp16.

**Comment by Sanster** [comment]
If anyone is interested, the code for converting torchscript model is [here](https://github.com/Sanster/latent-diffusion/tree/wip_torchscript).

**Comment by blessedcoolant** [comment]
> Add `torch.cuda.empty_cache()` after model forward helps to reduce GPU memory.
> 
> [61fcffd#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R78](https://github.com/Sanster/lama-cleaner/commit/61fcffda94fb23ae22a3297116b37a49d62bd2e8#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R78)

Cleaning the cache is definitely helping. The app hasn't crashed so far. Now I'm trying to see if there's a way to increase the ldm mode to be faster.

**Comment by 2blackbar** [comment]
the new model is strange, on second stroke it converts even area of first stroke, there must be some typo in the code.

**Comment by blessedcoolant** [comment]
That's correct. Can confirm that this happens.

**Comment by 2blackbar** [comment]
I does get nicer results tho, first model cant detect circular patterns/ovals , it works nice with perspective ines and straight patterns,  , would be great to have it trained for circles too like the new model which can look more artificial sometimes than first but it creates new details and results are very impressive but its one stroke only, second stroke just doesnt work so i make sure i get all areas with one stroke .

**Comment by Sanster** [comment]
> the new model is strange, on second stroke it converts even area of first stroke, there must be some typo in the code.

This is related to the current mask generation strategy. To preserve the previous inpainting results, first stroke is also used on second stroke mask, this works fine for LaMa model. From the results of your experiments, it may be better for ldm to use only the current stroke mask at a time.

|First Stroke Mask|Second Stroke Mask(with first storke)|
|------------|--------------|
|![stroke1](https://user-images.githubusercontent.com/3998421/158087465-a3fd5a6a-933c-4deb-ae28-80ad053aa64c.jpeg)|![stroke2](https://user-images.githubusercontent.com/3998421/158087469-73ca66a9-e160-49c4-8ead-fe95b0a78979.jpeg)|

**Comment by 2blackbar** [comment]
How we can change models to the one sdownloaded from https://github.com/CompVis/latent-diffusion or https://disk.yandex.ru/d/EgqaSnLohjuzAg
Cant find model files to just swap names around and use other downloaded models

**Comment by Sanster** [comment]
- latent-diffusion only has one model
- Change lama model: https://github.com/Sanster/lama-cleaner/issues/5#issuecomment-991846876

**Comment by Sazoji** [comment]
> If anyone is interested, the code for converting torchscript model is [here](https://github.com/Sanster/latent-diffusion/tree/wip_torchscript).

to this end, how would one convert a stable diffusion or a conditioned model into a .pt file for lama-cleaner?
load the .bin files to make a checkpoint and save it as a .pt?
