### ISSUE TITLE
How to run on colab

### ISSUE THREAD

**Issue by noriwaru** [Sanster/lama-cleaner#153]
Hello, I am looking for a way to run on colab. I have a question.

The link on the top page↓
https://colab.research.google.com/drive/1e3ZkAJxvkK3uzaTGu91N9TvI_Mahs0Wb?usp=sharing
When I run 「3. Start Lama Cleaner server」, I get the following code.

2022-12-10 06:31:14.909 | INFO     | lama_cleaner.model.lama:init_model:30 - Load LaMa model from: /root/.cache/torch/hub/checkpoints/big-lama.pt
2022-12-10 06:31:17.286 | INFO     | lama_cleaner.helper:load_jit_model:44 - Load model from: /root/.cache/torch/hub/checkpoints/clickseg_pplnet.pt
 * Running on http://0.0.0.0:4242/ (Press CTRL+C to quit)

I cannot access the site by clicking on "http://0.0.0.0:4242/". 
What do I do?

**Comment by guocuixia** [comment]
The same question

**Comment by guocuixia** [comment]
Did you solve it

**Comment by mgaitan** [comment]
Hey @Sanster  I've just tried a simpler way that doesn't require to setup ngrok but directly uses the Colab "proxy" public url. 

here is the notebook 
https://colab.research.google.com/gist/mgaitan/61ff6841552d5182535d91e989daad9d/lama-cleaner.ipynb

I hope this be useful

**Comment by noriwaru** [comment]
Thanks everyone. Sorry I forgot to reply.
