### ISSUE TITLE
Runs 1/2 speed on 4090 with CU113.

### ISSUE THREAD

**Issue by bbecausereasonss** [Sanster/lama-cleaner#154]
Hey there, Automatic1111's has similar issue the fix is to update the CU113 Pytorch to CU116, and then update some DLL's.

Not sure how to do it with this distro but on my 4090 I only get about 3-4 it/s should be 7-8

> 
torch_command = os.environ.get('TORCH_COMMAND', "pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu116")

**Comment by Sanster** [comment]
If you are using the window installer, you can try change this [line in win_config.bat file](https://github.com/Sanster/lama-cleaner/blob/main/scripts/user_scripts/win_config.bat#L10), and rerun `win_config.bat`

```
pip install torch==1.13.0 --extra-index-url https://download.pytorch.org/whl/cu116
```
