### ISSUE TITLE
Where Do I put command line arguments

### ISSUE THREAD

**Issue by EddieGithub26** [Sanster/lama-cleaner#156]

**Comment by Sanster** [comment]
In a terminal that has python environment. If you have no idea what `terminal` is, maybe you can try [One Click Installer for windows](https://github.com/Sanster/lama-cleaner/blob/main/scripts/README.md)

**Comment by EddieGithub26** [comment]
I am currently using the one click installer, I was just wondering where I could put command line arguments from there.

**Comment by Sanster** [comment]
You can add extra arguments at [tasks.py](https://github.com/Sanster/lama-cleaner/blob/main/scripts/user_scripts/tasks.py#L124)

**Comment by EddieGithub26** [comment]
thank you!
