### ISSUE TITLE
Web UI has Network timeout issue on macOS M1

### ISSUE THREAD

**Issue by thatjimupnorth** [Sanster/lama-cleaner#162]
I got everything up and running with the help of other threads with this:

docker run -p 8080:8080 \
-v /Users/jim/.cache/torch \
-v /Users/jim/.cache/huggingface \
--rm cwq1913/lama-cleaner:cpu-0.26.1 \

lama-cleaner --device=cpu --port=8080 --host=127.0.0.1 --model=sd1.5 --sd-disable-nsfw --sd-run-local

After starting Lama-cleaner the Web UI opens at the local address and starts to diffuse, but after about 30 seconds there's an Network has stopped responding error in the Web UI, even though the Terminal powershell shows the SD is still running. 

1 - How do I fix this?
2 - Where is the image output directory?

![Screenshot 2022-12-15 at 12 31 41](https://user-images.githubusercontent.com/113929527/207860272-ed7d8fd9-9ae8-4d59-8386-8b2542e81adf.png)

EDIT: It did exactly the same thing when installing with pip. I tried Docker without being fully familiar with how it works - which possibly answers my own question, as it does give a warning during install that the CPU didn't match what was expected, and in the Docker app it shows AMD64 instead of ARM64 (Apple M1).

**Comment by thatjimupnorth** [comment]
pip install lama-cleander==0.30.0

![Screenshot 2022-12-15 at 14 57 27](https://user-images.githubusercontent.com/113929527/207893351-202e882a-9e4c-475f-8bf0-9f5d58e05737.png)

But the process is still running in the command line:

![Screenshot 2022-12-15 at 15 07 19](https://user-images.githubusercontent.com/113929527/207895707-2dbcb427-5239-4179-a07c-837afebdc8d2.png)

So, presumably, somewhere on my computer there's an image of a Lego man sitting in a sports car, despite that the Web UI encountered a problem, but I have no idea where the Output directory is.

**Comment by Sanster** [comment]
![image](https://user-images.githubusercontent.com/3998421/207991627-7cca2a90-5230-4dd7-a4f7-317fcecc6651.png)

pytorch's package name is `torch` :smile: `pip install torch==1.13.0`

This is no output directory in lama-cleaner...If the model run successful, you can click download button on the bottom

![image](https://user-images.githubusercontent.com/3998421/207991540-b4a99244-7af5-41c7-82b9-7fef0dddcccc.png)

**Comment by Sanster** [comment]
Combine with [cropper feature](https://lama-cleaner-docs.vercel.app/features/croper_resize), sd1.5 run on M2 chip 1.5it/s (512x512) image size
