### ISSUE TITLE
paint _by_example doesn't work

### ISSUE THREAD

**Issue by bulutharbeli** [Sanster/lama-cleaner#163]
When I try to switch to paint by example it always returns this error https://prnt.sc/KAd197fvWngO`

**Comment by Sanster** [comment]
![image](https://user-images.githubusercontent.com/3998421/208109748-90c91bc8-8317-4043-97e9-24a343e83289.png)

You need a larger memory GPU to run paint_by_exmaple, I tested on 3080, and for a 512x512 image, paint_by_example needs around 5.6GB GPU memory.

**Comment by Sanster** [comment]
with new version(0.33.0) paint_by_example needs 2.6G (image size 512x512). Please check https://lama-cleaner-docs.vercel.app/memory#paint-by-example  Good luck
