### ISSUE TITLE
painting isn't working

### ISSUE THREAD

**Issue by shalevc1098** [Sanster/lama-cleaner#164]
Hello, whenever I try to paint then either the software just blackens the marked area or transforms it, but it never painted the things I asked it to. What can I do? I have an RTX 3070 Ti 8GB

**Comment by PixelPlayGG** [comment]
I have the same issue, lama model for object removal works fine. But the inpainting doesn't produce result at all, while the command prompt seem it's running the process of the whole GPU calculation. Something is happening right at the end when the calculation is done and the image has to be translated/superimposed at the masked area.

It's just transforming the masked area, tottaly ignoring prompts. The problem persists with both sd1.5 / sd2 irrelevant ot the amount of steps, sampler type, etc.

*sorry if I've butchered some terminology
