### ISSUE TITLE
Getting black image only

### ISSUE THREAD

**Issue by wirra55** [Sanster/lama-cleaner#167]
Hi, 
I am only getting a black blob where the mask is drawn instead of an image when using the SD1.5 and Paint by Example tools. I have the dreaded MSI 1660 Super GPU with 6gb VRAM. I added the --sd-disable-nsfw command line argument. Attached is the error message I get. Any solutions? 

Thanks
![LamaCleaner Error](https://user-images.githubusercontent.com/121200768/209023468-d9c626ae-4808-4aae-ae5d-23b4fa599cff.jpg)

**Comment by wirra55** [comment]
No reply to my previous question. Do you have any idea why this is not working for me?

Thanks
![LamaCleaner Error1](https://user-images.githubusercontent.com/121200768/210355635-e4dda0a5-1f73-4af5-b8f3-482178526bb4.jpg)

**Comment by Sanster** [comment]
Probably because of fp16 precision, I have released a new version that allows you to add the `--no-half` option to the startup command, please upgrade to 0.30.1(for one-click installer, rerun win_config.bat will install the newest version of lama-cleaner)

**Comment by wirra55** [comment]
Thanks very much for your reply. I have reinstalled and made the changes as suggested. When doing the "Dream" process I am getting a "Something went wrong: TypeError: Failed to fetch" message and the CMD window closes down. I was also getting this error sometimes before your update. Also when updating using win_config.bat there is a file not found error before it continues to install. Not sure if these things are related. I am a novice at this stuff so apologies for these issues.
![LamaCleaner Error3](https://user-images.githubusercontent.com/121200768/210451576-f0f6ed8a-acb6-46a7-8b72-2e365e446342.jpg)
![LamaCleaner Error2](https://user-images.githubusercontent.com/121200768/210451577-5ac6dd86-1b07-4ef2-af0e-714896457534.jpg)

**Comment by Sanster** [comment]
> Thanks very much for your reply. I have reinstalled and made the changes as suggested. When doing the "Dream" process I am getting a "Something went wrong: TypeError: Failed to fetch" message and the CMD window closes down. I was also getting this error sometimes before your update. Also when updating using win_config.bat there is a file not found error before it continues to install. Not sure if these things are related. I am a novice at this stuff so apologies for these issues. ![LamaCleaner Error3](https://user-images.githubusercontent.com/121200768/210451576-f0f6ed8a-acb6-46a7-8b72-2e365e446342.jpg) ![LamaCleaner Error2](https://user-images.githubusercontent.com/121200768/210451577-5ac6dd86-1b07-4ef2-af0e-714896457534.jpg)

Thanks for providing snapshots, there should be no problem with your operation, it definitely is an internal error in Lama Cleaner. I think `FileNotFoundError` can be ignored, it appears on my PC(3080), and my environment works fine. However, I don't have a 1660 GPU to reproduce the error. In the next release I will add `--cpu-offload` command line args, which will reduce the vRAM usage, it may be helpful for your error, please stay tuned...

**Comment by wirra55** [comment]
Thanks again for trying to help my problem. Just one last question. I have lama-cleaner installed on my E drive but when I update or load models these large files end up in this folder C:\Users\myname\.cache\huggingface. There is about 35gb in these folders. Is there anyway I can change this so these large files end up in my lama-cleaner folder on my E drive instead of my C drive?

Thanks again

**Comment by Sanster** [comment]
1. Copy `C:\Users\myname.cache\huggingface` to a drive(to avoid redownload model after change `HF_HOME`)
1. Change `win_start.bat` file, set new directory 

```bash
set TORCH_HOME=your_directory
set HF_HOME=your_directory
@call invoke start
```

**Comment by wirra55** [comment]
Thanks for your help. Your recent changes seem to have solved most of my problems. Sometimes the Dream function doesn't produce any results but that could be because of user error. :-)

Thanks again.
