### ISSUE TITLE
Error: CUDA out of memory

### ISSUE THREAD

**Issue by Novalien0424** [Sanster/lama-cleaner#169]
Tried quite a few models but all of them came back with this error.
Running on GTX1060 with 6GB vram.
Any advice to avoid this error? 
![image](https://user-images.githubusercontent.com/121502635/209681063-4026e791-bd83-471b-9eed-5c1f67747e40.png)

**Comment by Sanster** [comment]
- Using `lama` model would be helped(MAT model will pad input to square, which require more VRAM)
- Reduce the mask area( From the screenshot it looks like your mask size  is (1134, 422)), inpainting a small area once at a time

**Comment by DarkAlchy** [comment]
> * Using `lama` model would be helped(MAT model will pad input to square, which require more VRAM)
> * Reduce the mask area( From the screenshot it looks like your mask size  is (1134, 422)), inpainting a small area once at a time

Nope, same here using LDM

![image](https://user-images.githubusercontent.com/10561690/210296723-1370802f-c82d-4f72-ac78-f01ba6ca5240.png)

**Comment by Sanster** [comment]
With the new version (0.33.0) stable diffusion inpainting need 2GB for 512x512 image.  Please check https://lama-cleaner-docs.vercel.app/memory to see other memory saving method
