### ISSUE TITLE
Adding "--precision full" and "--no-half" args to sd

### ISSUE THREAD

**Issue by yattsu** [Sanster/lama-cleaner#170]
If I'm trying inpainting with sd1.5 or sd2, the mask is replaced by black. I used sd a few months back and it had the same problem, but adding "--precision full --no-half" solved my issue. The problem is that I've searched and I couldn't find where to pass the args.

**Comment by Sanster** [comment]
I have released a new version that allows you to add the `--no-half` option to the startup command, please upgrade to 0.30.1(for one-click installer, rerun win_config.bat will install the newest version of lama-cleaner)
