### ISSUE TITLE
[!] Not using xformers memory efficient attention.

### ISSUE THREAD

**Issue by ZeroCool22** [Sanster/lama-cleaner#171]
![545454](https://user-images.githubusercontent.com/13344308/210281331-d749c3b6-10d8-4be5-90cd-50a2e700a5c4.png)

![Screenshot_7](https://user-images.githubusercontent.com/13344308/210281371-f55216d8-0935-4fb7-9574-39f2b521e4f5.jpg)

Why not using it?

**Comment by ZeroCool22** [comment]
Downloaded the **One Click Installer** and now i don't get anymore that warning.

**Comment by DarkAlchy** [comment]
Using one click install this is a worthless tool to me since I keep getting CUDA oom errors with 6 gigs, YET I don't get them for inpainting in any other application so the memory saving features are just not here.

**Comment by Sanster** [comment]
With the new version (0.33.0) stable diffusion inpainting need 2GB for 512x512 image.  Please check https://lama-cleaner-docs.vercel.app/memory#paint-by-example
