### ISSUE TITLE
Running lama-cleaner on a Tesla T4 G1 Cloud Server takes 5.67s on average.

### ISSUE THREAD

**Issue by Seo-Hyung-San** [Sanster/lama-cleaner#173]
How much speed will be improved by changing from Tesla T4 G1 to RTX 3090 G2?

**Comment by Sanster** [comment]
Don't know which model you are using, and your other configs(like steps, and image size).

Here is my test on 3090:
- model: sd1.5
- xformers: Yes
- image size: 512x512
- steps: 50
- speed 16.8it/s
- latency:  3s
