### ISSUE TITLE
win_start.bat (cannot start)glitching，The desktop program could not be started

### ISSUE THREAD

**Issue by guocuixia** [Sanster/lama-cleaner#177]
Lama Cleaner One Click Installer----win_config.bat（successfully set） ----win_start.bat (cannot start)
。The desktop program could not be started

**Comment by guocuixia** [comment]
![1](https://user-images.githubusercontent.com/81362502/211787750-ddece3f7-e33b-46bb-b563-2f4053cf4e01.png)

**Comment by Sanster** [comment]
Something went wrong in the model downloading process, please delete model and run win_start.bat again. If you are in China a VPN proxy might be helpful for downloading process

**Comment by guocuixia** [comment]
Need a faster vpn download, thanks.

**Comment by guocuixia** [comment]
I want to change the directory where the model is stored, but I don't know how to correctly add the parameters to the command line

**Comment by guocuixia** [comment]
c.run(
    f"lama-cleaner --model-dir:  请问是在这个位置直接插入路径吗 {model} --device {device} --port {port} --gui --gui-size 1400 900 --sd-cpu-textencoder"
)

**Comment by Sanster** [comment]
是的（漏了个 --model），先要升级到 0.32.0（执行 win_config.bat）

```bash
c.run(
    f"lama-cleaner --model-dir xxxxx --model {model} --device {device} --port {port} --gui --gui-size 1400 900 --sd-cpu-textencoder"
)
```

**Comment by guocuixia** [comment]
我把.cache目录下的文件夹转移到D:\003\lama-cleaner\moxing里然后插入路径 启动闪退 是哪里出错了呢
 if desktop:
        c.run(
            f"lama-cleaner --model-dir D:\003\lama-cleaner\moxing --model {model} --device {device} --port {port} --gui --gui-size 1400 900 --sd-cpu-textencoder"
        )
    else:
        c.run(
            f"lama-cleaner --model {model} --device {device} --port {port}"
        )

**Comment by Sanster** [comment]
https://lama-cleaner-docs.vercel.app/install/windows_1click_installer
