### ISSUE TITLE
[2023.01.11] Where do you find lama-cleaner?

### ISSUE THREAD

**Issue by Sanster** [Sanster/lama-cleaner#178]
In the past two days, lama-cleaner got over 200 stars, I can't find any clues why this happen. I would appreciate it if any recent stargazers could tell me where they saw the lama-cleaner(really curious 🤔 ).

**Comment by gaoxinge** [comment]
[Traffic analysis](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-traffic-to-a-repository) in [insights](https://github.com/Sanster/lama-cleaner/pulse) may help.  In traffic analysis, you can use [referring sites](https://hodovi.cc/blog/githubs-repository-traffic-analytics/) to find where users are from if they come by a hyperlink.

**Comment by Sanster** [comment]
Thanks! Found the source: https://www.youtube.com/watch?v=Anvr8tR3shM&feature=youtu.be&ab_channel=%E9%9B%B6%E5%BA%A6%E8%A7%A3%E8%AF%B4
