### ISSUE TITLE
Support for high resolution file

### ISSUE THREAD

**Issue by Michaelwhite34** [Sanster/lama-cleaner#18]
We can crop the image,use lama and paste back to the original image.

**Comment by Michaelwhite34** [comment]
Or we can select a box and lama only affect this region,this way we can do many parts at a time.

**Comment by Sanster** [comment]
> Or we can select a box and lama only affect this region,this way we can do many parts at a time.

You can press `cmd/ctrl` to enable multi-stroke drawing

**Comment by Sanster** [comment]
> We can crop the image,use lama and paste back to the original image.

- You can use original image size(the last  one on image size selector) to do inpainting.

<img width="156" alt="截屏2022-03-20 上午10 11 55" src="https://user-images.githubusercontent.com/3998421/159144997-977a933b-dc92-4d7d-b0b5-81681fab4cd7.png">

- Reasons for cropping images I can think of:
1. Full size forward is slow
2. Model not performe well on full size image

May I ask what problem did you encounter in your actual usage scenario?

**Comment by Michaelwhite34** [comment]
> > We can crop the image,use lama and paste back to the original image.
> 
> * You can use original image size(the last  one on image size selector) to do inpainting.
> 
> <img alt="截屏2022-03-20 上午10 11 55" width="156" src="https://user-images.githubusercontent.com/3998421/159144997-977a933b-dc92-4d7d-b0b5-81681fab4cd7.png">
> 
> * Reasons for cropping images I can think of:
> 
> 1. Full size forward is slow
> 2. Model not performe well on full size image
> 
> May I ask what problem did you encounter in your actual usage scenario?

I am using a high resolution file with a lot of elements,if I use the original resolution it will just give error.If I use low res option,the detail will be lost.

**Comment by Sanster** [comment]
1. What is the size of your image？
2. What is error outputs?

**Comment by Michaelwhite34** [comment]
> 1. What is the size of your image？
> 2. What is error outputs?

6000*6000 
[local host 8080 says object event]

**Comment by Sanster** [comment]
Add crop mode for very large image, this helps with memory issues. But I noticed that lama behaves mediocrely on very large resolution(7000x5000) images, you can try it on your picture.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/3998421/159610609-0b935220-aae0-4fe2-8d84-fbe88a805514.png">

**Comment by Michaelwhite34** [comment]
> Add crop mode for very large image, this helps with memory issues. But I noticed that lama behaves mediocrely on very large resolution(7000x5000) images, you can try it on your picture.
> 
> <img alt="image" width="846" src="https://user-images.githubusercontent.com/3998421/159610609-0b935220-aae0-4fe2-8d84-fbe88a805514.png">

Tried it,it works best if the bounding box size is much smaller than crop size,otherwise it gives strange result.

**Comment by Sanster** [comment]
I also noticed this problem. Change crop method in [release 0.6.1](https://github.com/Sanster/lama-cleaner/releases/tag/0.6.1). Hope it works better on your data

**Comment by Sanster** [comment]
I tested [cleanup.pictures](https://cleanup.pictures/)  HD mode on large resolution image(7000x5000), the result is good

|lama-cleaner result| cleanup.pictures HD result|
|------|------------|
|![large size](https://user-images.githubusercontent.com/3998421/161233053-8ef21a04-325b-4df0-b70a-7b25a44816d1.jpg)|![clarisse-meyer-fegQqTTEolA的_large_cleanup1](https://user-images.githubusercontent.com/3998421/161233202-ecef0553-505c-475e-935c-891876e13573.jpeg)|

After reading the code, I summarize their **HD mode** processing as follow: 
1. [Resize image]( https://github.com/initml/cleanup.pictures/blob/main/src/App.tsx#L64)(RESIZE_HD=2048) in frontend
2. [Pass resized](https://github.com/initml/cleanup.pictures/blob/main/src/context/EditorContext.tsx#L296) image to backend, alse pass a `useHD` to backend, maybe some extra processing happened in backend
3. [renderOutput](https://github.com/initml/cleanup.pictures/blob/main/src/context/EditorContext.tsx#L207) function for HD mode

**Comment by Michaelwhite34** [comment]
> I tested [cleanup.pictures](https://cleanup.pictures/) HD mode on large resolution image(7000x5000), the result is good
> 
> lama-cleaner result	cleanup.pictures HD result
> ![large size](https://user-images.githubusercontent.com/3998421/161233053-8ef21a04-325b-4df0-b70a-7b25a44816d1.jpg)	![clarisse-meyer-fegQqTTEolA的_large_cleanup1](https://user-images.githubusercontent.com/3998421/161233202-ecef0553-505c-475e-935c-891876e13573.jpeg)
> After reading the code, I summarize their **HD mode** processing as follow:
> 
> 1. [Resize image](https://github.com/initml/cleanup.pictures/blob/main/src/App.tsx#L64)(RESIZE_HD=2048) in frontend
> 2. [Pass resized](https://github.com/initml/cleanup.pictures/blob/main/src/context/EditorContext.tsx#L296) image to backend, alse pass a `useHD` to backend, maybe some extra processing happened in backend
> 3. [renderOutput](https://github.com/initml/cleanup.pictures/blob/main/src/context/EditorContext.tsx#L207) function for HD mode
> 
> ```ts
> // originalImage is large resolution image 
> outputCtx?.drawImage(originalImage, 0, 0)
> // patch is same size with originalImage, upscaled from RESIZE_HD=2048. Only mask area is completely none transparent
> outputCtx?.drawImage(patch, 0, 0)
> ```

Just found out that the output file is compressed.I used a 2.64MB jpeg file and output is 728kb.I import them into photoshop and difference them.There is significant difference within threshould 5,I guess it is jpeg compression.

**Comment by buddylee7** [comment]
Being relatively new at this, how do you run it in “HD Mode”?

**Comment by Sanster** [comment]
@buddylee7 [cleanup.pictures](https://cleanup.pictures/) 5$/month or you can wait for this feature to be implemented in this free project

**Comment by Sanster** [comment]
@Michaelwhite34 So in your data, excluding pictures being compressed, you are satisfied with the inpainting quality of cleanup.pictures HD mode, right?

**Comment by Michaelwhite34** [comment]
> @Michaelwhite34 So in your data, excluding pictures being compressed, you are satisfied with the inpainting quality of cleanup.pictures HD mode, right?

Not sure,seems I need to create an account,something like that.I don't think it will be good on very detailed photos though,once you downsize it,the detail is lost and you can't super-res to bringit back..

**Comment by Sanster** [comment]
Now we have a `Resize Strategy` for high resolution images, it works better on my data(7000x5000) compare to `Crop Strategy`, at the cost of taking up more GPU memory.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/3998421/164240569-19d118eb-9d48-4582-992c-aa880718a35f.png">

**Comment by Sanster** [comment]
Yes. Use `Resize`(default value) high resolution strategy
