### ISSUE TITLE
Cuda is not working on A100 GPU

### ISSUE THREAD

**Issue by captraza3** [Sanster/lama-cleaner#184]
I also tried using docker. But it's showing this error.

docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by Sanster** [comment]
This looks like a docker error log, I suggest you try `sleep infinity` as entry point to start the container and see if it starts successfully

**Comment by captraza3** [comment]
I tried this but did not work. I also tried using this command "lama-cleaner --model=lama --device=cuda" but it taken 9 minutes to load the model. When i upload the image to test the lama model. So I waited 3 minutes but still working and did not give any response. Device name is "GRID A100d-1-10C MIG 1g.10gb".  Is lama-cleaner compatible for this device?

**Comment by cesar-avalos3** [comment]
You are actually using a virtual GPU (MIG), a slice of the whole A100. In theory it should work fine, but you are getting 1/7 of the whole card's resources, so it might be a bit slower.

**Comment by Sanster** [comment]
> could not select device driver "" with capabilities: [[gpu]].

I found an issue on the Nvidia-docker GitHub repository, which might be helpful [could not select device driver "" with capabilities: [[gpu]]. #1034](https://github.com/NVIDIA/nvidia-docker/issues/1034)
