### ISSUE TITLE
ImportError: cannot import name 'CompVisVDenoiser' from 'k_diffusion.external'

### ISSUE THREAD

**Issue by emmajane1313** [Sanster/lama-cleaner#187]
Getting this import error after installing with pip 

`ImportError: cannot import name 'CompVisVDenoiser' from 'k_diffusion.external' (/Users/devdesign/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/k_diffusion/external.py)`

Running on m1 mac. I've installed lama before a few months back and it worked fine on the same machine. But when reinstalling currently i'm now getting this import error. Any fix?

**Comment by Sanster** [comment]
Find a similar issue https://github.com/riffusion/riffusion-app/issues/17,   maybe downgrading diffusers to an older version would help.

**Comment by emmajane1313** [comment]
do you know which version? i just tried a few but i keep getting an error saying that lama requires 0.10.2, which is the original version i had

**Comment by Sanster** [comment]
Found the source.  There is no `k_diffusion.external` module in the older version of k-diffusion, please upgrade to the newest version `pip install -U k-diffusion`

**Comment by Sanster** [comment]
Open an issue in diffusers: https://github.com/huggingface/diffusers/issues/2013

**Comment by emmajane1313** [comment]
ok thank you!
