### ISSUE TITLE
App closed

### ISSUE THREAD

**Issue by SuperMaximus1984** [Sanster/lama-cleaner#188]
I have the following response in Terminal when launch Lama-Cleaner:

```
flaskwebgui - [INFO] - Opening browser at http://127.0.0.1:59494
flaskwebgui - [INFO] -  * Running on http://127.0.0.1:59494/ (Press CTRL+C to quit)
flaskwebgui - [INFO] - App closed
flaskwebgui - [INFO] - Closing connections...
```
What can be the issue & how to fix it?

**Comment by Sanster** [comment]
When starting as a desktop application, the backend server will close if the window is closed after a few seconds. If you have the application turned off, this is normal.

If you didn't close the app window, it might be a bug(should have been fixed in https://github.com/Sanster/lama-cleaner/issues/141#issuecomment-1323746931), please do not start as desktop application to solve this problem temporarily.

**Comment by SuperMaximus1984** [comment]
> When starting as a desktop application, the backend server will close if the window is closed after a few seconds. If you have the application turned off, this is normal.
> 
> If you didn't close the app window, it might be a bug(should have been fixed in [#141 (comment)](https://github.com/Sanster/lama-cleaner/issues/141#issuecomment-1323746931)), please do not start as desktop application to solve this problem temporarily.

Maybe it has something in common with the error I get from win_config.bat?

```
Traceback (most recent call last):
  File "d:\Python Stuff\Lama-Cleaner\installer\Scripts\conda-unpack-script.py", line 226, in <module>
    update_prefix(os.path.join(new_prefix, path), new_prefix,
  File "d:\Python Stuff\Lama-Cleaner\installer\Scripts\conda-unpack-script.py", line 66, in update_prefix
    with open(path, 'rb+') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'd:\\Python Stuff\\Lama-Cleaner\\installer\\Library\\bin\\libcrypto-1_1-x64.dll.c~.conda_trash'
Collecting package metadata (current_repodata.json): done
Solving environment: done
```
But after this I am able to config normally.
Yes, when I run Lama-Cleaner in browser, it works, though I couldn't attain any feasible result due to CUDA out of memory (now digging issues section further on).

**Comment by Sanster** [comment]
This error also occurs in my environment and can be ignored.

Add a [Memory](https://lama-cleaner-docs.vercel.app/memory) section to the docs, hope it helps.

**Comment by Sanster** [comment]
New command line arg `--no-gui-auto-close` added in 0.34.0 https://github.com/Sanster/lama-cleaner/releases/tag/0.34.0
