### ISSUE TITLE
PLMS sampler and DDIM sampler of ldm model are always crashing

### ISSUE THREAD

**Issue by FrankWuensch95** [Sanster/lama-cleaner#191]
![image](https://user-images.githubusercontent.com/103488558/213725800-1f936b02-1b99-42eb-9345-e97cb1f92627.png)

![image](https://user-images.githubusercontent.com/103488558/213726037-3a986f84-d352-4831-8cf7-f847e6ceea6e.png)

As you can see on the images above, there seems to be a difference of a couple of pixels in the dimensions of the image pad between the original size of the image and the _final forward pad size_. This seems to ends in a total crash of the file processing.

**Comment by Sanster** [comment]
LDM model needs the input image height and width to be divisible by 32, so the padded size is a little larger.

I don't see any error messages in your logs, do you have any other error messages?
