### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by IlyasVlasovGit** [Sanster/lama-cleaner#192]
Hello! Sorry to bother if you already explained this one, couldn't find a solution (
Get error while trying to run the app through terminal:

```
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:997)
```

I am noob in python so have no idea how to fix or what does it mean, would be great if you can help.

Terminal command: 
lama-cleaner --model=lama --device=cpu --port=8080

- Platform: macOS-13.0-arm64-arm-64bit
- Python version: 3.10.0
- torch: 1.13.1
- Pillow: 9.4.0
- diffusers: 0.10.2
- transformers: 4.25.1
- opencv-python: 4.7.0.68
- xformers: N/A
- accelerate: 0.15.0
- lama-cleaner: 0.34.0

And afterwards big message in red frame which results in the error mentioned above:
![image](https://user-images.githubusercontent.com/18146231/214146438-0fec6eda-9f98-4eec-b316-783721e7af8c.png)

**Comment by Sanster** [comment]
This is due to network problems, you can manually download the model to the specified directory, https://lama-cleaner-docs.vercel.app/install/download_model_manually
