### ISSUE TITLE
I am quite new but was able to install lama-cleaner (how to install x-formers?).

### ISSUE THREAD

**Issue by StreLa1st** [Sanster/lama-cleaner#195]
Now I want to install x-formers, but I don't know how. i have lama-cleaner docker archive and command link https://github.com/Sanster/lama-cleaner/releases/tag/docker-0.33.0

where to enter them? and where to throw these files?
thank you for your reply!!

**Comment by Sanster** [comment]
You need to install [docker](https://www.docker.com/) on your computer, then just run the `docker run...` command(change the cache_dir), xformers is already installed in the docker image.

```bash
docker run --gpus all -p 8080:8080 \
-v /path/to/cache_dir:/root/.cache/ \
--rm cwq1913/lama-cleaner:gpu-0.33.0 \
lama-cleaner --device=cuda --port=8080 --host=0.0.0.0 --enable-xformers
```

**Comment by StreLa1st** [comment]
> Вам нужно установить [докер](https://www.docker.com/) на свой компьютер, затем просто выполнить `docker run...`команду (изменить cache_dir), xformers уже установлен в образе докера.
> 
> ```shell
> docker run --gpus all -p 8080:8080 \
> -v /path/to/cache_dir:/root/.cache/ \
> --rm cwq1913/lama-cleaner:gpu-0.33.0 \
> lama-cleaner --device=cuda --port=8080 --host=0.0.0.0 --enable-xformers
> ```
