### ISSUE TITLE
No module named 'triton'

### ISSUE THREAD

**Issue by shanin-ivan** [Sanster/lama-cleaner#198]
Hi, I using Windows 1-Click Installer
I installed xformers and when I run win_start I get an error

```
2023-01-29 21:52:33.126 | INFO     | lama_cleaner.parse_args:parse_args:88 - Loading installer config from C:\Users\Ivan\Desktop\lama-cleaner\win_start.bat\..\installer_config.json
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
```
I would be glad if someone could help me.

**Comment by Sanster** [comment]
- 1-Click Installer use python3.10, and currently [triton](https://github.com/openai/triton) only provide binary wheels 3.6-3.9
- It's ok to not install triton, you can still gain the benefit from xformers, in my tests it had almost no effect on the inference speed of the sd model

**Comment by DominusFL** [comment]
I have this same problem, so I can't run it. Anyone figure it out yet? Can't run it otherwise.

**Comment by xiaowangaixuexijishu** [comment]
I have installed the big-lama.pt model, but this problem is still happening at startup。ModuleNotFoundError: No module named '_lzma'

**Comment by Saaalih2g** [comment]
ماهذا البرنامج وفوائده واستخدامه

في أربعاء، 5 يونيو، 2024 في 5:23 ص، كتب xiaowangaixuexijishu <
***@***.***>:
