### ISSUE TITLE
The features that I think can be added to lama-cleaner will be much better

### ISSUE THREAD

**Issue by kingal2000** [Sanster/lama-cleaner#199]
First of all, it is better to add a section for editing the mask, I mean to clean it
Second, for cuda, make it so that it has the ability to reduce or increase its use so that the error is cuda run out of memory
It is not a problem to slow down   Strictly MAT  Erase model
And it is better to add the use of all gpu or to use both gpu and cpu at the same time so that the pressure is not only on one device, I am not a programmer, I just said my opinion, it would be great 
And thanks for making this good app

**Comment by Sanster** [comment]
New release 1.0.2: MAT model support fp16(default), require less vRAM and run faster
