### ISSUE TITLE
Need to keep exif data

### ISSUE THREAD

**Issue by linguowei** [Sanster/lama-cleaner#202]
Now after lama-cleaner finishes processing the picture, the exif data is also cleared

**Comment by linguowei** [comment]
> fixed in `0.35.0`

The version installed through pip is still 0.34.0

**Comment by Sanster** [comment]
Please try `pip3 install lama-cleaner==0.35.0`

**Comment by linguowei** [comment]
> Please try `pip3 install lama-cleaner==0.35.0`

It works now, thanks

**Comment by jaankoppe** [comment]
Is it possible to add this as an option? For example, if I use an image directly taken with a phone that has rotation information, then after the inpainting process it rotates the image.
