### ISSUE TITLE
Use alternate GPU?

### ISSUE THREAD

**Issue by JenXIII** [Sanster/lama-cleaner#203]
Hi, great tool.  I'm using the Windows 1-click install method, and it seems to default to my display GPU.  However, I have a more powerful secondary GPU I use for CUDA applications.  Is there a file or argument I can modify to direct the program to use an alternate GPU device by default?  If it's already supported, maybe add it to the documentation.

**Comment by Sanster** [comment]
Can you try add follow line before lama-cleaner starts in [win_start.bat](https://github.com/Sanster/lama-cleaner/blob/main/scripts/user_scripts/win_start.bat#L7)?

```bat
SET CUDA_VISIBLE_DEVICES="1"
```

**Comment by JenXIII** [comment]
It works if I remove the quotation marks around 1.  Thanks!
