### ISSUE TITLE
请问这个问题如何解决？

### ISSUE THREAD

**Issue by hc-1962518420** [Sanster/lama-cleaner#206]
![image](https://user-images.githubusercontent.com/62363165/217823265-125ef059-7897-443a-a9b3-292a30d27f5e.png)

**Comment by Sanster** [comment]
模型下载有问题，参考[这里](https://lama-cleaner-docs.vercel.app/install/download_model_manually)手动下载，再放到对应目录：https://lama-cleaner-docs.vercel.app/frequently_asked_questions#where-are-models-downloaded

**Comment by hc-1962518420** [comment]
感谢，已经解决
