### ISSUE TITLE
How to install Xformers in Windows Installer v2. I am New please help me!!

### ISSUE THREAD

**Issue by xmartysa** [Sanster/lama-cleaner#207]

**Comment by Kingal20000** [comment]
Me too

**Comment by xmartysa** [comment]
Hope someone help us :(

**Comment by Sanster** [comment]
Replace the following two lines in `win_config.bat`
```bash
@call conda install -y cudatoolkit=11.3
@call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
```

**New**

```bash
@call conda install -y cudatoolkit=11.7
@call pip3 install torch --extra-index-url https://download.pytorch.org/whl/cu117
@call pip3 install xformers
```

**Comment by xmartysa** [comment]
> Replace the following two lines in `win_config.bat`
> ```bash
> @call conda install -y cudatoolkit=11.3
> @call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
> ```
> 
> **New**
> 
> ```bash
> @call conda install -y cudatoolkit=11.7
> @call pip install torch --extra-index-url https://download.pytorch.org/whl/cu117
> @call pip install xformers
> ```

Thank you so much sir ☺️, It works!!
