### ISSUE TITLE
FR: Reuse last mask

### ISSUE THREAD

**Issue by JenXIII** [Sanster/lama-cleaner#209]
In a lot of cases I find that it's at first unclear which method/settings is best to apply to a certain image+mask, so I find myself needing to reenter the mask fairly often to try various approaches. 

Also, there can be cases where a second application is needed (with a different method, or just to clean up artifacts left by the first pass) and the first mask will suffice for the second step.

To better facilitate these two use cases, it would be nice if there was a button and/or hotkey in the UI to allow applying the last mask used with the current image & settings.

**Comment by Sanster** [comment]
This can be achieved by the following operations, although it does a little bit 🤏complicated

1. Prepare a mask

Enable download mask in settings, when clicking the download button, you will get a mask. Or you can also prepare a mask by yourself.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/3998421/218619798-f905b1a0-47b2-424c-9e43-61bf990006a4.png">

2. Upload the mask and run different models. 

[![Watch the video](https://user-images.githubusercontent.com/3998421/218621794-838873c3-5d78-48da-8a8c-c662b7d1c792.png)](https://youtu.be/S7J4CtAx7kY)

**Comment by JenXIII** [comment]
I am aware it is possible to do things like this.  However workflow-wise it is not very ideal.

Usually, a mask is only needed once if I am good at predicting which method/settings are needed, and/or the task is simple.  However, in the case the cleaning is not as intended, then I may need that mask I just made again, except it is now gone and I must remake it.

The workaround for this would be to just save EVERY mask I make, since I do not necessarily know which ones will need reuse.  However, since most masks are not useful after their first application, this leads to wasted time/space in dealing up with extraneous mask files.  Also, it is kind of clunky to have to go and select it from a system dialogue rather than just hit a "reuse previous mask" button.

**Comment by Sanster** [comment]
see: https://github.com/Sanster/lama-cleaner/releases/tag/0.36.0
