### ISSUE TITLE
[Feature Request] Support for passing in image path parameters to start

### ISSUE THREAD

**Issue by photkey** [Sanster/lama-cleaner#21]
When used as a local tool, most of the time you may only need to process a single photo, and it could be a bit more convenient if it could support passing in the image path at startup, eliminating the need to manually select the path.
Let's say the following.
```
python3 main.py --device=cuda --port=8080 --model=lama --image path/example.jpg

python3 main.py --device=cuda --port=8080 --model=ldm --ldm-steps=50 --image path/example.jpg
```

**Comment by Eidenz** [comment]
I personally don't really see how that's convenient..
Wouldn't it take much longer to write the path rather than just selecting the image in a select window (or using drag&drop)?

(and copy-pasting the path would mean you did open the folder at some point anyway)

**Comment by photkey** [comment]
If you support command pass in parameters to start, then you can do it with other software: mouse select image One click to start CMD and execute the command `python3 main.py --device=cuda --port=8080 --model=lama --image path/example.jpg`.

I recorded a simple animation of a usage similar to this, the demonstration is to select the URL `https://github.com/Sanster/lama-cleaner` and then open CMD with one click and execute: `cd /d D:\MySoft\GitHub && git clone --depth=1 "https://github.com/Sanster/lama-cleaner.git" && start D:\MySoft\GitHub`
![lama-cleaner](https://user-images.githubusercontent.com/60434581/159938789-9aa2a84b-2919-419a-a72d-626e74ad14da.gif)

**Comment by photkey** [comment]
> I can see a few uses for this now that you mention it. And doesn't seem complicated to implement so why not

I only know a little bit of basic syntax to get started with python and can't figure it out, can you implement this?

**Comment by blessedcoolant** [comment]
I'm working on it. Have the image loading already but trying to see the optimal way to handle this. I'll make a pull request when I'm done.

**Comment by Sanster** [comment]
Thanks to @blessedcoolant , main.py now support `--input` argument

```bash
python3 main.py --input /path/to/image.jpg --gui
```

**Comment by photkey** [comment]
@[blessedcoolant](https://github.com/blessedcoolant) Thanks for your excellent work, now it's very handy and very cool!
![lama-cleaner](https://user-images.githubusercontent.com/60434581/160339147-b6d20c94-5a95-4b26-80c8-fc6134837cd8.gif)

**Comment by blessedcoolant** [comment]
> @[blessedcoolant](https://github.com/blessedcoolant) Thanks for your excellent work, now it's very handy and very cool! ![lama-cleaner](https://user-images.githubusercontent.com/60434581/160339147-b6d20c94-5a95-4b26-80c8-fc6134837cd8.gif)

You are welcome. :)
