### ISSUE TITLE
Implementing lama-refinement?

### ISSUE THREAD

**Issue by syleeVeluga** [Sanster/lama-cleaner#215]
Hi,
I am trying to implement the lama refinement feature and hard time to figure it out.
Any idea where I start?

**Comment by Sanster** [comment]
Lama Cleaner use the Torchscript model to do inference, as far as I know, lama-refinement requires `backward` process and need at least 24GB vRAM, so one should copy all training code(which is a lot) and integrate it into https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/model/lama.py

**Comment by syleeVeluga** [comment]
Thanks will check it out
