### ISSUE TITLE
Preserve mask areas when using SD models

### ISSUE THREAD

**Issue by lucellent** [Sanster/lama-cleaner#216]
**Imagine this:** I'm inpainting an image and draw over some things. I then enter a prompt and generate content with Stable Diffusion. I don't like it, but now that the content has already been generated, I have to paint over the area again, rather than having the mask preserved.

This is an issue when working with a lot of painted areas and you don't want to waste time carefully creating a mask again.

**Comment by Sanster** [comment]
Actually, this feature is already there! When using sd/paint_by_example model, after inpainting once, clicking the `Dream` button again will reuse the previous mask. 

There are no user-friendly hints for this feature, so perhaps it could be optimized in conjunction with this issue https://github.com/Sanster/lama-cleaner/issues/209

**Comment by lucellent** [comment]
> Actually, this feature is already there! When using sd/paint_by_example model, after inpainting once, clicking the `Dream` button again will reuse the previous mask and previous image.
> 
> Tips to myself: There are no user-friendly hints for this feature, so perhaps it could be optimized in conjunction with this issue #209

I opened this "issue" because this exact method doesn't work for me - I make a mask once, write a prompt, click "Dream" - it works. If I click dream again (or first change the prompt) - nothing happens because there's no visible mask, so while it appears as if there's an image being generated, nothing actually ends up getting generated due to the mask not being there

**Comment by lucellent** [comment]
PS: Dunno if I should open a new request for this but it would be useful if we had a restore brush - when cleaning up with the regular lama model, there could be another brush and when used on the image it would restore the initial look of the image (instead of undo-ing everything which is entirely different thing)

What I'm suggesting is the same restore brush as in Photoshop (History Brush Tool)

**Comment by Sanster** [comment]
Both **Stable Diffusion** and **Paint by Example** model support this feature. Can you check whether the `seed` button is enabled or not? By design, if it's **not enabled**, every time the result will be different.

<img width="303" alt="截屏2023-02-17 09 08 22" src="https://user-images.githubusercontent.com/3998421/219523668-48fa000b-58d7-4859-8947-e826fef06492.png">

**Comment by Sanster** [comment]
Other models also add support for reuse last mask: [0.36.0](https://github.com/Sanster/lama-cleaner/releases/tag/0.36.0)
