### ISSUE TITLE
May you upgrade cuda as torch to Found existing installation: torch 1.13.1+cu117

### ISSUE THREAD

**Issue by AkoZ** [Sanster/lama-cleaner#217]
As other softs are using this one, the torch1.12+cu113 is just obsolete and make a fuss with the premium installs..
With no compatibility, Lama has to be down to keep other functionning.
is it possible ?

**Comment by AkoZ** [comment]
oops but ?
in fact i just try to replace the original numbers by the used by others ones .. and torch 1.13.1+cu117 works all OKi
even the web_config opens right and .. yep installed in webui111 scripts folder ... but it seems to get a torch1.12.1 instead of 1.13.1 ! .. so to review.
And the nsfw even disabled witht he win_config, goes on censured parts ! (so black results)

**Comment by Sanster** [comment]
torch 1.13.1 + cu117 works with Lama Cleaner, please check issue:  https://github.com/Sanster/lama-cleaner/issues/207

**Comment by AkoZ** [comment]
issue #207 is 404 now ...

**Comment by Sanster** [comment]
https://lama-cleaner-docs.vercel.app/frequently_asked_questions#how-to-install-xformers-in-windows-installer-v2
