### ISSUE TITLE
Getting error starting Lama Cleaner

### ISSUE THREAD

**Issue by Dreamz-Dziner** [Sanster/lama-cleaner#218]
When I double click win_start I get this: error: python.exe- Entry Point Not Found. Can you please help me.
PS: I am running a windows desktop installer version
![Untitled-2](https://user-images.githubusercontent.com/69266893/219165722-7acf4b42-abdd-4953-bf96-bf0ad61f232b.png)

**Comment by Sanster** [comment]
Do you enable `xformers` when run `win_config.bat`? This error maybe caused by you enabled it and `xformers` is not installed

<img width="841" alt="image" src="https://user-images.githubusercontent.com/3998421/219241026-7cc84ced-23e4-4762-b613-72e61889418c.png">

**Comment by Dreamz-Dziner** [comment]
I disabled it but the error is still showing everytime. The Lama GUI opens up after giving the "Ok". Everything works except few of the models especially paint by example. Loading that model always fails. Maybe something messed up the script.

**Comment by Sanster** [comment]
What error do you get when using the Paint by Example model?

**Comment by Dreamz-Dziner** [comment]
> What error do you get when using the Paint by Example model?

The error I was getting was a text in red color " Model Failed to Load". Finally for a last try I deleted the zip folder completely and re extracted everything including the 'models' to a new location. That "Entry point Not Found" error still pops up on start but now all the models are working correctly; especially paint by example:-) Glad it worked. Thank you so much mate.
