### ISSUE TITLE
Add an auto saving option in settings

### ISSUE THREAD

**Issue by Sanster** [Sanster/lama-cleaner#220]
**The plan**

~~Add an `enable auto saving` option in the settings dialog, if enabled, the resulting image will be saved to `--output-dir` using the original image file name without confirmation.~~

update:  If start server with `--output-dir` , auto save result image using the original image file name without confirmation.

**Is't possible to just overwrite the original image?**

No, we can't get the absolute file path of the original image in the browser. One possible workaround is to set `--output-dir` to the original image directory after this feature is implemented.

Related issues
- https://github.com/Sanster/lama-cleaner-docs/issues/8
- https://github.com/Sanster/lama-cleaner/discussions/219

**Comment by starush** [comment]
`we can't get the absolute file path of the original image in the browser`
It just blows my mind. Is it really impossible to get this path at the moment of drag and drop or selecting via file open dialog?

**Comment by Sanster** [comment]
For security reasons browsers do not allow this. https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav

**Comment by Sanster** [comment]
add auto saving in [0.36.0](https://github.com/Sanster/lama-cleaner/releases/tag/0.36.0)
