### ISSUE TITLE
Completely uninstall Lama Cleaner

### ISSUE THREAD

**Issue by meetdilip** [Sanster/lama-cleaner#223]
Hi, I am using Ubuntu 22.04.2 and installed Lama Cleaner using these commands

`pip install lama-cleaner`

`lama-cleaner --model=lama --device=cpu --port=8080`

I am not able to use it properly and I thought of removing the tool. So I used 

`pip uninstall lama-cleaner`

The result was quick and was told that lama cleaner got removed. But there is still around 4GB of space utilised ( as per the previous free space before installing Lama cleaner). Is there any method to remove all files added and reclaim the free space? Thanks.

**Comment by Sanster** [comment]
https://lama-cleaner-docs.vercel.app/frequently_asked_questions#how-to-completely-uninstall-lama-cleaner

**Comment by meetdilip** [comment]
Thanks for the quick response. I have deleted the items under

~/.cache/torch/hub/checkpoints/

which were 2 files close to 300 MB

But for 

~/.cache/huggingface/

there was no diffuser directory and there is only a directory called `hub` with a  text doc called version.txt

A lot more space was consumed during the installation. It would be helpful to know any command to get them removed. Is Flask a part of lama-cleaner? I can see it and it is still there along with a few other, which I am not sure about.

**Comment by Sanster** [comment]
Oh, I forgot about the other pip dependencies, you can check here to uninstall other package(torch should be the main space hog): https://github.com/Sanster/lama-cleaner/blob/main/requirements.txt

**Comment by meetdilip** [comment]
Thanks. If I may, do we have to install them one by one? Or is there any simple method to do it?

**Comment by meetdilip** [comment]
Manually uninstalled them. This one got an error though 


```
pip uninstall markupsafe
Found existing installation: MarkupSafe 2.0.1
Not uninstalling markupsafe at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'MarkupSafe'. No files were found to uninstall.
```
