### ISSUE TITLE
[BUG] '"disable_nsfw": true' in config.json has no effect

### ISSUE THREAD

**Issue by setzke** [Sanster/lama-cleaner#224]
Which model are you using?
sd1.5

Running win_start.bat, the config.json file contrains "disable_nsfw":true, but there is no effect.

**Screenshots**

**System Info**
Software version used
- lama-cleaner: how do I check this
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.6
- torch: 1.12.1+cu113
- Pillow: 9.3.0
- diffusers: 0.12.1
- transformers: 4.25.1
- opencv-python: 4.6.0.66
- xformers: N/A
- accelerate: 0.15.0
- lama-cleaner: 0.36.0

**Comment by Sanster** [comment]
I tried it in my environment and this parameter is valid. 

Do you mean you set `disable_nsfw=true`, but the generated images are still sometimes black?

**Comment by Sanster** [comment]
You are using v1 installer, which will not pass disable_nsfw to lama cleaner start command. You can manually add command line arg in win_start.bat or download v2 installer https://lama-cleaner-docs.vercel.app/install/windows_1click_installer
