### ISSUE TITLE
Switch to sd2 model failed 

### ISSUE THREAD

**Issue by xperternier** [Sanster/lama-cleaner#226]
<img width="230" alt="螢幕擷取畫面_20230223_093605" src="https://user-images.githubusercontent.com/116382039/220922937-f74e5bd0-ce16-4378-9a1e-26fc49298219.png">
How to fix it?
請問如何解決?

**Comment by Sanster** [comment]
如果没有下载过的话前端切换现在有 bug。。请先用 sd2 启动一次，会自动下载
```bash
lama-cleaner --model sd2
```

**Comment by xperternier** [comment]
Even if downloaded he still does not work

**Comment by Sanster** [comment]
The error is caused by you  set `enable_xformers=True`, but not install the xformers package. There are two solutions

- Set `enable_xformers` to False
- or install xformers https://lama-cleaner-docs.vercel.app/frequently_asked_questions#how-to-install-xformers-in-windows-installer-v2

**Comment by xperternier** [comment]
Now a new problem arises
<img width="352" alt="螢幕擷取畫面_20230302_044725" src="https://user-images.githubusercontent.com/116382039/222261482-723bf645-31aa-46f1-837c-8ed7d34d0df0.png">

**Comment by Sanster** [comment]
GPU memory is not enough, check this https://lama-cleaner-docs.vercel.app/memory#stable-diffusion
