### ISSUE TITLE
[feature]I think putting these tools and feature will help the program

### ISSUE THREAD

**Issue by Kingal20000** [Sanster/lama-cleaner#228]
First, make the mask changeable, like erasing the mask, and secondly, draw a straight line like Photoshop with shift, and it is better to add a quality enhancement tool or upscale for models like fcf or mat, to improve the quality of the work without it. Thanks for this amazing program. 
One thing, if it is possible, I think fix the mask size limit is like this for inpainting models, where the mask that is created is divided into several parts and do big masks little by little.  It corrects cuda out memory, I am not a programmer, if possible, check this too ❤️

**Comment by Sanster** [comment]
## Enhancement/upscale tool

Thanks for the suggestion, I'm a little confused about the description of the enhancement/upscale tool. Are you saying that similar to extras post-processing in AUTO1111, you can directly use a model like Real-ESRGAN to upscale the result image?

## Memory saving for MAT model 
For memory optimization the next release will focus on the MAT model, which now has two main problems.

- The precision of the current model is float32, not float16. Open an issue about memory saving for MAT model: https://github.com/fenglinglwb/MAT/issues/71
- MAT only allow input image size like 512x512 / 1024x1024, so if a mask area is 640x640, Lama Cleaner will padding to 1024x1024, increasing the consumption of GPU memory, perhaps we can just resize 640x640 to 512x512 to do model inference, sacrificing some image quality to save GPU memory.
- Divide mask into several parts: It may affect the effect of the model, maybe I can try it. But as mentioned above the MAT model must have a minimum of 512x512 inputs

**Comment by Dreamz-Dziner** [comment]
Awesome update mate. I was struggling with the MAT model and saw an update right now and boom! MAT model is now super charged and no memory error. Thank you so much for the update.

**Comment by Kingal20000** [comment]
By upscale, I mean that for models like fcf or mat, which have a limited size, there should be something that increases the quality of the work, which is only limited to the mask, and there is a problem, the lama model is for black and white photos, more like manga, and for the rest of the photos.  Its color changes very little

**Comment by Sanster** [comment]
- MAT model fp16
- add Real-ESRGAN upscaler
Full release note: https://github.com/Sanster/lama-cleaner/releases/tag/1.0.0

Please upgrade to 1.0.2
