### ISSUE TITLE
Output format matches input format which can cause quality loss.

### ISSUE THREAD

**Issue by ja231c** [Sanster/lama-cleaner#229]
This causes a loss of quality when input format can be lossy, even if the image is lossless (for example, put lossless webp into lama-cleaner, the output will be full of compression artifacts).

Caused by line 298 in server.py, where format of output gets set to format of input, and then later in the pil_to_bytes function in helper.py which uses a fixed quality setting of 95.

Solution: force a specific output format, preferrably configurable, lossless by default.

Also, the mask output format seems to always to be JPEG, I've got no idea where saving of this is done though.

**Comment by Sanster** [comment]
add `--quality` in 1.0.2, default value is 95, you can change to 100
