### ISSUE TITLE
open file failed because of errno 2 on fopen: No such file or directory

### ISSUE THREAD

**Issue by twtytei** [Sanster/lama-cleaner#232]
![error](https://user-images.githubusercontent.com/17823820/222131259-eab23a9c-cd8c-42a1-9df7-d34afff9ae18.jpg)

**Comment by Sanster** [comment]
有点奇怪，如果本地没有文件的话，会自动下载的，你能检查下 C:\Users\xxx\.cache\torch\hub\checkpoints\ 这个目录下面有没有模型文件么？

**Comment by novaexe** [comment]
same issue

**Comment by twtytei** [comment]
有的，big-lama.pt检查过MD5值是对的，也直接在下载放入过该文件夹，也报错

**Comment by Sanster** [comment]
可以试下把 .cache 文件夹换个目录，然后启动时指定 `--model-dir` 参数到该文件夹

**Comment by twtytei** [comment]
意思是把big-lama.pt文件换个路径吗？然后加上dir指定路径？

**Comment by Sanster** [comment]
或者直接启动的时候指定 --model-dir，会自动重新下模型
