### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Tobe2d** [Sanster/lama-cleaner#233]
Updated to the latest release and when I start it got this error:

OSError: fp16 is not a valid git identifier (branch name, tag name or commit id) that exists for this model name. Check
the model page at 'https://huggingface.co/Sanster/anything-4.0-inpainting' for available revisions.
Press any key to continue . . .

**Comment by novaexe** [comment]
same except slightly different

[Errno 2] No such file or directory:
'C:\\Users\\redacted\\Documents\\lama-cleaner\\installer\\Scripts\\lama-cleaner.exe\\__main__.py'

and

OSError: Error no file named diffusion_pytorch_model.bin found in directory
C:\Users\redacted\.cache\huggingface\diffusers\models--Sanster--anything-4.0-inpainting\snapshots\f5cc12c878f2924775be8d577
053251d74daccd5\vae.
Press any key to continue . . .

**Comment by novaexe** [comment]
i get the exact same error when not running in fp32 as tobe

**Comment by Sanster** [comment]
Fixed in `0.37.1`.

1. add `safetensors` to requirements.txt
2. push `fp16` revision to HuggingFace hub

**Comment by novaexe** [comment]
not possible to do if you used the installer?

**Comment by Sanster** [comment]
> not possible to do if you used the installer?

Rerun `win_config.bat` to update to newest version. The above operation is only my own modification record, users can ignore.

**Comment by novaexe** [comment]
can confirm that fixed it tyvm :)
