### ISSUE TITLE
Offline working version without addons installations

### ISSUE THREAD

**Issue by fewtubefx** [Sanster/lama-cleaner#237]
I've tried to install it on win7 and win10 with "easy installer", but no luck, many errors while installing.

It will be great to download working version with switching between cpu and gpu option, with all additions needed for python, and python included. Even if it will not update.

**Comment by fewtubefx** [comment]
[lama configlog.txt](https://github.com/Sanster/lama-cleaner/files/10928568/lama.configlog.txt)
[lama start log.txt](https://github.com/Sanster/lama-cleaner/files/10928569/lama.start.log.txt)

**Comment by Sanster** [comment]
Sorry, this is an error from a dependency library and I don't know how to fix it. If you purchased the 1-click Installer with money, feel free to request a refund.

**Comment by fewtubefx** [comment]
Issue was not about error from a dependency library. But about offline version.
