### ISSUE TITLE
Switch to mange model failed[BUG]

### ISSUE THREAD

**Issue by xiaomayidechuanshuo** [Sanster/lama-cleaner#239]
![image](https://user-images.githubusercontent.com/46549217/223972099-01fc853b-8c85-405b-908f-e1cf25d086eb.png)

**Comment by xiaomayidechuanshuo** [comment]
![image](https://user-images.githubusercontent.com/46549217/223985116-eec1160c-d71a-45f8-9288-15aaa914120a.png)

**Comment by Sanster** [comment]
fixed in 1.0.2
