### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qiyao887** [Sanster/lama-cleaner#240]
**Model**
Which model are you using?

**Describe the bug**

**Screenshots**
If applicable, add screen
![photo_2023-03-10_01-40-03](https://user-images.githubusercontent.com/127336431/224110832-28d38cd2-f803-4985-b780-ae7f4e01f06a.jpg)
shots to help explain your problem.

**System Info**
Software version used
- lama-cleaner: 
- pytorch: 
- CUDA:

**Comment by Sanster** [comment]
hi, the error means there is not enough GPU memory to finish the inpainting,  please refer to this page to see how to reduce the GPU memory usage https://lama-cleaner-docs.vercel.app/memory
