### ISSUE TITLE
[Feature Request] Filemanager: Sort by Modification date, Inpaint: Rectangle tool as alternative to brush tool

### ISSUE THREAD

**Issue by neojam** [Sanster/lama-cleaner#241]
Hallo,

I would like to ask for 2 additional features:

**1.**
-----------
Additional sorting option in the file manager: "Sort by modification date".

I have  my input and output dirs set to the same location:
"input": "D:\\limaWIP",
"output_dir": "D:\\limaWIP"
so I'm overwriting the images after cleaning. With the reversed sorting order by modification date, the unedited images would appear on top of the list when you open the File manager, which would help with the workflow.

1a
Also please make the sorting order and the asc/desc direction sticky. Currently it seems to reset to "Created Time" after you reopen the file manager.

1b
It would also be nice, if all thumbnails  in file manager would not overlap rows. Currently the portrait thumbs are larger than landscape ones and because of it they overlap multiple rows. It looks nice from aesthetic point of view, but hinders productivity, where you clean the images row after row.

1c
Is it possible to make right arrow/left arrow to go to next/prev image in the input directory? 
This would help with the workflow as well. Hotkey for saving image would be nice to.

**2.**
-----------
Additional inpainting tool: "Rectangle selection".
User has to click and hold left mouse button and then draw a selection rectangle over area to be inpainted.
The release of the left mouse button should trigger the inpainting.
Since most logos/watermarks are rectangular, this would make the process of inpainting faster and easier with no need to increase/decrease the brush size.

thank you :)

**Comment by Sanster** [comment]
- Add row layout
- save FileManager states in localstore
- add sort by modified time

Please updated to 1.0.2

https://user-images.githubusercontent.com/3998421/229341246-79859741-3edd-4d11-93aa-f9b8671b5d8b.mp4

Other feature requests maybe next time...

**Comment by neojam** [comment]
Thank you, this really helps with the workflow :)

Hope to see the requests 1c + 2 to make it in the app sometime too. ;)
