### ISSUE TITLE
Switch to sd1.5 model failed

### ISSUE THREAD

**Issue by vasyaholly** [Sanster/lama-cleaner#242]
I have this problem when choosing any Stable-Diffusion model. How to fix it?

![111](https://user-images.githubusercontent.com/6813610/224755531-65cce64d-7943-492c-8702-13847ca9fe9e.jpg)
![112](https://user-images.githubusercontent.com/6813610/224755521-4159bc12-e97a-472e-bfee-5885a9b661cd.jpg)

**Comment by Sanster** [comment]
Hi, please start the server with `--model sd1.5` first, the switch will work after the model had been downloaded

**Comment by vasyaholly** [comment]
> Привет, пожалуйста, запустите сервер с `--model sd1.5`во-первых, переключатель будет работать после загрузки модели
In which folder should I put the "sd1.5.ckpt" file?

**Comment by Sanster** [comment]
By default it's downloaded to `C:\Users\your_name\.cache\huggingface\diffusers`, you can use `--model-dir` command line argument to set a new location

**Comment by vasyaholly** [comment]
I put the model in the path you provided. I wrote "--model sd1.5", but it gives this.
![113](https://user-images.githubusercontent.com/6813610/224937613-a2788d4e-e646-4081-8016-b4dac751604f.jpg)

**Comment by Sanster** [comment]
Maybe it's caused by some configurations in the config.json file, please take a screenshot of the config.json file.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/3998421/224942578-1393d6ba-3bba-4efb-bf7e-7af96e7fad88.png">

**Comment by vasyaholly** [comment]
![114](https://user-images.githubusercontent.com/6813610/224945981-19eec873-0d8f-4aa1-b865-8dc910f22b0e.jpg)

**Comment by Sanster** [comment]
Can you try delete `models` dir, and run `win_start.bat` again?

**Comment by vasyaholly** [comment]
Almost everything is the same, only at the very beginning the program downloads something
![115](https://user-images.githubusercontent.com/6813610/224956593-f9f2fc04-09cc-4ef3-a2f4-5bd94df77691.jpg)

**Comment by Sanster** [comment]
Found the bug source: https://github.com/huggingface/diffusers/issues/2614

Solution: set an absolute path for `model_dir` (e.g. /path/to/your/folder)

**Comment by vasyaholly** [comment]
Unfortunately it didn't help. I already wrote a bunch of things in config.json, and if I change the path in "model_dir", then I get this.
![116](https://user-images.githubusercontent.com/6813610/225035672-2e4bb452-2038-4ed0-b1a5-df780d0f0480.jpg)
![117](https://user-images.githubusercontent.com/6813610/225035700-b8984130-9bda-4a12-b759-143f36edc1ef.jpg)

**Comment by Sanster** [comment]
change all `\` in model_dir to `\\` 

https://stackoverflow.com/questions/57165074/json-parse-windows-file-path

**Comment by vasyaholly** [comment]
Thank you very much, everything worked!!!
