### ISSUE TITLE
Remove background  ̶a̶n̶d̶ ̶r̶i̶g̶h̶t̶ ̶c̶l̶i̶c̶ ̶c̶o̶p̶y̶ ̶t̶o̶ ̶c̶l̶i̶p̶b̶o̶a̶r̶d̶  [Feature Request]  ̶x̶2̶

### ISSUE THREAD

**Issue by cibernicola** [Sanster/lama-cleaner#243]
The option to remove the background would be for unifying tasks, there are several tools available, but I think the inclusion of some of them would be great.
On the other hand allowing right click to copy image would be highly useful to speed up detail work when switching between applications.

**Comment by Sanster** [comment]
Hi, you can use `ctrl+c` to copy the result. BTW: you can also use `ctrl+v` to paste the image to the Lama Cleaner

**Comment by Sanster** [comment]
Hi, you can use `ctrl+c` to copy the result. BTW: you can also use `ctrl+v` to paste the image to the Lama Cleaner

**Comment by cibernicola** [comment]
Oh, I knew about ctr + v, but I never tried ctr + c.

**Comment by Sanster** [comment]
rembg added in 1.0.2: https://github.com/Sanster/lama-cleaner/releases/tag/1.0.0
