### ISSUE TITLE
[BUG] Error: Failed to import transformers.models.clip.feature_extraction_clip | No module named 'absl'

### ISSUE THREAD

**Issue by xk44** [Sanster/lama-cleaner#246]
**Model**
Which model are you using?
Lama, or none, because the program doesn't finish loading.
**Describe the bug**
1. Attempt pip install, get error: `RuntimeError: Failed to import transformers.models.clip.feature_extraction_clip because of the following error (look up to see its traceback): module 'tensorflow.compat.v2.__internal__' has no attribute 'register_load_context_function'`
2. Bought Windows Installer.
3. Followed instructions *exactly* as shown at https://lama-cleaner-docs.vercel.app/install/windows_1click_installer
4. Open win_config.bat
5. Select Model Lama, default IP and Port, using device cuda. enabled `Launch Lama Cleaner as desktop app` and `Disable NSFW checker. (sd/paint_by_example)`.
6. Save config.
7. Run win_start.bat
8. Get error shown below
9. Uninstalled and reinstalled torch, transformers, absl-py, and tensorflow-gpu, verified dependencies installed are the correct versions.
10. Run win_start.bat
11. Get same error shown below.

**System Info**
Software version used
- lama-cleaner: 0.37.1
- pytorch: 1.12.1 (I installed 1.13.1 as pip instructions show, not sure why this is different but I've reinstalled and it shows same version still.)
- CUDA: cu113
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.6
- Pillow: 9.4.0
- diffusers: 0.12.1
- transformers: 4.27.1
- opencv-python: 4.7.0.72
- xformers: N/A (Installed xformers with pip but xformers is not used even when the setting is enabled in config gradio ui)
- accelerate: 0.17.1

Error:
`2023-03-17 18:53:16.928 | INFO     | lama_cleaner.parse_args:parse_args:122 - Loading installer config from C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\win_start.bat\..\installer_config.json
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\transformer │
│ s\utils\import_utils.py:1126 in _get_module                                                      │
│                                                                                                  │
│   1123 │                                                                                         │
│   1124 │   def _get_module(self, module_name: str):                                              │
│   1125 │   │   try:                                                                              │
│ > 1126 │   │   │   return importlib.import_module("." + module_name, self.__name__)              │
│   1127 │   │   except Exception as e:                                                            │
│   1128 │   │   │   raise RuntimeError(                                                           │
│   1129 │   │   │   │   f"Failed to import {self.__name__}.{module_name} because of the followin  │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\importlib\__init__.py:126 │
│ in import_module                                                                                 │
│                                                                                                  │
│   123 │   │   │   if character != '.':                                                           │
│   124 │   │   │   │   break                                                                      │
│   125 │   │   │   level += 1                                                                     │
│ > 126 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   127                                                                                            │
│   128                                                                                            │
│   129 _RELOADING = {}                                                                            │
│ <frozen importlib._bootstrap>:1050 in _gcd_import                                                │
│ <frozen importlib._bootstrap>:1027 in _find_and_load                                             │
│ <frozen importlib._bootstrap>:1006 in _find_and_load_unlocked                                    │
│ <frozen importlib._bootstrap>:688 in _load_unlocked                                              │
│ <frozen importlib._bootstrap_external>:883 in exec_module                                        │
│ <frozen importlib._bootstrap>:241 in _call_with_frames_removed                                   │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\transformer │
│ s\models\clip\feature_extraction_clip.py:20 in <module>                                          │
│                                                                                                  │
│   17 import warnings                                                                             │
│   18                                                                                             │
│   19 from ...utils import logging                                                                │
│ > 20 from .image_processing_clip import CLIPImageProcessor                                       │
│   21                                                                                             │
│   22                                                                                             │
│   23 logger = logging.get_logger(__name__)                                                       │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\transformer │
│ s\models\clip\image_processing_clip.py:22 in <module>                                            │
│                                                                                                  │
│    19 import numpy as np                                                                         │
│    20                                                                                            │
│    21 from ...image_processing_utils import BaseImageProcessor, BatchFeature, get_size_dict      │
│ >  22 from ...image_transforms import (                                                          │
│    23 │   center_crop,                                                                           │
│    24 │   convert_to_rgb,                                                                        │
│    25 │   get_resize_output_image_size,                                                          │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\transformer │
│ s\image_transforms.py:48 in <module>                                                             │
│                                                                                                  │
│    45 │   import torch                                                                           │
│    46                                                                                            │
│    47 if is_tf_available():                                                                      │
│ >  48 │   import tensorflow as tf                                                                │
│    49                                                                                            │
│    50 if is_flax_available():                                                                    │
│    51 │   import jax.numpy as jnp                                                                │
│                                                                                                  │
│ C:\Users\xk44\AppData\Roaming\Python\Python310\site-packages\tensorflow\__init__.py:37 in        │
│ <module>                                                                                         │
│                                                                                                  │
│    34 import sys as _sys                                                                         │
│    35 import typing as _typing                                                                   │
│    36                                                                                            │
│ >  37 from tensorflow.python.tools import module_util as _module_util                            │
│    38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader                   │
│    39                                                                                            │
│    40 # Make sure code inside the TensorFlow codebase can use tf2.enabled() at import.           │
│                                                                                                  │
│ C:\Users\xk44\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\__init__.py:37 in │
│ <module>                                                                                         │
│                                                                                                  │
│    34 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top                   │
│    35                                                                                            │
│    36 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow                      │
│ >  37 from tensorflow.python.eager import context                                                │
│    38                                                                                            │
│    39 # pylint: enable=wildcard-import                                                           │
│    40                                                                                            │
│                                                                                                  │
│ C:\Users\xk44\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\eager\context.py: │
│ 25 in <module>                                                                                   │
│                                                                                                  │
│     22 import random                                                                             │
│     23 import threading                                                                          │
│     24                                                                                           │
│ >   25 from absl import logging                                                                  │
│     26 import numpy as np                                                                        │
│     27 import six                                                                                │
│     28                                                                                           │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'absl'

The above exception was the direct cause of the following exception:

┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\runpy.py:196 in           │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ > 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\runpy.py:86 in _run_code  │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ >  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\Scripts\lama-cleaner.exe\__ma │
│ in__.py:7 in <module>                                                                            │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'C:\\Users\\xk44\\Downloads\\lama-cleaner-win-v2\\lama-clea │
│ ner\\installer\\Scripts\\lama-cleaner.exe\\__main__.py'                                          │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\lama_cleane │
│ r\__init__.py:10 in entry_point                                                                  │
│                                                                                                  │
│    7 │   args = parse_args()                                                                     │
│    8 │   # To make os.environ["XDG_CACHE_HOME"] = args.model_cache_dir works for diffusers       │
│    9 │   # https://github.com/huggingface/diffusers/blob/be99201a567c1ccd841dc16fb24e88f7f239    │
│ > 10 │   from lama_cleaner.server import main                                                    │
│   11 │   main(args)                                                                              │
│   12                                                                                             │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\lama_cleane │
│ r\server.py:23 in <module>                                                                       │
│                                                                                                  │
│    20                                                                                            │
│    21 from lama_cleaner.interactive_seg import InteractiveSeg, Click                             │
│    22 from lama_cleaner.make_gif import make_compare_gif                                         │
│ >  23 from lama_cleaner.model_manager import ModelManager                                        │
│    24 from lama_cleaner.schema import Config                                                     │
│    25 from lama_cleaner.file_manager import FileManager                                          │
│    26                                                                                            │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\lama_cleane │
│ r\model_manager.py:10 in <module>                                                                │
│                                                                                                  │
│    7 from lama_cleaner.model.ldm import LDM                                                      │
│    8 from lama_cleaner.model.manga import Manga                                                  │
│    9 from lama_cleaner.model.mat import MAT                                                      │
│ > 10 from lama_cleaner.model.paint_by_example import PaintByExample                              │
│   11 from lama_cleaner.model.instruct_pix2pix import InstructPix2Pix                             │
│   12 from lama_cleaner.model.sd import SD15, SD2, Anything4, RealisticVision14                   │
│   13 from lama_cleaner.model.zits import ZITS                                                    │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\lama_cleane │
│ r\model\paint_by_example.py:5 in <module>                                                        │
│                                                                                                  │
│    2 import PIL.Image                                                                            │
│    3 import cv2                                                                                  │
│    4 import torch                                                                                │
│ >  5 from diffusers import DiffusionPipeline                                                     │
│    6 from loguru import logger                                                                   │
│    7                                                                                             │
│    8 from lama_cleaner.model.base import DiffusionInpaintModel                                   │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\diffusers\_ │
│ _init__.py:54 in <module>                                                                        │
│                                                                                                  │
│    51 │   │   get_polynomial_decay_schedule_with_warmup,                                         │
│    52 │   │   get_scheduler,                                                                     │
│    53 │   )                                                                                      │
│ >  54 │   from .pipelines import (                                                               │
│    55 │   │   AudioPipelineOutput,                                                               │
│    56 │   │   DanceDiffusionPipeline,                                                            │
│    57 │   │   DDIMPipeline,                                                                      │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\diffusers\p │
│ ipelines\__init__.py:44 in <module>                                                              │
│                                                                                                  │
│    41 except OptionalDependencyNotAvailable:                                                     │
│    42 │   from ..utils.dummy_torch_and_transformers_objects import *  # noqa F403                │
│    43 else:                                                                                      │
│ >  44 │   from .alt_diffusion import AltDiffusionImg2ImgPipeline, AltDiffusionPipeline           │
│    45 │   from .latent_diffusion import LDMTextToImagePipeline                                   │
│    46 │   from .paint_by_example import PaintByExamplePipeline                                   │
│    47 │   from .stable_diffusion import (                                                        │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\diffusers\p │
│ ipelines\alt_diffusion\__init__.py:33 in <module>                                                │
│                                                                                                  │
│   30                                                                                             │
│   31 if is_transformers_available() and is_torch_available():                                    │
│   32 │   from .modeling_roberta_series import RobertaSeriesModelWithTransformation               │
│ > 33 │   from .pipeline_alt_diffusion import AltDiffusionPipeline                                │
│   34 │   from .pipeline_alt_diffusion_img2img import AltDiffusionImg2ImgPipeline                 │
│   35                                                                                             │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\diffusers\p │
│ ipelines\alt_diffusion\pipeline_alt_diffusion.py:22 in <module>                                  │
│                                                                                                  │
│    19                                                                                            │
│    20 from diffusers.utils import is_accelerate_available                                        │
│    21 from packaging import version                                                              │
│ >  22 from transformers import CLIPFeatureExtractor, XLMRobertaTokenizer                         │
│    23                                                                                            │
│    24 from ...configuration_utils import FrozenDict                                              │
│    25 from ...models import AutoencoderKL, UNet2DConditionModel                                  │
│ <frozen importlib._bootstrap>:1075 in _handle_fromlist                                           │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\transformer │
│ s\utils\import_utils.py:1117 in __getattr__                                                      │
│                                                                                                  │
│   1114 │   │   │   value = self._get_module(name)                                                │
│   1115 │   │   elif name in self._class_to_module.keys():                                        │
│   1116 │   │   │   module = self._get_module(self._class_to_module[name])                        │
│ > 1117 │   │   │   value = getattr(module, name)                                                 │
│   1118 │   │   else:                                                                             │
│   1119 │   │   │   raise AttributeError(f"module {self.__name__} has no attribute {name}")       │
│   1120                                                                                           │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\transformer │
│ s\utils\import_utils.py:1116 in __getattr__                                                      │
│                                                                                                  │
│   1113 │   │   if name in self._modules:                                                         │
│   1114 │   │   │   value = self._get_module(name)                                                │
│   1115 │   │   elif name in self._class_to_module.keys():                                        │
│ > 1116 │   │   │   module = self._get_module(self._class_to_module[name])                        │
│   1117 │   │   │   value = getattr(module, name)                                                 │
│   1118 │   │   else:                                                                             │
│   1119 │   │   │   raise AttributeError(f"module {self.__name__} has no attribute {name}")       │
│                                                                                                  │
│ C:\Users\xk44\Downloads\lama-cleaner-win-v2\lama-cleaner\installer\lib\site-packages\transformer │
│ s\utils\import_utils.py:1128 in _get_module                                                      │
│                                                                                                  │
│   1125 │   │   try:                                                                              │
│   1126 │   │   │   return importlib.import_module("." + module_name, self.__name__)              │
│   1127 │   │   except Exception as e:                                                            │
│ > 1128 │   │   │   raise RuntimeError(                                                           │
│   1129 │   │   │   │   f"Failed to import {self.__name__}.{module_name} because of the followin  │
│   1130 │   │   │   │   f" traceback):\n{e}"                                                      │
│   1131 │   │   │   ) from e                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Failed to import transformers.models.clip.feature_extraction_clip because of the following error (look up
to see its traceback):
No module named 'absl'`

**Comment by Sanster** [comment]
Lama Cleaner not dependent on TensorFlow, can you try uninstall `tensorflow-gpu` and ` tensorflow`?
