### ISSUE TITLE
[BUG] Failed to load model big-lama.pt

### ISSUE THREAD

**Issue by happyuli** [Sanster/lama-cleaner#248]
**Model**
Which model are you using?
Lama

**Describe the bug**
I download a Windows 1-Click Installer.
Do it step by step.
Then it shows on the Screen :
    Failed to load model C:\Users\...\.cache\torch\hub\checkpoints\big-lama.pt
PLS tell me how to solve it. 
Many THX.

**Screenshots**
![Lama Bug](https://user-images.githubusercontent.com/128284237/226162695-1d971a6c-e367-4805-9994-0b97ec0ff420.JPG)

**System Info**
Software version used
- lama-cleaner: 
- pytorch: 
- CUDA:

**Comment by Sanster** [comment]
Unfortunately, there is still no solution to this error because I can't reproduce it on my computer. If you could help me try the following two solutions, I would be very grateful.

### Possible Solution 1
Change model download directory to another disk that is not the system disk. For example `D:\\lama-cleaner-models`

### Possible Solution 2

Modify `win_confg.bat` file, remove two lines: 
```bash
@call conda install -y cudatoolkit=11.3
@call pip install torch==1.12.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
```

Add three lines at the original position.
```bash
@call conda install -y -c conda-forge cudatoolkit=11.7
@call pip install torch==1.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
@call pip install xformers
```

**Comment by happyuli** [comment]
THX a lot ! 
Your solution really works. (I tried both.)

AND 
There is still a problem left—— after I “cleaned” the picture，and press the button "Save Imgae" in the bottom right of the menu bar, Nothing happens. 
I mean I cannot save the picture.  OR I don't konw where is the picture saved. 
Would you please give me one more solution about the problem?  
Thank you.

**Comment by Sanster** [comment]
With the default settings, a dialog box will pop up for you to choose where to save  the result image.

If you start the server with `--input` and `--output-dir`, the images are automatically saved to the `--output-dir` directory.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/3998421/227210403-c415bbc2-6d4d-4b84-9149-706b4bedc79c.png">

If you haven't set `--input` and `--output-dir`, but don't see the save dialog, I suggest you change the web browser
