### ISSUE TITLE
[BUG] can't run most of the time

### ISSUE THREAD

**Issue by bveleven** [Sanster/lama-cleaner#251]
**Model**
sd 1.5

I have 2 issues:
1. I use the Window 1-click installer but it doesn't work most of the time (pls check pic 1)
2. It works sometimes, but when I use the brush to mask an object, it doesn't automatically remove the object like it does in the videos (but I can still use the dream feature to replace that object) (pic 2)

I'm new to this, so please give specific instructions if possible, thank you very much!

**System Info**
pytorch:1.13.1+cu117

![1](https://user-images.githubusercontent.com/129085062/227984230-2f4b7b5d-0cc1-4d45-a2d2-3a6e2267e5df.png)
![2](https://user-images.githubusercontent.com/129085062/227987913-0d2a2d55-86a1-4f11-b16a-86955c94a3d6.png)

**Comment by Sanster** [comment]
Issue 1:

You can enable this command

<img width="432" alt="image" src="https://user-images.githubusercontent.com/3998421/228091130-dc152f64-fb4a-4644-9d3d-4dc0d697676c.png">

Issue 2:

The following models can be used to erase objects: https://lama-cleaner-docs.vercel.app/models#erase I suggest you try lama first.
