### ISSUE TITLE
[BUG] incorrect tile size for upscale & face upscale settings 

### ISSUE THREAD

**Issue by novaexe** [Sanster/lama-cleaner#261]
tile size for real-esrgan should be set at 512 not 640, and face upscale at 1 instead of 2

**Comment by novaexe** [comment]
would also be fantastic to be able to chose fp32 instead of half for cards that get black images when useing the main real-esrgan upscale 
![image](https://user-images.githubusercontent.com/69226867/229367685-0802ab20-634d-40e3-b234-e8e20625c7ad.png)

**Comment by novaexe** [comment]
the reason for face upscale 1 instead of 2 is because it is doing the entire image not just the face

**Comment by Sanster** [comment]
> tile size for real-esrgan should be set at 512 not 640, and face upscale at 1 instead of 2

Hi, as I understand it, setting the tile size to 512 will reduce the vRAM requirements, and the effect will not be too different, right? If that were the case I would change it to 512

**Comment by Sanster** [comment]
> would also be fantastic to chose fp32 instead of half for cards that get black images when useing the main real-esrgan upscale ![image](https://user-images.githubusercontent.com/69226867/229367685-0802ab20-634d-40e3-b234-e8e20625c7ad.png)

I didn't know that real-esrgan would also have problems with fp16 outputting black images, I'll add a startup option

**Comment by Sanster** [comment]
fixed in `1.0.3`, add `--realesrgan-no-half` option

**Comment by novaexe** [comment]
the main reason you use 512 is because that is the tile sizes specified by gfp and codeformer, having missmatched tile size can cause problems and reduce performance
