### ISSUE TITLE
[BUG] I can't run win_start，and successfully solve the problem。汉语环境的朋友们可以参考下。

### ISSUE THREAD

**Issue by lovelimon** [Sanster/lama-cleaner#266]
The following error occurred while running 'win_start': torch.cuda.is_available() is False, please use --device cpu or check your pytorch installation. 这个应该是因为AMD显卡的缘故，或者是驱动问题，没有深究。后来换成cpu模式，又出现新的问题。后排查是c盘路径不能为中文，也就是C:\Users后面的文件夹需要是英文或者拼音，不能是汉字，修改方法是，在http://127.0.0.1:7860/里把Model download directory修改成纯英文路径，保存并重新运行win_start会自动下载模型文件，随后就能成功运行。
THANKS.

**Comment by tanwongo** [comment]
> The following error occurred while running 'win_start': torch.cuda.is_available() is False, please use --device cpu or check your pytorch installation. 这个应该是因为AMD显卡的缘故，或者是驱动问题，没有深究。后来换成cpu模式，又出现新的问题。后排查是c盘路径不能为中文，也就是C:\Users后面的文件夹需要是英文或者拼音，不能是汉字，修改方法是，在[http://127.0.0.1:7860/里把Model](http://127.0.0.1:7860/%E9%87%8C%E6%8A%8AModel) download directory修改成纯英文路径，保存并重新运行win_start会自动下载模型文件，随后就能成功运行。 THANKS.

新加的seg anything 怎么用 老哥

**Comment by Sanster** [comment]
> > The following error occurred while running 'win_start': torch.cuda.is_available() is False, please use --device cpu or check your pytorch installation. 这个应该是因为AMD显卡的缘故，或者是驱动问题，没有深究。后来换成cpu模式，又出现新的问题。后排查是c盘路径不能为中文，也就是C:\Users后面的文件夹需要是英文或者拼音，不能是汉字，修改方法是，在[http://127.0.0.1:7860/里把Model](http://127.0.0.1:7860/%E9%87%8C%E6%8A%8AModel) download directory修改成纯英文路径，保存并重新运行win_start会自动下载模型文件，随后就能成功运行。 THANKS.
> 
> 新加的seg anything 怎么用 老哥

https://github.com/Sanster/lama-cleaner/releases/tag/1.1.1
