### ISSUE TITLE
M1 Pro Mac Bug when running

### ISSUE THREAD

**Issue by raywgs** [Sanster/lama-cleaner#268]
lama-cleaner --model=lama --device=cuda --port=8080
Tried this command but it returned zsh: illegal hardware instruction. I'm running it on M1 Pro Mac.
Any ideas how to fix this?

**Comment by Sanster** [comment]
lama-cleaner --model=lama --device=mps --port=8080

**Comment by raywgs** [comment]
still got the same error though

**Comment by Sanster** [comment]
What version of pytorch do you have? This is my local environment on M2 Pro and it is working.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/3998421/231037016-581d5816-cd76-46ab-8109-a5aa19d4f87e.png">

**Comment by raywgs** [comment]
<img width="332" alt="CleanShot 2023-04-11 at 17 21 24@2x" src="https://user-images.githubusercontent.com/128401657/231316019-ddda112e-7b26-44d6-b684-a499f6353dd9.png">

**Comment by raywgs** [comment]
doesn't work still

**Comment by Sanster** [comment]
> <img alt="CleanShot 2023-04-11 at 17 21 24@2x" width="332" src="https://user-images.githubusercontent.com/128401657/231316019-ddda112e-7b26-44d6-b684-a499f6353dd9.png">

I see that your Platform here is `x86_64-i386`, not arm64. Did you use x86 version of python(via Rosetta)? 
Can you try run with `--device=cpu`?

**Comment by emmajane1313** [comment]
when i try with the rosetta shell i still and --device=cpu  i still get the
error and same with raw arm64, it's strange because it was working up until
a week or so ago

**Comment by Sanster** [comment]
Strangely enough, all the `zsh: illegal hardware instruction` related content I can find is about tensorflow. e.g https://stackoverflow.com/questions/65946627/zsh-illegal-hardware-instruction-python-when-tensorflow-on-macbook-pro-m1

Can you guys try uninstall tensorflow from your environment?

One possible reason I can think of is that [transformers](https://github.com/huggingface/transformers) is a project that supports multiple frameworks(pytorch, tensorflow, jax...), and this issue may be related to it

**Comment by emmajane1313** [comment]
that worked! thanks :)
