### ISSUE TITLE
[ERROR] I have problem when launching Windows 1-Click Lama Cleaner (win_start.bat)

### ISSUE THREAD

**Issue by RadityaArts** [Sanster/lama-cleaner#269]
![image](https://user-images.githubusercontent.com/99865422/230858161-c21ad24b-d0ac-42a9-887b-6d38c2eeedd0.png)
![image](https://user-images.githubusercontent.com/99865422/230857409-87383a80-580a-4382-b197-6ee2e69f8007.png)

I installed Lama Cleaner using Windows 1-Click Installer, then this problem appears with the words "An attempt was made to access a socket in a way forbidden by its access permissions. Press any key to continue.".
When I press any key, nothing appears on my screen.

I have followed all the instructions given.

If needed, this is the config I use.
![image](https://user-images.githubusercontent.com/99865422/230857899-ce9efa3d-7431-40c9-9a26-5f3cc5f460dd.png)

**Comment by Sanster** [comment]
It seems that the port is occupied, can you try to modify the port? for example, to 4242

**Comment by RadityaArts** [comment]
> It seems that the port is occupied, can you try to modify the port? for example, to 4242

Thank you very much. I can now use it properly and no more errors.
