### ISSUE TITLE
ERROR: No matching distribution found for imghdr

### ISSUE THREAD

**Issue by photkey** [Sanster/lama-cleaner#27]
`pip3 install -r requirements.txt` found imghdr error when installing
Then install imghdr separately: `pip install imghdr`
![image](https://user-images.githubusercontent.com/60434581/160687894-c0005f26-639c-4f7b-baae-a30e698df717.png)
Python 3.9.12
Windows 11

It can still run normally now, I don't know what effect this will have and under what circumstances it will go wrong.

**Comment by blessedcoolant** [comment]
imghdr ships inbuilt with Python. That's why I did not add in the requirements.txt .. Trying to install it is causing the issue. I am not sure why @Sanster added it to the requirements file. I'll let him have a look at this and revert that change.

**Comment by Sanster** [comment]
Fixed.

I haven't used it before and thought it was a separate library

**Comment by blessedcoolant** [comment]
> 

No worries. I didn't realize it was an inbuilt module until I saw through the docs myself.
