### ISSUE TITLE
SD 1.5 super slow on Mac Book M1 Pro 16 GB RAM

### ISSUE THREAD

**Issue by demirklvc** [Sanster/lama-cleaner#270]
Hello! The Lama model works fast but when using SD 1.5 its super slow. how can i improve speed or what can i change in settings to get it faster running? best wishes

**Comment by Sanster** [comment]
Set --device=mps run fastest on m1/m2 chip, on my m2 pro 1.5~2 it/s

**Comment by tcouet** [comment]
![Capture d’écran 2024-04-04 à 18 29 21](https://github.com/Sanster/IOPaint/assets/10501325/b381495e-c41c-424b-8f1d-efef29be1c72)

My M1 pro like 8000/9000ms, why ? :'(
