### ISSUE TITLE
--input --output-dir cannot use a path containing Chinese characters, otherwise it cannot be saved successfully.

### ISSUE THREAD

**Issue by liulintc** [Sanster/lama-cleaner#275]
--input --output-dir cannot use a path containing Chinese characters, otherwise it cannot be saved successfully.
--input --output-dir The file name of the image is in Chinese, and it cannot be saved successfully. Click on download and it will prompt that the save was successful, but it is not included in the saved path. If you change it to an English path and image name, there will be no problem. May I ask why?

**Comment by Sanster** [comment]
Same as https://github.com/Sanster/lama-cleaner/issues/265
