### ISSUE TITLE
[Feature Request] - Implementing "Segment Anything"?

### ISSUE THREAD

**Issue by CCpt5** [Sanster/lama-cleaner#279]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Curious if an implementation of the newly released "Segment Anything" into lama is potentially coming down the road.

**Additional context**
Stumbled on a new repo that utilizes Segment Anything in a way that seems as though it'd be perfect as an additional feature for Lama-cleaner: https://github.com/Uminosachi/inpaint-anything  
  
There's also a "Segment Anything" extension for A1111 now here: https://github.com/continue-revolution/sd-webui-segment-anything  

Thanks for considering!

**Comment by Sanster** [comment]
This feature was actually added to Lama Cleaner the day after the Segment Anything release, check this：https://github.com/Sanster/lama-cleaner/releases/tag/1.1.1

**Comment by Sanster** [comment]
From the first part of your log, it seems that torch and torchvision have been installed successfully. However, when you were starting it up, you passed the wrong parameter name `--mode=lama`. It should be `--model=lama`.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/3998421/232260731-e54a68cc-bf4c-4d2d-9819-e9ef27d0035d.png">
<img width="837" alt="image" src="https://user-images.githubusercontent.com/3998421/232260734-1f995f1c-586b-4c7c-84c9-0c3f6640e210.png">

In the second part of your log, the version of torch is `1.12.1+cu113`, which is different from the torch version(1.13.1+cu117) in the first part. Is it another environment?
<img width="565" alt="image" src="https://user-images.githubusercontent.com/3998421/232260772-c816e238-1e1f-4265-acdd-69f71fb729b8.png">
