### ISSUE TITLE
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.[BUG]

### ISSUE THREAD

**Issue by AlexYez** [Sanster/lama-cleaner#280]
Hi!
I got this message when using one click installer
"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible."
Lama in working but I am curious, does this error affect the work or can it be ignored?

**Comment by Sanster** [comment]
This error can be ignored.

Note to myself: It may be because the version of Flask used by lama-cleaner is too old, there is a conflict with the click dependency of `rembg`, which will need to be resolved in a future release
