### ISSUE TITLE
Could not build wheels for scikit-image [BUG]

### ISSUE THREAD

**Issue by RomixERR** [Sanster/lama-cleaner#281]
**Describe the bug**

While running
**@call pip install lama-cleaner**
 or
**@call pip3 install -U lama-cleaner**
the same error occurs.
```
      [WinError 2] Не удается найти указанный файл


      error: Command "clang-cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -IC:\Users\RomixERR\AppData\Local\Temp\pip-build-env-cyn61bc7\overlay\Lib\site-packages/pythran -IC:\Users\RomixERR\AppData\Local\Temp\pip-build-env-cyn61bc7\overlay\Lib\site-packages\numpy\core\include -IC:\Users\RomixERR\AppData\Local\Temp\pip-build-env-cyn61bc7\overlay\Lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.11\numpy\distutils\include -IR:\lama-cleaner\lama-cleaner\installer\include -IR:\lama-cleaner\lama-cleaner\installer\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /EHsc /Tpskimage/feature/brief_pythran.cpp /Fobuild\temp.win-amd64-3.11\Release\skimage/feature/brief_pythran.obj /std:c++14 /w /openmp /Zm1000" failed with exit status 127
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : msvc

      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : none
        Extra checks: none

      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\RomixERR\AppData\Local\Temp\pip-install-b_wkqtmk\scikit-image_8286fe31a88f43bc87431f2809a25077\build\temp.win-amd64-3.11\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-image
Failed to build scikit-image
ERROR: Could not build wheels for scikit-image, which is required to install pyproject.toml-based projects
```

**System Info**
Windows 10.
Software version used
- lama-cleaner: [6750df1](https://github.com/Sanster/lama-cleaner/commit/6750df13e71cf74ace96b481fc319cb48f01637e)
- pytorch: 
torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url 
or 
torch==1.13.1+cu117 torchvision==0.14.1 --extra-index-url

**Comment by Sanster** [comment]
Only the zits model needs scikit-image, and I think we can remove it from the dependency and use opencv to implement the corresponding operation.

added in:  https://github.com/Sanster/lama-cleaner/commit/0d89c37ef1d9e912b3f804dbfbccecb7d331c255

**Comment by RomixERR** [comment]
Oh, thank you very much! I thought I was doing something wrong.

**Comment by adoin** [comment]
> Only the zits model needs scikit-image, and I think we can remove it from the dependency and use opencv to implement the corresponding operation.
> 
> Modified in: [0d89c37](https://github.com/Sanster/lama-cleaner/commit/0d89c37ef1d9e912b3f804dbfbccecb7d331c255)

Not working. Still "ERROR: Could not build wheels for scikit-image, which is required to install pyproject.toml-based projects
"

**Comment by Sanster** [comment]
@adoin The pip package is not yet released, did you pull the latest code from git?

**Comment by adoin** [comment]
> @adoin The pip package is not yet released, did you pull the latest code from git?

Yes I do.

**Comment by adoin** [comment]
> @adoin The pip package is not yet released, did you pull the latest code from git?

![image](https://user-images.githubusercontent.com/20517172/232407705-290eb46c-488a-4dbf-9391-7a3770b54245.png)

**Comment by adoin** [comment]
> @adoin The pip package is not yet released, did you pull the latest code from git?

Fix through this [https://stackoverflow.com/questions/70303758/error-could-not-build-wheels-for-scikit-learn-which-is-required-to-install-pyp](url)

**Comment by lenzfliker** [comment]
Tried @adoin method and downgraded python (3.10) to try @RomixERR method but still keep getting the same error. Any guidance is appreciated.

**Comment by lenzfliker** [comment]
Clean installed Python through Anaconda and everything worked smoothly
