### ISSUE TITLE
Can't zoom in on Windows

### ISSUE THREAD

**Issue by NetizenKev** [Sanster/lama-cleaner#282]
**Model**
No model

**Describe the bug**
Is there a way you can zoom in and out of the uploaded picture? 

This is for the one-click windows installer application by the way.

**Screenshots**

**System Info**
Lenovo Legion 7i 
Operating System: Windows 11

Software version used
- lama-cleaner: 1.1.2
- pytorch: 1.13.1
- CUDA: 11.7

**Comment by Sanster** [comment]
You can use the mouse wheel to zoom in/out

**Comment by NetizenKev** [comment]
Ok, is there anyway you can do it without mouse wheel such as with keyboard shortcut?

I don't have a mouse, only a touchpad.

**Comment by Sanster** [comment]
I can use two fingers to zoom/pinching on my mac's touchpad, but I haven't tested it on windows

**Comment by NetizenKev** [comment]
Can confirm this works on Windows too, thanks!
