### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by java43wuyi** [Sanster/lama-cleaner#285]
when i use sd2 model,something went to wrong:CUDA out of memory,what should i do?buy a new gpu? and how much gpu memory do I need?

**Comment by Sanster** [comment]
hi, you can check this to reduce vRAM usage https://lama-cleaner-docs.vercel.app/memory#stable-diffusion

**Comment by java43wuyi** [comment]
thy

**Comment by java43wuyi** [comment]
thank you
