### ISSUE TITLE
Models don't support mps on M1 Mac?

### ISSUE THREAD

**Issue by alexzadeh** [Sanster/lama-cleaner#287]
Hi,

Pytorch supports mps but all the models I've tried switch to cpu, e.g. lama says 'lama not support mps, switch to cpu'

![iTerm2 - lama-cleaner --model lama --device mps - 21-04-2023 - 16 58 17@2x](https://user-images.githubusercontent.com/11060179/233681829-bb293550-477b-4edf-b3c0-977ad63211af.jpg)

Will it be possible to use GPU with MPS on M1 Mac?

Thanks

**Comment by Sanster** [comment]
Following diffusion models support `mps` device.

```bash
MPS_SUPPORT_MODELS = [
    "instruct_pix2pix",
    "sd1.5",
    "anything4",
    "realisticVision1.4",
    "sd2",
    "paint_by_example",
]
```

lama/mat models won't work in `mps` without set environment var `PYTORCH_ENABLE_MPS_FALLBACK=1`, I've tested this before and the lama model does not get a speed boost after adding this environment variable

**Comment by alexzadeh** [comment]
Thanks for the feedback. That's fantastic that the SD models support mps.
