### ISSUE TITLE
[Feature Request] How could I package this into a windows exe file?

### ISSUE THREAD

**Issue by ArSrNa** [Sanster/lama-cleaner#288]
I used pyinstaller to package it, but a incredible error occurred. There are more than 400,000 files taken up more than 8GB, especially pytorch.
And tons of fatal errors occured, quantities of dependencies were lost. I copy them manually, and encounter the fucking SB issue as above !!!!:(((((((((((((((((((((((((((((((((((
How could I package via a efficient way, e.g. https://github.com/xinntao/Real-ESRGAN/releases, only 100MB, an exe file and some dll files.

![image](https://user-images.githubusercontent.com/42886855/233795331-2549fe6d-01e7-47ba-8107-cf9c9d23d15e.png)

I want to use it through nodejs `child_process`, but this issue just fucking disturb me :(

**Comment by Sanster** [comment]
Real-ESRGAN using ncnn & vulkan as inference engine, so its installation package is very small. To make a portable executable file of Lama Cleaner, I can think of two ways to do this
1. using libtorch, the c++ sdk of pytorch
2. find ncnn version of LaMa or Stable Diffusion and integrate with Lama Cleaner

But I think these two methods require more work than you figuring out how to use pyinstaller(regardless of the installation package size). Good luck to you.
