### ISSUE TITLE
I am getting errors

### ISSUE THREAD

**Issue by FlowDownTheRiver** [Sanster/lama-cleaner#29]
C:\lama-cleaner>call conda activate lama

(lama) C:\lama-cleaner>python main.py --device=cpu --gui --gui-size 800 640 --crop-margin 128
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    main()
  File "main.py", line 160, in main
    model = LaMa(crop_trigger_size=args.crop_trigger_size,
  File "C:\lama-cleaner\lama_cleaner\lama\__init__.py", line 38, in __init__
    model = torch.jit.load(model_path, map_location="cpu")
  File "C:\Users\breakmycurse\.conda\envs\lama\lib\site-packages\torch\jit\_serialization.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I tried to install pytorch as well with cuda support.It is giving errors.Couldn't find a way to use the lama-cleaner.

How can I solve this issue?

**Comment by FlowDownTheRiver** [comment]
my environment : 

(lama) C:\lama-cleaner>conda list
# packages in environment at C:\Users\breakmycurse\.conda\envs\lama:
#
# Name                    Version                   Build  Channel
ca-certificates           2022.3.29            haa95532_0
certifi                   2021.10.8        py38haa95532_2
click                     8.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               11.3.1               h59b6b97_2
flask                     2.1.1                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
flaskwebgui               0.3.5                    pypi_0    pypi
importlib-metadata        4.11.3                   pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jinja2                    3.1.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
numpy                     1.22.3                   pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
openssl                   1.1.1n               h2bbff1b_0
pip                       21.2.2           py38haa95532_0
python                    3.8.13               h6244533_0
setuptools                58.0.4           py38haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.38.2               h2bbff1b_0
torch                     1.11.0                   pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
werkzeug                  2.1.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
whichcraft                0.6.1                    pypi_0    pypi
wincertstore              0.2              py38haa95532_2
zipp                      3.8.0                    pypi_0    pypi

**Comment by Sanster** [comment]
Looks like your model is corrupted. Delete `~/.cache/torch/hub/checkpoints/big-lama.pt`(You should find the corresponding directory under windows) file and run `main.py` again

**Comment by FlowDownTheRiver** [comment]
@Sanster Thank you very much for pin-pointing the error.It seems that the model got corrupted.Everything works perfectly now. It works with cuda with pytorch-gpu as well.

I have another problem though.I don't know if this is possible or not. In the UI,to change brush size with a shortcut is assigned to"[" "]" keys.
My keyboard layout is unfortunately making it very hard to use. I have to press Alt GR + 8 = [ , and Alt GR + 9 = ] ,to make those symbols. Is there anyway that we can re-assing those keys to like +,- keys on the numpad,or something like holding ctrl key and mouse scroll up and down to increase brush size ,or decrease it?

**Comment by FlowDownTheRiver** [comment]
![2022-04-07 05_04_46-Window](https://user-images.githubusercontent.com/71787427/162106013-ce86fe82-5248-40d2-ac0b-23f256ad1f5a.jpg)
![2022-04-07 05_05_10-](https://user-images.githubusercontent.com/71787427/162106017-46eed821-ec86-49be-894d-3763afe46eaf.jpg)
![2022-04-07 05_04_57-](https://user-images.githubusercontent.com/71787427/162106019-8230c4e0-b18e-46f8-a831-3030479d4150.jpg)
After the dark theme,the UI elements got very small on a 1080p monitor,like it is working in 4k mode. I didn't want to open a new thread for that,but wanted you to know.
