### ISSUE TITLE
[BUG] color changes

### ISSUE THREAD

**Issue by wolfkingal2000** [Sanster/lama-cleaner#291]
When I want to copy the picture, its color changes
all model and cuda

**Comment by Sanster** [comment]
Can you post two pictures as examples?

**Comment by wolfkingal2000** [comment]
like this 
1=orginal
2 =copy 
3=And when you copy it again several times, the color becomes very bad. It is not visible on color screens, but it is very visible on black or white photos or manga.

![009 25(1)](https://user-images.githubusercontent.com/131250049/234154358-30e580f4-b571-4e7f-aebd-7b28bd14ed84.jpg)

**Comment by Kingal20000** [comment]
> Can you post two pictures as examples?

https://github.com/Sanster/lama-cleaner/issues/291#issuecomment-1521040690

**Comment by Sanster** [comment]
> like this 1=orginal 2 =copy 3=And when you copy it again several times, the color becomes very bad. It is not visible on color screens, but it is very visible on black or white photos or manga.
> 
> ![009 25(1)](https://user-images.githubusercontent.com/131250049/234154358-30e580f4-b571-4e7f-aebd-7b28bd14ed84.jpg)

It does look bad, but I tried a few comic images and didn't notice a change in color. To help pinpoint the problem, there are a few questions I'd like to ask
1. If you don't use the copy (ctrl+c) operation, but instead use the download operation (clicking on the download button at the bottom), will there be any color issues?
2. Did you perform any operations during step 『2』-> 『3』 in your example image? Or did you just repeat pressing ctrl+c multiple times?
3. Can you send me the original files of the three images in your example picture to my email address? My email address is cwq1913@gmail.com.

**Comment by wolfkingal2000** [comment]
> > like this 1=orginal 2 =copy 3=And when you copy it again several times, the color becomes very bad. It is not visible on color screens, but it is very visible on black or white photos or manga.
> > ![009 25(1)](https://user-images.githubusercontent.com/131250049/234154358-30e580f4-b571-4e7f-aebd-7b28bd14ed84.jpg)
> 
> It does look bad, but I tried a few comic images and didn't notice a change in color. To help pinpoint the problem, there are a few questions I'd like to ask
> 
> 1. If you don't use the copy (ctrl+c) operation, but instead use the download operation (clicking on the download button at the bottom), will there be any color issues?
> 2. Did you perform any operations during step 『2』-> 『3』 in your example image? Or did you just repeat pressing ctrl+c multiple times?
> 3. Can you send me the original files of the three images in your example picture to my email address? My email address is [cwq1913@gmail.com](mailto:cwq1913@gmail.com).

![image](https://github.com/Sanster/lama-cleaner/assets/131250049/7161a29f-a6c3-4d58-a019-8ff95c13bffa)
 hi that bug fixed  one of this get updated bug fixed  
 - Python version: 3.10.11
- torch: 2.ø.O+cu118
- Pillow: 9.5.ø
- diffusers: 0.14.ø
- transformers: 4.27.4
- opencv-python: 4.7.ø.72
- xformers: 19
- accelerate: ø.19.ø
- lama-cleaner: 1.1.2
