### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by rahmanshaber** [Sanster/lama-cleaner#3]
I have 6GB memory in gtx2060. trying to use a 1024x659 image. used smallest brush with just one stroke
getting this memory error
```
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.02 GiB already allocated; 0 bytes free; 4.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
is it that memory taxing or there is an error?

**Comment by rahmanshaber** [comment]
Also website load speed is slow.

**Comment by Sanster** [comment]
> I have 6GB memory in gtx2060. trying to use a 1024x659 image. used smallest brush with just one stroke getting this memory error
> 
> ```
> RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.02 GiB already allocated; 0 bytes free; 4.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```
> 
> is it that memory taxing or there is an error?

- GPU memory is not related to size of brush or number of stroke
- LaMa is a big model，you need more GPU memory，or you can try cpu with --device=cpu

**Comment by rahmanshaber** [comment]
With CPU it works, but image is low resulation when i download. i think the dev pushed a option to not compress the image. how to enable it here?

**Comment by Sanster** [comment]
Image is resized [here](https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/app/src/App.tsx#L69)，you can change `maxSize`

**Comment by rahmanshaber** [comment]
i changed it but still the image is resizing 
![image](https://user-images.githubusercontent.com/30831735/142728145-ea7db1b9-2e6f-4161-8f33-3a0f95844f94.png)

**Comment by Sanster** [comment]
Did you execute the `yarn build`?

**Comment by rahmanshaber** [comment]
no, how to do that?

**Comment by rahmanshaber** [comment]
![image](https://user-images.githubusercontent.com/30831735/142728393-245714f2-caf4-425c-8b79-7f7a9338d09d.png)

**Comment by Sanster** [comment]
follow README ：https://github.com/Sanster/lama-cleaner/blob/main/README.md#fronted

**Comment by rahmanshaber** [comment]
can't you guys add an option in the website to do keep the original image? i see a button called HD in the original project

**Comment by Sanster** [comment]
Maybe when I have time I can add this “simple" button

**Comment by rahmanshaber** [comment]
That will be great. That button only limits to 2k, if possible add 3 option, 1080, 2k and original.

**Comment by Sanster** [comment]
> That will be great. That button only limits to 2k, if possible add 3 option, 1080, 2k and original.

Done. Check the new relesse
