### ISSUE TITLE
嗨，作者你好，我希望通过有效的方式支持你，但kofi不允许同样来自中国的用户向你付款

### ISSUE THREAD

**Issue by ntf-Cinema4D-sd** [Sanster/lama-cleaner#304]
按照paypal的说法，它认为同样来自中国的支持者违反了“国际法”，这让我很无奈，希望你能够提供可以供中国用户付款的方式，例如支付宝或微信。如果你认为这是可以的，请回复。特别对你的辛苦工作与付出表示衷心感谢！

![Snipaste_2023-05-10_04-53-22](https://github.com/Sanster/lama-cleaner/assets/72090841/5e1fc5e8-b17d-498a-9d0e-6e04d62b08cd)

**Comment by Sanster** [comment]
感谢支持🙏  。这是 windows 安装包的购买链接，支持微信和支付宝：https://panicbyte.lemonsqueezy.com/checkout?cart=b38e6b82-8c2a-42f8-9508-567445d8100f

**Comment by ntf-Cinema4D-sd** [comment]
好的，已经成功购买，一点小小的支持希望不要嫌弃。再次对你努力成果表示最大的尊敬和支持！加油！！
![Snipaste_2023-05-11_01-41-00](https://github.com/Sanster/lama-cleaner/assets/72090841/0d122cb9-01db-493b-a932-d53ce9db97ec)
