### ISSUE TITLE
Is there a way to run LDM on images higher than 608p?

### ISSUE THREAD

**Issue by flagshipbowtie** [Sanster/lama-cleaner#31]
I've got 1070 with 8gb.
Is there a way around it using disk space? Page file increase or something? I would just need buy a videcard with more VRAM?
Having read the main page. Can't 3090 run LDM on 1080p? Only 720p tops? It was jsut an example?

**Comment by Sanster** [comment]
Can't 3090 run LDM on 1080p? Only 720p tops? It was jsut an example?

> It's an example. Because LDM consumes a lot of GPU memory, the backend will only run on cropped stroke area, so the memory consumption depends on the size of the crop area. For reference, a 396*554 crop area takes around 3G GPU memory.

Is there a way around it...?

> Run on CPU or reconvert the torchscript model to support fp16(current model reports an error when using fp16)

**Comment by flagshipbowtie** [comment]
I've tried running on CPU and it can't even do 608p. Says buy more RAM. I've got 16gb.
Not a coder. I just make memes and I'd donate towards the work you do here but I literally cannot. I'm Russian

**Comment by Sanster** [comment]
I'm guessing you've tried the lama model, but didn't get good results?

**Comment by Sanster** [comment]
According to your description, it seems that there is no way to run 1080p pictures(ldm) on your existing hardware. 😞

**Comment by flagshipbowtie** [comment]
Anyway why are PNGs produced by Lama cleaner cause error in Adobe Apps when I try to import?

**Comment by flagshipbowtie** [comment]
> > Anyway why are PNGs produced by Lama cleaner cause error in Adobe Apps when I try to import?
> 
> According to https://www.checkfiletype.com/ ,png created by lama cleaner, is a jpg image,it also ignores alpha channel and rasterizes image with a white background fill.That is why. ![lama](https://user-images.githubusercontent.com/71787427/162256551-f5a400be-3f7e-4cec-8b24-dcb86a0d5d12.png) ![lama_cleanup](https://user-images.githubusercontent.com/71787427/162256561-ee663083-d664-4cc9-b8e1-d82fcbbbc331.png)

Ohhhh it's jpg.  Makes sense but why... 

@Sanster Is there a reason true PNGs don't come out as an output?

**Comment by Sanster** [comment]
The problem with image types has been fixed in this modification: caed45b52028f1698d580a1080058f4d105de65e

Know issue: RGBA png will lose Alpha channel

**Comment by Sanster** [comment]
fix RGBA png will lose Alpha channel: 1b1aade06793571c920431079d6c015248ecb576

|Origin image| lama-cleaner result| cleanup.pictures result|
|-------------|--------------------|-----------------------|
|![png_example](https://user-images.githubusercontent.com/3998421/162548601-36dff1f9-400a-4036-bd06-393f93148875.png)|![png_example_lama_cleaner](https://user-images.githubusercontent.com/3998421/162548669-ffec0da2-ef9f-4601-81e2-aa5feca91323.png)|![png_example_cleanup](https://user-images.githubusercontent.com/3998421/162548674-970adc8d-67ed-4441-bf44-3f77d3c04a89.png)|

**Comment by Sanster** [comment]
> fix RGBA png will lose Alpha channel: [1b1aade](https://github.com/Sanster/lama-cleaner/commit/1b1aade06793571c920431079d6c015248ecb576)
> 
> Origin image	lama-cleaner result	cleanup.pictures result
> ![png_example](https://user-images.githubusercontent.com/3998421/162548601-36dff1f9-400a-4036-bd06-393f93148875.png)	![png_example_lama_cleaner](https://user-images.githubusercontent.com/3998421/162548669-ffec0da2-ef9f-4601-81e2-aa5feca91323.png)	![png_example_cleanup](https://user-images.githubusercontent.com/3998421/162548674-970adc8d-67ed-4441-bf44-3f77d3c04a89.png)

fix a related bug: [bug fix: resize alpha channel when using non original image size](https://github.com/Sanster/lama-cleaner/commit/ca65c95d22bc8c39c49a64155ddabb570d0ab509)

**Comment by Sanster** [comment]
It turns out the GPU version of pytorch will take up more CPU RAM(even model not run on GPU) than the CPU version

- https://github.com/pytorch/pytorch/issues/63555
- https://github.com/pytorch/pytorch/issues/64720

**Comment by flagshipbowtie** [comment]
> It turns out the GPU version of pytorch will take up more CPU RAM(even model not run on GPU) than the CPU version
> 
> * [pytorch 1.8.1+cu111 used much more CPU RAM than pytorch 1.8.1 after run `import torch` pytorch/pytorch#63555](https://github.com/pytorch/pytorch/issues/63555)
> * [Unreasonable memory usage for hello world example pytorch/pytorch#64720](https://github.com/pytorch/pytorch/issues/64720)

I'm running on CUDA 10.2

**Comment by Sanster** [comment]
ldm model support fp16 at version 0.12.0, use less GPU memory. Benchmark on 3090

|Image size| GPU memory|
|-----------|-------------|
| 720x519 | 6147mb|
|1080x778|17499mb|

**Comment by flagshipbowtie** [comment]
> ldm model support fp16 at version 0.12.0, use less GPU memory. Benchmark on 3090
> 
> Image size	GPU memory
> 720x519	6147mb
> 1080x778	17499mb

That's not really an improvement for me. 8 GB Vram. Sounds like it's still the same 608p or slighly higer is not really a drastic change. Well LDM requires lots of memory. Unless someone encodes some use of SDD it's really pointless to optimize anything.
