### ISSUE TITLE
[BUG] can't run cleaner after fresh installation

### ISSUE THREAD

**Issue by Rogal80** [Sanster/lama-cleaner#313]
hi, i have issue after clean installation , I always get this issue 

**Describe the bug**
Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.9
- torch: 1.13.1+cu117
- Pillow: 9.3.0
- diffusers: 0.14.0
- transformers: 4.27.4
- opencv-python: 4.7.0.68
- xformers: 0.0.16
- accelerate: 0.18.0
- lama-cleaner: 1.1.2

2023-05-29 12:04:58.545 | INFO     | lama_cleaner.parse_args:parse_args:182 - Loading installer config from I:\Github\Cleaner_Lama\lama-cleaner\win_start.bat\..\installer_config.json
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: DLL load failed while importing libtriton: The specified module could not be found.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program Files\Python310\lib\runpy.py:196 in _run_module_as_main                               │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Program Files\Python310\lib\runpy.py:86 in _run_code                                          │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from lama_cleaner import entry_point                                                         │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(entry_point())                                                                  │
│   8                                                                                              │
│                                                                                                  │
│ C:\Program Files\Python310\lib\site-packages\lama_cleaner\__init__.py:16 in entry_point          │
│                                                                                                  │
│   13 │   args = parse_args()                                                                     │
│   14 │   # To make os.environ["XDG_CACHE_HOME"] = args.model_cache_dir works for diffusers       │
│   15 │   # https://github.com/huggingface/diffusers/blob/be99201a567c1ccd841dc16fb24e88f7f239    │
│ ❱ 16 │   from lama_cleaner.server import main                                                    │
│   17 │                                                                                           │
│   18 │   main(args)                                                                              │
│   19                                                                                             │
│                                                                                                  │
│ C:\Program Files\Python310\lib\site-packages\lama_cleaner\server.py:24 in <module>               │
│                                                                                                  │
│    21 from lama_cleaner.const import SD15_MODELS                                                 │
│    22 from lama_cleaner.file_manager import FileManager                                          │
│    23 from lama_cleaner.model.utils import torch_gc                                              │
│ ❱  24 from lama_cleaner.model_manager import ModelManager                                        │
│    25 from lama_cleaner.plugins import (                                                         │
│    26 │   InteractiveSeg,                                                                        │
│    27 │   RemoveBG,                                                                              │
│                                                                                                  │
│ C:\Program Files\Python310\lib\site-packages\lama_cleaner\model_manager.py:15 in <module>        │
│                                                                                                  │
│   12 from lama_cleaner.model.paint_by_example import PaintByExample                              │
│   13 from lama_cleaner.model.instruct_pix2pix import InstructPix2Pix                             │
│   14 from lama_cleaner.model.sd import SD15, SD2, Anything4, RealisticVision14                   │
│ ❱ 15 from lama_cleaner.model.zits import ZITS                                                    │
│   16 from lama_cleaner.model.opencv2 import OpenCV2                                              │
│   17 from lama_cleaner.schema import Config                                                      │
│   18                                                                                             │
│                                                                                                  │
│ C:\Program Files\Python310\lib\site-packages\lama_cleaner\model\zits.py:5 in <module>            │
│                                                                                                  │
│     2 import time                                                                                │
│     3                                                                                            │
│     4 import cv2                                                                                 │
│ ❱   5 import skimage                                                                             │
│     6 from skimage import color, feature                                                         │
│     7 import torch                                                                               │
│     8 import torch.nn.functional as F                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: source code string cannot contain null bytes
Press any key to continue . . .

**Screenshots**

**System Info**
windows10
- lama-cleaner: 
- pytorch: 
- CUDA:

**Comment by Rogal80** [comment]
after update -still cant run -, pls help :

2023-06-06 21:39:05.116 | INFO     | lama_cleaner.parse_args:parse_args:193 - Loading installer config from I:\Github\Cleaner_Lama\lama-cleaner\win_start.bat\..\installer_config.json
Traceback (most recent call last):
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\Scripts\lama-cleaner.exe\__main__.py", line 7, in <module>
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\site-packages\lama_cleaner\__init__.py", line 16, in entry_point
    from lama_cleaner.server import main
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\site-packages\lama_cleaner\server.py", line 23, in <module>
    from lama_cleaner.model.utils import torch_gc
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\site-packages\lama_cleaner\model\utils.py", line 10, in <module>
    from diffusers import (
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\site-packages\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\site-packages\diffusers\configuration_utils.py", line 34, in <module>
    from .utils import (
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "I:\Github\Cleaner_Lama\lama-cleaner\installer\lib\site-packages\diffusers\utils\accelerate_utils.py", line 24, in <module>
    import accelerate
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\accelerate\accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\accelerate\tracking.py", line 49, in <module>
    import wandb
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\__init__.py", line 3, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\lib\config_util.py", line 10, in <module>
    from wandb.util import load_yaml
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\wandb\util.py", line 53, in <module>
    from wandb.env import get_app_url
  File "C:\Users\jerzy\AppData\Roaming\Python\Python310\site-packages\wandb\env.py", line 19, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'

**Comment by Sanster** [comment]
It looks like an python environment problem, I don't have a clue either, maybe this will help https://stackoverflow.com/questions/32798137/importerror-no-module-named-appdirs 

If this is a problem you are having with  [Window 1-click installer](https://lama-cleaner-docs.vercel.app/install/windows_1click_installer), please leave your email and I will refund you.

**Comment by Rogal80** [comment]
ok, don't worry, maybe some day it will run after some updates, it was working in the past. And pls don't refund - you are doing greate job , and you deserve it :)

**Comment by DominusFL** [comment]
I just downloaded it, same problem, can't run it due to the missing Triton. Anyone figure it out yet?

**Comment by Sanster** [comment]
> I just downloaded it, same problem, can't run it due to the missing Triton. Anyone figure it out yet?

hi, missing triton will not affect any usage, there is this problem https://github.com/Sanster/lama-cleaner/issues/386 with the current installation package, I will fix it as soon as possible.

**Comment by DominusFL** [comment]
Thanks. It does slightly affect usage, as it does not allow it to run.
Looking forward to the fix. ;-)

Regards,
Rick
