### ISSUE TITLE
How can i use it in macOS

### ISSUE THREAD

**Issue by domjeck** [Sanster/lama-cleaner#325]
Thx to share this nice tool ! But how can i use it in macOS? It keeps prompting me with an error message [object event]

**Comment by Sanster** [comment]
Can you please check the error message in the terminal and take a screenshot?

**Comment by domjeck** [comment]
Thank you for your reply, and  i run it with 'serve -s build', so i can't see the terminal massage. how can i rule out this problem.

**Comment by domjeck** [comment]
@Sanster Thank you for your reply, and i run it with 'serve -s build', so i can't see the terminal messages. how can i rule out this problem.

**Comment by Sanster** [comment]
`serve -s build` What is this command used for? I am not very familiar with it. Recommended installation and startup method is:

```bash
pip install lama-cleaner
lama-cleaner --model=lama --device=cpu --port=8080
```

**Comment by andupotorac** [comment]
> `serve -s build` What is this command used for? I am not very familiar with it. Recommended installation and startup method is:
> 
> ```shell
> pip install lama-cleaner
> lama-cleaner --model=lama --device=cpu --port=8080
> ```

Actually for MAC you want to use one of the models that supports MPS, so you'd start like this:
`lama-cleaner --model=sd1.5 --device=mps --port=8080`
