### ISSUE TITLE
[BUG]   Could not find TensorRT  what  meaning and how to fix??

### ISSUE THREAD

**Issue by wolfkingal2000** [Sanster/lama-cleaner#328]
hi i get this massage error  what  meaning and how to fix? ?

W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
/usr/local/lib/python3.10/dist-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(

**Comment by Sanster** [comment]
Can you try uninstall tensorflow from your environment?

One possible reason I can think of is that [transformers](https://github.com/huggingface/transformers) is a project that supports multiple frameworks(pytorch, tensorflow, jax...), and this issue may be related to it
