### ISSUE TITLE
One click install additions

### ISSUE THREAD

**Issue by gitihobo** [Sanster/lama-cleaner#330]
I understand the five dollar price tag but can we add automatic anaconda venv or an exe to it? I also want to outpaint and make backgrounds transparent, maybe even remove video watermarks.

**Comment by Sanster** [comment]
You can refer to these two files to create a conda environment and install Lama Cleaner dependencies:
- https://github.com/Sanster/lama-cleaner/blob/main/scripts/environment.yaml
- https://github.com/Sanster/lama-cleaner/blob/main/scripts/user_scripts/win_config.bat

**Comment by gitihobo** [comment]
Did it, is it possible to do video watermark removal through?

**Comment by Sanster** [comment]
Lama Cleaner can only process image，maybe you can try this project: https://github.com/gaomingqi/Track-Anything
