### ISSUE TITLE
instruct-pix2pix的模型文件应放在哪里呢？

### ISSUE THREAD

**Issue by ddyec** [Sanster/lama-cleaner#337]
借助pip安装，lama-cleaner已经成功运行
但是，当尝试使用instruct-pix2pix模型时，命令符提示【连接出错】
可是，在自己下载模型以后，却不知道应该放在哪个文件夹内
请您能否告知，我应该放在那里呢？

**Comment by Sanster** [comment]
手动下载的模型是这个？
<img width="318" alt="image" src="https://github.com/Sanster/lama-cleaner/assets/3998421/87cbd5c8-e991-4b3c-b144-2db2e5ef65f4">

lama-cleaner 不支持加载 ckpt/safetensors 的 instruct-pix2pix 模型，建议在命令行挂代理后自动下载

**Comment by ddyec** [comment]
了解了....（主要是浏览器可以，但命令就报错）
再试吧,,,,
