### ISSUE TITLE
LAMA outputs PNGs that are actually JPG files why?

### ISSUE THREAD

**Issue by flagshipbowtie** [Sanster/lama-cleaner#34]
Is there a reason true PNGs don't come out as an output but JPEGs with PNG extention ? https://cleanup.pictures/ make true PNGs. Your code is based on the same github project. So what's going on here?

**Comment by Sanster** [comment]
Fixed in caed45b52028f1698d580a1080058f4d105de65e

The back-end code is different, their back-end code is not open source
