### ISSUE TITLE
[BUG]Use 1 click cannot use the brush function

### ISSUE THREAD

**Issue by 9ikj** [Sanster/lama-cleaner#340]
**Model**
lama

**Describe the bug**
500 errors occurred after applying with a brush

**Screenshots**
![QQ截图20230709040034](https://github.com/Sanster/lama-cleaner/assets/10474114/6739f248-74ce-4cb9-9ae4-a336dbc36cf0)
![QQ截图20230709040049](https://github.com/Sanster/lama-cleaner/assets/10474114/694e46a0-9f41-4963-becb-43e124bfbbb5)

**System Info**
Software version used
- lama-cleaner: 1.2.1
- pytorch: torch 1.13.1+cu117,torchvision 0.14.1+cu117
- CUDA:12.2

**Comment by jameswan** [comment]
I got the same error also.
This did not exist previously.

**Comment by Sanster** [comment]
Thank you for reporting this issue. I may have figured out the cause of the problem, and I will release a fix today.

**Comment by jameswan** [comment]
Thank you!

**Comment by Sanster** [comment]
fixed in 1.2.2
