### ISSUE TITLE
Fatal error in launcher: Unable to create process using

### ISSUE THREAD

**Issue by xperternier** [Sanster/lama-cleaner#344]
<img width="867" alt="螢幕擷取畫面 2023-07-11 022828" src="https://github.com/Sanster/lama-cleaner/assets/116382039/a8645868-499c-4cc9-9b91-49cd09fc0dac">

**Comment by Sanster** [comment]
hi, do you run win_config.bat first?

**Comment by xperternier** [comment]
I have executed both

**Comment by Sanster** [comment]
1. 压缩包的解压路径中不能有中文
2. 在新目录解压以后不要移动解压目录，直接运行 bat 文件

**Comment by xperternier** [comment]
lama-cleaner: error: torch.cuda.is_available() is False, please use --device cpu or check your pytorch installation

**Comment by xperternier** [comment]
thanks! i got it
