### ISSUE TITLE
How to erase many same shape watermarks once?

### ISSUE THREAD

**Issue by stevezhang88** [Sanster/lama-cleaner#347]
![test](https://github.com/Sanster/lama-cleaner/assets/129701399/25e9a9fc-45a3-4aff-abdd-f5d95aff0743)

Now I have to clean one by one. It costs too much time.

Thanks

**Comment by Sanster** [comment]
If your watermarks are in fixed positions, you can save the mask after cleaning it once (open the "download mask" setting in the settings). Next time, you can directly upload the mask.

**Comment by stevezhang88** [comment]
Thanks.
