### ISSUE TITLE
[BUG] Can launch app on linux

### ISSUE THREAD

**Issue by andzejsp** [Sanster/lama-cleaner#357]
**Model**
idk

**Describe the bug**
Cant launch app.

**Screenshots**
![image](https://github.com/Sanster/lama-cleaner/assets/80409979/1ae24f3d-e77f-4c88-a786-3684695949d0)

**System Info**
See screenshot.

Linux VM, ubuntu22.04

GTX1080ti

I tried with venv and it still the same.

Tried with cuda instead of cpu, still the same.

And i cant exit the terminal with CTRL+C

![image](https://github.com/Sanster/lama-cleaner/assets/80409979/423c1902-912f-4fc8-ae48-d475e07fc8da)

**Comment by Sanster** [comment]
I can't tell what happened just by looking at this log, perhaps it is stuck on automatic model downloading? You can refer here for manual model downloading.https://lama-cleaner-docs.vercel.app/install/download_model_manually
