### ISSUE TITLE
[BUG] With 1 click installer

### ISSUE THREAD

**Issue by Gazgiza** [Sanster/lama-cleaner#360]
Hi, I recently by the 1 click installer and, when I want to generate something, this appear :
![Capture d'écran 2023-08-19 213900](https://github.com/Sanster/lama-cleaner/assets/128604910/c7f15c1c-eb1c-4436-90f0-437d6a4eaa28)
Can you help me?

**Comment by Gazgiza** [comment]
Eaven with lama model
![Capture d'écran 2023-08-19 214219](https://github.com/Sanster/lama-cleaner/assets/128604910/384e840d-6c14-4b16-891d-18b58d430e41)

**Comment by Sanster** [comment]
Hi, it seems like there's an issue with the server, could you screenshot the command line error? Thanks
