### ISSUE TITLE
[BUG] 这个水印去不掉？

### ISSUE THREAD

**Issue by lucasjinreal** [Sanster/lama-cleaner#363]
**Model**
Which model are you using?

**Describe the bug**
**Screenshots**
![LoDi-lovely pink style, snow-2023-08-27-13_34_14-yfzl7t05ivaff96dv1mpci](https://github.com/Sanster/lama-cleaner/assets/21303438/7ff7cce8-0870-43a1-a7cd-63c009878c37)

**System Info**
Software version used
- lama-cleaner: 
- pytorch: 
- CUDA:

<img width="924" alt="image" src="https://github.com/Sanster/lama-cleaner/assets/21303438/4294d891-cabb-4d4b-9ea1-b5d19ebb25cf">

奇怪啊，就是下面的水印qu bu掉

**Comment by Sanster** [comment]
这个水印试试现在 alpha 通道的，模型只能处理 rgb，可以先转成 jpg，去掉以后再用 remove_bg 转成有透明图层的 png
