### ISSUE TITLE
[Feature Request] Translate Text 

### ISSUE THREAD

**Issue by TheMBeat** [Sanster/lama-cleaner#364]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Automatic recognition of text via OCR
Masks from the text boxes
Inpaint 
Translate the text and paste it back

Like: https://github.com/iuliaturc/detextify/tree/main/detextify

**Comment by Sanster** [comment]
https://github.com/iuliaturc/detextify do not have translate/paste text back feature, I also haven't found a better method for generating text that matches the original style. For more discussion, you can see here. https://github.com/Sanster/lama-cleaner/discussions/221
