### ISSUE TITLE
Request Flask Server

### ISSUE THREAD

**Issue by sunatte-saad** [Sanster/lama-cleaner#371]
I am trying to access the inpaint method using the requests.

`import requests
import io

server_url = "http://127.0.0.1:8081/inpaint"
files={    "image":image_bytes,
                 "mask":mask_bytes}
data = {

    "ldmSteps": 25,
    "ldmSampler": "plms",
    "zitsWireframe": True,
    "hdStrategy": "Crop",
    "hdStrategyCropMargin": 196,
    "hdStrategyCropTrigerSize": 800,
    "hdStrategyResizeLimit": 2048,
    "prompt": "",
    "negativePrompt": "",
    "croperX": 128,
    "croperY": 128,
    "croperHeight": 512,
    "croperWidth": 512,
    "useCroper": False,
    "sdMaskBlur": 5,
    "sdStrength": 0.75,
    "sdSteps": 50,
    "sdGuidanceScale": 7.5,
    "sdSampler": "uni_pc",
    "sdSeed": -1,
    "sdMatchHistograms": False,
    "sdScale": 1,
    "cv2Radius": 5,
    "cv2Flag": "INPAINT_NS",
    "paintByExampleSteps": 50,
    "paintByExampleGuidanceScale": 7.5,
    "paintByExampleSeed": -1,
    "paintByExampleMaskBlur": 5,
    "paintByExampleMatchHistograms": False,
    "p2pSteps": 50,
    "p2plmageGuidanceScale": 1.5,
    "p2pGuidanceScale": 7.5,
    "controlnet_conditioning_scale": 0.4,
    "controlnet_method": "control_v11p_sd15_canny",
}

response = requests.post(server_url, data=data, files=files)

if response.status_code == 200:
    print("Inpainting completed successfully.")
else:
    print(f"Error: {response.status_code} - {response.text}")`
    
 can you help me with how to correctly send the payload? or if I could have payload for all the APIs if you have them documented somewhere?
or maybe I am sending the images in a wrong format. Kindly assist me in this

**Comment by Sanster** [comment]
I'm sorry for the confusion, the design of the inpaint interface is very messy, all parameters are mixed together, the following code is what I have tested and can work:

```python
import requests

# https://raw.githubusercontent.com/Sanster/lama-cleaner/main/assets/dog.jpg
img_path = "dog.jpg"
# "https://user-images.githubusercontent.com/3998421/202105351-9fcc4bf8-129d-461a-8524-92e4caad431f.png"
mask_path = "mask.png"

image = open(img_path, "rb").read()
mask = open(mask_path, "rb").read()

url = "http://127.0.0.1:8080/inpaint"

response = requests.post(
    url,
    files={"image": image, "mask": mask},
    data={
        "ldmSteps": 1,
        "ldmSampler": "ddim",
        "hdStrategy": "Original",
        "zitsWireframe": False,
        "hdStrategyCropMargin": 128,
        "hdStrategyCropTrigerSize": 512,
        "hdStrategyResizeLimit": 1280,
        "prompt": "",
        "negativePrompt": "",
        "useCroper": False,
        "croperX": 0,
        "croperY": 0,
        "croperHeight": 512,
        "croperWidth": 512,
        "sdScale": 1.0,
        "sdMaskBlur": 0,
        "sdStrength": 0.75,
        "sdSteps": 50,
        "sdGuidanceScale": 7.5,
        "sdSampler": "uni_pc",
        "sdSeed": 42,
        "sdMatchHistograms": False,
        "cv2Flag": "INPAINT_NS",
        "cv2Radius": 4,
        "paintByExampleSteps": 50,
        "paintByExampleGuidanceScale": 7.5,
        "paintByExampleMaskBlur": 0,
        "paintByExampleSeed": 42,
        "paintByExampleMatchHistograms": False,
        "paintByExampleExampleImage": None,
        "p2pSteps": 50,
        "p2pImageGuidanceScale": 7.5,
        "p2pGuidanceScale": 7.5,
        "controlnet_conditioning_scale": 0.4,
        "controlnet_method": "control_v11p_sd15_canny",
        "paint_by_example_example_image": None,
    },
)

with open("out.png", "wb") as f:
    f.write(response.content)

```

**Comment by sunatte-saad** [comment]
Thankyou so much. I have been going crazy haha
I will test this out today.
Also can I have the payload for other endpoints if you have them ready? That will be a great help

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sunatte-saad** [comment]
Yesterday I had my payload finalized exactly as yours. The only problem was that I was sending a properly masked image.
Is there an APi for image segmentation and then masking?


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sunatte-saad** [comment]
Thank you so much for you help.  This worked great
if you happen to have a payload for other features, please let me know

**Comment by hamzakhalid-whizpool** [comment]
can you please help me with api call. I want to make an api call to lama from postman any idea how?

**Comment by himmeled** [comment]
would you plz tell me how to make the mask？thanks.
