### ISSUE TITLE
BLACK PAINT[BUG]

### ISSUE THREAD

**Issue by arjundheek** [Sanster/lama-cleaner#381]
**Stable Diffusion 1.5**
Which model are you using?

**Describe the bug**
I selected and cropped the area using croper but the result was BLACK painting after processing with prompt. It worked on some images but same BLACK PAINT on some images. I re-tried again on image with BLACK BUG but still shows same BLACK paint
![Screenshot](https://github.com/Sanster/lama-cleaner/assets/139465670/c0b96ae1-0c09-4003-ae1e-de5b94429559)
.

**Screenshots**

**System Info**
Software version used
- lama-cleaner: 1.2.3
- pytorch: 3.10.12
![Software versions used](https://github.com/Sanster/lama-cleaner/assets/139465670/fb63f98a-a0e2-4239-98c2-77bf971d7aea)

- CUDA:T4

**Comment by Sanster** [comment]
It might be because of the fp16 issue, you can try adding `--no-half`.

**Comment by arjundheek** [comment]
Superb Quick response. i will try. Thanks a lot.
