### ISSUE TITLE
Automatic Inpaint Selection

### ISSUE THREAD

**Issue by arjundheek** [Sanster/lama-cleaner#382]
![hair selectionn](https://github.com/Sanster/lama-cleaner/assets/139465670/4da9d803-1028-494a-96f1-aa613b7bb20c)
**Is your feature request related to a problem? Please describe.**
Hi, I always need to paint a specific area. For example, Only hair. So, Everytime inpainting is time consuming. So, How can i make sure that the hair is inpainted when i upload an image so that it generate with a prompt. Here, My prompt is also always a fixed one. "A Red color hair"

**Describe the solution you'd like**
How can i make the inpainting selection area automatic. So, How can i pass any other hair selected model into SD1.5? OR any other way so that i upload a masked image so that it works as per prompt?
![hair selection](https://github.com/Sanster/lama-cleaner/assets/139465670/bac755c3-8645-42f4-bf79-3d9f9750a5c5)

**Additional context**
![hair selection](https://github.com/Sanster/lama-cleaner/assets/139465670/56df391d-b7c3-41b4-99af-836866e96a7f)

**Comment by Sanster** [comment]
You can use [interactive segmentation](https://lama-cleaner-docs.vercel.app/plugins#interactive-segmentation) to select hair area. After drawing a mask once, you don't need to draw the mask again when changing other parameters or prompts, just click on the dream button directly (you will see the previous mask when you hover over the dream button).

**Comment by arjundheek** [comment]
Hi,
  So, using interactive segmentation, Do the hair will get its mask automatically on the other different images as well?

**Comment by Sanster** [comment]
No. For different images, the hair part needs to be reselected. I think what you might need is a semantic segmentation model specifically for hair.

**Comment by arjundheek** [comment]
I got it. So, I need to pass the semantic segmentation model. Thankyou.
