### ISSUE TITLE
Remove transparency from the HUD

### ISSUE THREAD

**Issue by flagshipbowtie** [Sanster/lama-cleaner#39]
I can't see anything. I don't wanna go dark mode and in opposite cases I have to go light mode.  

![tt](https://user-images.githubusercontent.com/103138306/163835183-a3421cab-7a6f-4fb9-b4e6-5fb281d6df1e.PNG)

**Comment by Sanster** [comment]
fix CSS issue in 0.9.3

**Dark theme white image**
<img width="1022" alt="black-fixed" src="https://user-images.githubusercontent.com/3998421/164018424-368dd3b1-429d-42b4-8e6b-df5e8bcc1c9d.png">

**Light theme black image**
<img width="1144" alt="light-fixed" src="https://user-images.githubusercontent.com/3998421/164018479-b983c388-195d-46d8-b5c9-4807b807daa2.png">
