### ISSUE TITLE
Image quality/size limited?

### ISSUE THREAD

**Issue by Eidenz** [Sanster/lama-cleaner#4]
Hello,

I was wondering if you were limiting/lowering the quality or size of the image at some point in the code?

When I use full HD as input, the output is lowered to 1024x682. Is this normal and can we change it?

Thanks

**Comment by Sanster** [comment]
Check new release.

![image](https://user-images.githubusercontent.com/3998421/143991719-2c364ab2-7e27-4cf2-b8c9-e135d9155b0d.png)
