### ISSUE TITLE
High memory consumption/usage when loading the model on iOS after converting to CoreML.

### ISSUE THREAD

**Issue by codenia** [Sanster/lama-cleaner#405]
Thank you for this great model.

After converting the model to CoreML using this script https://github.com/mallman/CoreMLaMa , the memory usage of the model is way too high on iOS.

After this line of code, the app immediately uses 1.4GB more memory than before:

MLModel *model = [MLModel modelWithContentsOfURL:[[NSBundle mainBundle] URLForResource:@"LaMa" withExtension:@"mlmodelc"] error:&error];

The actual processing of the image inpainting then requires approx. 400MB of memory, which is not too bad.

The problem is the 1.4GB memory consumption when loading the model. The older iPad and iPhone crash at this point with "Out Of Memory" (OOM) exception.

Is there a way to reduce the size of the model? Maybe a simplification or compression of the model?

**Comment by Sanster** [comment]
Maybe you can try using other smaller models from https://github.com/advimman/lama

**Comment by codenia** [comment]
I have now converted the model with 512x512 pixels and the model only uses 408MB when loading. We can work very well with this now. Thank you again for your script.

`size = (512, 512) # pixel width x height`
