### ISSUE TITLE
[BUG] Images with portrait orientation rotated 90 degrees after processing

### ISSUE THREAD

**Issue by vredesbyyrd** [Sanster/lama-cleaner#419]
**Model**
Lama

**Describe the bug**
After an image is processed, images with portrait orientation get rotated 90 degrees, ie horizontally. exiftool says the tag reads - `Orientation : Rotate 90 CW` 

**System Info**
Software version used
- lama-cleaner: 1.2.0
- pytorch: 2.1.1
- CUDA: 12.1.105

**Comment by Sanster** [comment]
Can you provide an image for testing?

**Comment by vredesbyyrd** [comment]
No problem, thank you.

![DSCF0119](https://github.com/Sanster/lama-cleaner/assets/22080838/733b24d4-f98b-4ea0-b9e3-7a1c650a7501)

**Comment by Sanster** [comment]
Fixed in the new release, lama-cleaner has now been renamed to `iopaint`, the general usage method is similar, and you can install it with `pip install iopaint`

**Comment by vredesbyyrd** [comment]
Hi, thanks for heads up. 

I installed `iopaint` and the issue is fixed :)

I see at this time the `--help` menu is pretty minimal. I used to start lama-cleaner with the following flags: 

```
 lama-cleaner --model=lama  \
--enable-interactive-seg --interactive-seg-model=vit_l \
--input=/mnt/PHOTO/lama-cleaner/input --output-dir=/mnt/PHOTO/lama-cleaner/output
```
Do you intend to implement any of the flags from lama-cleaner or is this a new minimal version? Thanks for your time!
