### ISSUE TITLE
Add a configuration to toggle automatic or manual mode

### ISSUE THREAD

**Issue by lucellent** [Sanster/lama-cleaner#42]
I'd love it if there was a manual "Clean up" button, rather than having to select everything within one selection.

For example, I'd mask several different items, and then click on Clean up, rather than mask the first one -> wait for clean up > mask the second one > wait for clean up, and so on...

Also, sometimes when zoomed in, I can't reach and mask all of the object so I have to let go of the mouse click which automatically starts the clean up process, rather than letting me continue it and then manually deciding when to clean up

Hope this makes sense :)

**Comment by flagshipbowtie** [comment]
How about you read the main page dumbass?
>Multi stroke support. Press and hold the cmd/ctrl key to enable multi stroke mode.

**Comment by Sanster** [comment]
@lucellent  Currently we can `hold the cmd/ctrl key` to do multi-stroke painting, but I think a manual "Clean up" button will be helpful in the following scenarios: working on a very large image having many defects to remove. I will add a configuration in the next version to toggle automatic or manual mode.

**Comment by lucellent** [comment]
Great to know, thank you!

**Comment by FlowDownTheRiver** [comment]
> I'd love it if there was a manual "Clean up" button, rather than having to select everything within one selection.
> 
> For example, I'd mask several different items, and then click on Clean up, rather than mask the first one -> wait for clean up > mask the second one > wait for clean up, and so on...
> 
> Also, sometimes when zoomed in, I can't reach and mask all of the object so I have to let go of the mouse click which automatically starts the clean up process, rather than letting me continue it and then manually deciding when to clean up
> 
> Hope this makes sense :)

@lucellent You can hold ctrl while painting and even you release your left mouse click it doesn't do the clean up. you can paint other regions by this way.Aso in combination while holding ctrl,you can use your mouse scroll to zoom in and out paint areas as you wish + you can press space and drag the image while still holding ctrl. @Sanster Manuel mode is a good idea,it can act like ctrl is pressed all the time.Activation can be made by a shortcut or a button.

**Comment by Sanster** [comment]
Check the new release: https://github.com/Sanster/lama-cleaner/releases/tag/0.10.0

**Comment by FlowDownTheRiver** [comment]
> Check the new release: https://github.com/Sanster/lama-cleaner/releases/tag/0.10.0

Manuel mode is working great.Thank you very much @Sanster. A keyboard shortcut assigned to that or mouse right click to activate lama-cleaning shall be nice in manuel mode.Another one maybe in the future if you wanna implement is "redo" functionality,opposite of "undo". Can redo brush strokes in manuel mode,can redo lama cleaning in automatic mode.

**Comment by blessedcoolant** [comment]
> Manuel mode is working great.Thank you very much @Sanster. A keyboard shortcut assigned to that or mouse right click to activate inpainting shall be nice in manuel mode.

I pushed a patch that adds a hotkey (Shift + R) to manual painting. I did it because I thought it was handy but then I realized you wanted it too. So updating you on that.

**Comment by blessedcoolant** [comment]
> Is there anyway or trick we can do to customize the hot keys for the end user?I mean where can we edit and if it is possible,does it require alt,ctrl or shift keys to be in the combination or we can just assign a hot key like any single keyboard key?

Yes. There's actually a branch I have on my local system where I was trying to implement the ability for a user to save their own hotkeys. But I'm still figuring out the best way to do it. Because the cleaner works in a browser, it has limited access to the local system. I want to find an efficient way to store and restore hotkeys that does not interfere in anyway with the current working of the program.

**Comment by FlowDownTheRiver** [comment]
Got it. Great to hear that you already working on a feature like that and yeah browsers have their own shortcuts keys. It maybe limiting the options. Hoping you work it out.
