### ISSUE TITLE
Does not work with the newer Diffusers

### ISSUE THREAD

**Issue by Piscabo** [Sanster/lama-cleaner#436]
Lcleaner needs to be updated to work with newer dependencies. It is stopping ComfUI nodes from functioning.
**Model**
lama-cleaner 1.2.5 requires diffusers==0.16.1, but you have diffusers 0.25.1 which is incompatible.

**Describe the bug**
lama-cleaner 1.2.5 requires diffusers==0.16.1, but you have diffusers 0.25.1 which is incompatible.

**System Info**
Software version used
- lama-cleaner:    1.2.5
- torch:   2.1.2+cu121
- CUDA: 21.2

**Comment by Sanster** [comment]
Lama-cleaner has been renamed to iopaint in the new version. I suggest switching to iopaint, which uses the latest diffusers.
