### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [Sanster/lama-cleaner#48]
Hi, would you be interested in adding lama-cleaner  to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

there is already a demo for lama on spaces: https://huggingface.co/spaces/akhaliq/lama

would be great to have lama-cleaner as well to try out as a web demo

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by Sanster** [comment]
Sorry for the late replay, Lama Cleaner is now running on spaces! 🤗  https://huggingface.co/spaces/Sanster/Lama-Cleaner-lama
