### ISSUE TITLE
Model Loading (and other suggestions)

### ISSUE THREAD

**Issue by mjc619** [Sanster/lama-cleaner#5]
Moving the biglama model out of the cache and putting it into a model folder would help for people training their models for different targets(looking into this myself), as well as a way to pause and apply multiple strokes would be helpful. 
Something like mask filling/loading and U^2 net salient object masking would be more for a gimp-ml tool but could speed up and make the tool easier to use.

**Comment by Sanster** [comment]
- [x] Use `LAMA_MODEL` to set a torchscript lama model.  convert script: https://github.com/Sanster/lama/blob/add_torchscript_convert_script/bin/to_jit.py
- [x] Multi stroke support. Press and hold the cmd/ctrl key to enable multi stroke mode.
