### ISSUE TITLE
Request - Add support for Zits and MAT inpainting which are the current SoTa

### ISSUE THREAD

**Issue by ofirkris** [Sanster/lama-cleaner#52]

**Comment by Sanster** [comment]
ZITS: https://github.com/Sanster/lama-cleaner/releases/tag/0.15.0

**Comment by flagshipbowtie** [comment]
From my tests. ZITS is as good as LAMA. Sometimes better sometimes worse depending on the image. MAT is a wild card. It injects whatever it's got in its models labeled as for example building or tree.

**Comment by styler00dollar** [comment]
I feel like you don't properly use MAT. I used your MAT output image to draw over it.
![182226870-b0ff5881-b505-4b18-9454-7eaafa533697_cleanup(1)](https://user-images.githubusercontent.com/51405565/184536544-46339f8d-6326-4205-8ad5-7dc333a23ee7.png)
.

**Comment by flagshipbowtie** [comment]
> I feel like you don't properly use MAT. I used your MAT output image to draw over it with MAT again. Maybe your code is wrong. ![182226870-b0ff5881-b505-4b18-9454-7eaafa533697_cleanup(5)](https://user-images.githubusercontent.com/51405565/184536940-1fc9d619-a49d-4503-a914-a0f9a05030e6.png)

You don't seem to even know how to use a mask. I can still open your first pic through gmail notification.  hahahahaha  You're not supposed to draw a giant square. MAT does take squares but it doesn't require a mask to be so.
Your second attemp fucked up the floor to the point it bears no resemblence the original one. Both of your attempts fucked the boat to the white reddish mess

You MATted over my MAT image? hahahah WTF? That's not how it's done. You should take the source posted above.

It's all very simple. You feed a picture and a mask (white black picture. That's explaining to you) Done!

**Comment by styler00dollar** [comment]
I just wanted to illustrate that I do not get the output you got. I got randomly drew a mask. At the bottom I felt like removing the lines since you showed color inconsistencies in the other images there.

**Comment by flagshipbowtie** [comment]
> I created a few different images and I guess I left just one which I felt was the best one which I did in my limited testing. I just wanted to illustrate that I do not get the output you got with MAT. I just randomly drew a mask, not a square. [I modded lama cleaner to have MAT which I used for this](https://github.com/styler00dollar/sudo-inpaint). It's still in a rough shape but functional. At the bottom I felt like trying to remove the lines since you showed color inconsistencies in the other images there. You did not even provide a mask, how am I supposed to guess what you did. My whole point was to show that MAT does not create such artifacts which you said it does, nothing else, and I think I archived that. You don't need to act rude.

hahahahahaah provide a mask of what? The obvious? You can't be helped if you can figure what the mask is especially by the failed MAT output (not that it woould've been much harder without) which shows the exact mask outline. How do you even function in your life? Rhetorical question.
hahahaha I act Russian. Sure by your liberal snowflake cry baby stardards everything is rude and offensive. No wonder your society and life are nothing by vomiting inducing

**Comment by styler00dollar** [comment]
This has nothing to do with the output quality of MAT and I can't be bothered to trace the pixels you inpainted. If you can't contribute anything useful then just stop responding.

**Comment by flagshipbowtie** [comment]
>  If you can't contribute anything useful then just stop responding.
Take your own advice dumbass cos that's clearly you

**Comment by styler00dollar** [comment]
Who cares about the mask? I talk about the output quality of MAT. If you are looking for a fight, don't do it on Github and do it somewhere else.

**Comment by flagshipbowtie** [comment]
> Who cares about the mask? I talk about the output quality of MAT. If you are looking for a fight, don't do it on Github and do it somewhere else. Github is a place for developers and not about arguing about stuff that is not even relevant. I guess I will just ignore further comments, if you can't seem to make any kind of productive comment. You could retry MAT, or whatever, instead you just pick on something that was never important.

hahahahahah projecting libshit, look into the mirror. Also yet again take your own advice and go back to Twatter. I'm sure you can screech there for hours about whatever.

**Comment by flagshipbowtie** [comment]
> What part of "I just randomly drew a mask, not a square. [...] At the bottom I felt like trying to remove the lines since you showed color inconsistencies" did you not get. Also, I am just pointing out that you somehow wrongly use MAT. I do not know how, but you did. Here, I did it again. Keep in mind that I added MAT into my code. ![a](https://user-images.githubusercontent.com/51405565/184635226-4cd79c96-f812-43da-91df-f1404ef26594.gif) [ ![a](https://user-images.githubusercontent.com/51405565/184635226-4cd79c96-f812-43da-91df-f1404ef26594.gif) ](https://user-images.githubusercontent.com/51405565/184635226-4cd79c96-f812-43da-91df-f1404ef26594.gif) [ ](https://user-images.githubusercontent.com/51405565/184635226-4cd79c96-f812-43da-91df-f1404ef26594.gif) There are no such artefacts like in your picture.

hahahaa Why the fuck do you keep masking the fucked up MATS result of mine instead masking the table in the source pic above? I'm not gonna even ask the point of your retarded exerice in trying to repeat the issue which seems to be your goal

**Comment by styler00dollar** [comment]
I feel like you are trolling at this point. I took your image to proof that the inpainted stuff does not look like your result.

**Comment by flagshipbowtie** [comment]
> I feel like you are trolling at this point. I took your mat as a base image to proof that the inpainted stuff does not look like your result and you did something wrong. It simply does not matter what image I use. Water looks like actual water and not this black/white whatever striped artifact. That was the only thing I wanted to show, nothing else. Absolutely nothing else. Why do you bring up stuff I never mentioned or cared about I wonder..

I feel like .... nah  I know for a fact you're retarded. hahahaha
Quote myself from 14 days ago **MAT's for filling large holes with whatever it's got a match for in its models. Works on a number of things and even then you get a wild result. Paint a window and it will place some other random window instead. Doesn't work on many other things especially removal. The filling never has any relevancy to the image.** aka it worked on a bunch of other images I tried with no issues so there's no wrong with the code. It's irrelevant why it's fucked the table.

**Comment by styler00dollar** [comment]
Looks like the comments I replied to are gone. Stating this to avoid confusion.

**Comment by Sanster** [comment]
@styler00dollar I added the MAT model in this [PR](https://github.com/Sanster/lama-cleaner/pull/62). Have you found any practical use where MAT works better than LaMa? In my tests, the MAT tends to produce strange results and does not perform well on high resolution, which I don't feel is very practical. Maybe there is something wrong with my code, will take some time to check it.

**Comment by styler00dollar** [comment]
MAT is non-deterministic because of `z = torch.randn(images_in.size(0), self.img_resolution)`, so you can generate a different image all the image, and since it is a transformer, you don't need to wait like in diffusion, which is what I liked about MAT. I didn't really do comparisons against lama. I mainly tested it on drawings and it did well there though.

**Comment by Sanster** [comment]
MAT: https://github.com/Sanster/lama-cleaner/releases/tag/0.16.0
