### ISSUE TITLE
Super slow

### ISSUE THREAD

**Issue by zhiyicai** [Sanster/lama-cleaner#54]
I use mac mini m1 super slow, photo 1920 * 1000 need 5-6 minutes 

The command used is
lama-cleaner --device=cpu --port=8080

**Comment by dheerajpg** [comment]
Hey @Sanster is there any substantial difference in using the Original, Resize and Crop other than the time to get output. Like will there be different or better results if we choose Original compared to Resize or Crop.

**Comment by Sanster** [comment]
> Hey @Sanster is there any substantial difference in using the Original, Resize and Crop other than the time to get output. Like will there be different or better results if we choose Original compared to Resize or Crop.

Most models perform worse at high resolutions, so I recommend using crop in most cases.

**Comment by dheerajpg** [comment]
alright!
