### ISSUE TITLE
0.15.0 windows not working 

### ISSUE THREAD

**Issue by ammartist** [Sanster/lama-cleaner#56]
I updated from  V0.14.0 to V0.15.0 and try to run it using: 
`python main.py`

(lama015) C:\Users\username\Documents\Ai_Ml\lama-cleaner-0.15>python main.py
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

I installed it using conda new env and installed pytorch
`conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch`

I wax using 0.14.0 and it was working perfictly with almost 0 issues
something had changed cusing this.

**Comment by Sanster** [comment]
I found the solution [here](https://stackoverflow.com/questions/20554074/sklearn-omp-error-15-initializing-libiomp5md-dll-but-found-mk2iomp5md-dll-a)

I don't have an environment to reproduce the problem, please try this command: `KMP_DUPLICATE_LIB_OK=True python main.py`

**Comment by ammartist** [comment]
When I try  `KMP_DUPLICATE_LIB_OK=True python main.py`

Got this error:
KMP_DUPLICATE_LIB_OK is not recognized as an internal or external command,
operable program or batch file.

**Comment by Sanster** [comment]
On windows it should be `set KMP_DUPLICATE_LIB_OK=True && python main.py`

**Comment by ammartist** [comment]
> 

It work using `set KMP_DUPLICATE_LIB_OK=True && python main.py`
However, when i try to use it It show this error:
![image](https://user-images.githubusercontent.com/4099839/180790718-e418c608-c406-4429-ba39-021cf2975a71.png)
it show this on the Terminal:
127.0.0.1 - - [25/Jul/2022 17:38:16] "POST /inpaint HTTP/1.1" 400 -

One more thing to note, in settings it does not show the new model (ZITS):
![image](https://user-images.githubusercontent.com/4099839/180791851-bf76378a-57fd-49c1-8899-1603976fd2e7.png)

**Comment by Sanster** [comment]
I tried `set KMP_DUPLICATE_LIB_OK=True && python main.py` in a new conda environment on windows, it works fine. Not sure why there are the problems you are experiencing

**Comment by ammartist** [comment]
I will test on new env, thx

**Comment by ammartist** [comment]
Yes you are right. On new Env. it does work. I think something changed since 0.14 

Any ways, thank you so much ;-)

**Comment by Sanster** [comment]
🥳

**Comment by lenzfliker** [comment]
@Tobe2d where exactly should I run this command? I'm using Anaconda and can't find a main.py?
