### ISSUE TITLE
Does Lama Cleaner support the new feature refinement?

### ISSUE THREAD

**Issue by dillfrescott** [Sanster/lama-cleaner#57]
Just wondering if it has it built-in

**Comment by Sanster** [comment]
Do you mean this PR https://github.com/saic-mdal/lama/pull/112 ?Not yet supported, as far as I know this method requires a large amount of GPU memory, have you tested it?

**Comment by DillFrescott** [comment]
I have not tested it but it looks cool!

**Comment by flagshipbowtie** [comment]
> I have not tested it but it looks cool!

LOL of course but nobody's got VRAM for that. Nobody ever bothers to intergrate a ready solution to offload on SSD or HDD

**Comment by DillFrescott** [comment]
Maybe one day lolol
