### ISSUE TITLE
Design change if possible

### ISSUE THREAD

**Issue by FlowDownTheRiver** [Sanster/lama-cleaner#58]
@Sanster Hi there...Hoping everything is going well.
It has been awhile since I checked the repo for updates. I have noticed that after dragging and dropping to canvas and after I save the photo,I realized the button function is changed to upload new,which opens explorer to load a new photo from a location on the pc which is fine but this took away the previous functionality which was cleaning the canvas and return to welcome screen,we can drag and drop a new photo to inpaint.Now the only way to drag and drop is when the gui is first launched.

Is it possible for you to revert changes back to the original design,or maybe you can add the old button back next to "upload new" if you want.That was a good functionality.

![2022-08-02 02_51_35-Window](https://user-images.githubusercontent.com/71787427/182263872-5056d0bd-d663-43df-9ad3-34593ce4660c.jpg)

**Comment by FlowDownTheRiver** [comment]
Also thanks for the zitz model and updates,I forgot to say :)

**Comment by Sanster** [comment]
Complete remove landing page: https://github.com/Sanster/lama-cleaner/releases/tag/0.22.0


https://user-images.githubusercontent.com/3998421/194713446-c22e8320-1f12-4910-814b-ae2b0f1a3ade.mov


https://user-images.githubusercontent.com/3998421/194713757-21b637a1-fc5d-408a-987b-337627a3f33b.mov
