### ISSUE TITLE
High resolution strategies

### ISSUE THREAD

**Issue by FBehrad** [Sanster/lama-cleaner#59]
Have you implemented the strategies which are mentioned in readme?
I mean this part:
Resize: Resize the image to a smaller size, then do inpainting on the resized image. The inpainting area will be croped, upsampled and pasted back on the original image to make sure other part of image not loss quality.
Crop: Crop masking area from the original image to do inpainting, and paste the result back. Mainly for performance and memory reasons on high resolution image.

**Comment by Sanster** [comment]
Yes, you can see it in settings 
<img width="1911" alt="截屏2022-08-02 下午9 03 12" src="https://user-images.githubusercontent.com/3998421/182381384-907eeb2b-cec5-463b-a616-32c2754711fa.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/3998421/182381189-97bb0cb8-2ea1-4195-904e-2916054394bf.png">

**Comment by FBehrad** [comment]
Thanks.
