### ISSUE TITLE
ZITS input size

### ISSUE THREAD

**Issue by FBehrad** [Sanster/lama-cleaner#61]
Hello
Why the inputs of ZITS must be 256*256 or 512*512 otherwise they are cropped?
In other word, why the input must be square?

**Comment by Sanster** [comment]
Check this issue： https://github.com/DQiaole/ZITS_inpainting/issues/7

**Comment by flagshipbowtie** [comment]
> Check this issue： [DQiaole/ZITS_inpainting#7](https://github.com/DQiaole/ZITS_inpainting/issues/7)

ooph!

Can you implement chopping 1080p images into 2 squares and stick them back together when we're done painting. It will be 2 of 960 by 1080 and at least then the resizing back damage will be minimal or simple chopping top and bottom for 70 pixels each before painting.
Or at least put up a notice on the model? Cos I didn't really know that. I knew MATS takes squares

**Comment by FBehrad** [comment]
> Check this issue： [DQiaole/ZITS_inpainting#7](https://github.com/DQiaole/ZITS_inpainting/issues/7)

Thank you so much for your quick response.
