### ISSUE TITLE
Requests- Add support for FCF-Inpainting

### ISSUE THREAD

**Issue by fathshalaby** [Sanster/lama-cleaner#63]
https://github.com/SHI-Labs/FcF-Inpainting

**Comment by Sanster** [comment]
https://github.com/Sanster/lama-cleaner/releases/tag/0.17.0

||Lama|FcF|
|-----|-----|-----|
|![texture](https://user-images.githubusercontent.com/3998421/188305027-a4260545-c24e-4df7-9739-ac5dc3cae879.jpeg)|![texture_lama](https://user-images.githubusercontent.com/3998421/188305024-2064ed3e-5af4-4843-ac10-7f9da71e15f8.jpeg)|![texture_fcf](https://user-images.githubusercontent.com/3998421/188305006-a08d2896-a65f-43d5-b9a5-ef62c3129f0c.jpeg)|
