### ISSUE TITLE
Suggestion: allow users to use ctrl v to paste in a image and ctrl c to copy the edited image

### ISSUE THREAD

**Issue by gammesB** [Sanster/lama-cleaner#68]
Instead of having to select a file it would be awesome if you could easily paste in a image you have on your clipboard.
Also the other way arround where if you do ctrl c it would copy the current image to your clipboard.

I do most of my work in photoshop and noticed that just copying part of the image into lama cleaner works great and sometimes even better then when i gave it the full image

**Comment by Sanster** [comment]
- `ctrl+v` added in [0.22.0](https://github.com/Sanster/lama-cleaner/releases/tag/0.22.0)
- `ctrl+c` added in [0.20.0](https://github.com/Sanster/lama-cleaner/releases/tag/0.20.0)
