### ISSUE TITLE
Question: How to Access Flask Server

### ISSUE THREAD

**Issue by arnavmehta7** [Sanster/lama-cleaner#70]
Hey, first of all the app is amazing. I want to access only the flask server and call it through 'requests'. However, while digging in code, there are too many CONFIGS which I don't know about. I would be grateful to know how can I call it with requests through JS/python. Like what are the data I need to provide in the FORM while POSTING request.

**Comment by Sanster** [comment]
There is already an API [here](https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/server.py#L92), you can check the meaning of arg in `Config` at [here](https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/schema.py)
