### ISSUE TITLE
Question: How to manually install Stable Diffusion model that is already downloaded?

### ISSUE THREAD

**Issue by jasonmhead** [Sanster/lama-cleaner#74]
How to manually install Stable Diffusion model that is already downloaded?
 
 Where should it go?
 Sub-directory for that model?
 What should be the name of the model file?

**Comment by swankwc** [comment]
I would also like to know this.

**Comment by Sanster** [comment]
There are two versions of stable-diffusion weights:
1. huggingface version：[https://huggingface.co/CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4)
2. CompVis version：[https://huggingface.co/CompVis/stable-diffusion-v-1-4-original](https://huggingface.co/CompVis/stable-diffusion-v-1-4-original)

If you have downloaded the **huggingface version**, just copy to `~/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4`([diffusers's](https://github.com/huggingface/diffusers) default cache folder)

If you have downloaded the **CompVis version**,  you need to convert it to the huggingface version first. But I don't know how to convert this model 😞

**Comment by tuwonga** [comment]
> There are two versions of stable-diffusion weights:
> 
> 1. huggingface version：https://huggingface.co/CompVis/stable-diffusion-v1-4
> 2. CompVis version：https://huggingface.co/CompVis/stable-diffusion-v-1-4-original
> 
> If you have downloaded the **huggingface version**, just copy to `~/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4`([diffusers's](https://github.com/huggingface/diffusers) default cache folder)
> 
> If you have downloaded the **CompVis version**, you need to convert it to the huggingface version first. But I don't know how to convert this model 😞

I'm sorry but I can't do that. I've got the sd1.4.ckpt.
Can you please explain how to place in folder ?
I use Windows 11 , conda
Thank you

**Comment by Sanster** [comment]
`0.32.0` https://github.com/Sanster/lama-cleaner/releases/tag/0.32.0

use `--model-dir` to set model download directory
