### ISSUE TITLE
Running the docker image on windows gives no response

### ISSUE THREAD

**Issue by marquilio7** [Sanster/lama-cleaner#75]
I'm using Windows 11 with WSL and after building the image with
`docker build -f Dockerfile -t lamacleaner .`

and running on cpu with:
`docker run -p 8080:8080 -e CACHE_DIR=/app/models -v  ${pwd}/models:/app/models -v ${pwd}:/app --rm lamacleaner python3 main.py --device=cpu --port=8080`
[ i've switched '$(pwd)' to '${pwd}' ]

It says: 

> * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)

But i get an empty response when i visit that url.
Neither changing the port nor accessing [::1] or the internal ip of the docker image works.

**Comment by Sanster** [comment]
Add `--host=0.0.0.0` when start server: `python3 main.py --device=cpu --port=8080 --host=0.0.0.0`

**Comment by mrg358** [comment]
> Add `--host=0.0.0.0` when start server: `python3 main.py --device=cpu --port=8080 --host=0.0.0.0`

it works, thank you.

**Comment by marquilio7** [comment]
> Add `--host=0.0.0.0` when start server: `python3 main.py --device=cpu --port=8080 --host=0.0.0.0`
It works thank you! Now i can access it from http://[::1]:8080/
