### ISSUE TITLE
Add zoom in (out) functionality to make better mask ?

### ISSUE THREAD

**Issue by Michaelwhite34** [Sanster/lama-cleaner#8]

**Comment by Michaelwhite34** [comment]
Also,the bottom of the image is hard to select when I use a small brush,but the top left right sides are easy to select.

**Comment by Sanster** [comment]
> Also,the bottom of the image is hard to select when I use a small brush,but the top left right sides are easy to select.

Can you take a screenshot?

**Comment by Michaelwhite34** [comment]
Sorry for late reply,I can't take a screen shot with cursor,you can try the file
![alice_](https://user-images.githubusercontent.com/72028833/151307001-e279af49-8511-4106-99ae-25ecc0d8c308.png)
I can't paint around 80 pixel height area in the bottom.

**Comment by Sanster** [comment]
Done
