### ISSUE TITLE
taking too much time in cleaning 

### ISSUE THREAD

**Issue by vishnusharmax** [Sanster/lama-cleaner#81]
how we can reduce the time?

**Comment by Sanster** [comment]
1. If you are currently running on a cpu, you can use the gpu
2. Try to use `crop strategy`, 
<img width="549" alt="截屏2022-10-08 下午6 09 15" src="https://user-images.githubusercontent.com/3998421/194702363-685a30b0-ea63-4c21-9834-c09cd521603c.png">
