### ISSUE TITLE
Add resizable brush when alt+left mouse button is pressed

### ISSUE THREAD

**Issue by bropines** [Sanster/lama-cleaner#82]
In photoshop, you could change the size of the brush when you pressed alt and held down the left mouse button. It would be convenient to use it here as well. Or as in [Ballon Translator](https://github.com/dmMaze/BallonsTranslator) 
Example video: 

https://user-images.githubusercontent.com/57861007/194719080-536bf0c8-318f-45d2-b068-d3000995936e.mp4

**Comment by Sanster** [comment]
Implemented a simple version [0.23.0](https://github.com/Sanster/lama-cleaner/releases/tag/0.23.0): press alt/opt and move the mouse left/right to change brush size

**Comment by bropines** [comment]
Doesn't work in Yandex browser. It's all good.
