### ISSUE TITLE
I opened http://localhost:8080 with firefox and he showed a blank page with nothing on it.

### ISSUE THREAD

**Issue by popdog0** [Sanster/lama-cleaner#85]
I opened http://localhost:8080 with firefox and he showed a blank page with nothing on it.
Here are the log messages：

 lama-cleaner --model=lama --devi=cpu --port=8080
/home/a/.local/lib/python3.9/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/home/a/.local/lib/python3.9/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
2022-10-10 09:30:54.027 | INFO     | lama_cleaner.model.lama:init_model:30 - Load LaMa model from: /home/a/.cache/torch/hub/checkpoints/big-lama.pt
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
127.0.0.1 - - [10/Oct/2022 09:33:12] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2022 09:33:12] "GET /static/css/main.466cfae4.chunk.css HTTP/1.1" 304 -
127.0.0.1 - - [10/Oct/2022 09:33:12] "GET /static/js/2.cf5073aa.chunk.js HTTP/1.1" 304 -
127.0.0.1 - - [10/Oct/2022 09:33:12] "GET /static/js/main.54107436.chunk.js HTTP/1.1" 304 -
127.0.0.1 - - [10/Oct/2022 09:33:12] "GET /static/media/WorkSans-Regular.bb287b89.ttf HTTP/1.1" 304 -

**Comment by Sanster** [comment]
What version of firefox are you using? I tested 105.0.3 on macOS, it works fine.

Can you help to see what error is reported in the console?

<img width="1240" alt="截屏2022-10-10 上午11 15 15" src="https://user-images.githubusercontent.com/3998421/194794994-68298342-0202-4886-96c3-6857ff131b50.png">

**Comment by popdog0** [comment]
My firefox version is to low,it's 43,That's the reason。
When I upgraded to the latest version, he worked fine.
> What version of firefox are you using? I tested 105.0.3 on macOS, it works fine.
> 
> Can you help to see what error is reported in the console?
>
