### ISSUE TITLE
wont run in the cloud

### ISSUE THREAD

**Issue by cryptojoejoe** [Sanster/lama-cleaner#86]
No matter what I do I can't get this to run in the cloud tried using render.com, netlify, and vercel.

**Comment by Sanster** [comment]
I'm curious what problems you've encountered?

**Comment by cryptojoejoe** [comment]
I get an "Invalid Host header" when I try and deploy it. Could be a really easy fix or something im doing wrong.. im new to all this and just started learning all this not long ago

but I also get this code
Build successful 🎉
 ==> Deploying...
 ==> Starting service with 'npm run start'

> lama-cleaner@0.1.0 start /opt/render/project/src/lama_cleaner/app
> react-scripts start
 
｢wds｣: Project is running at http://10.207.78.52/
｢wds｣: webpack output is served from
｢wds｣: Content not from webpack is served from /opt/render/project/src/lama_cleaner/app/public
｢wds｣: 404s will fallback to /
Starting the development server...

Your service is live 🎉
Failed to compile.

src/components/shared/Toast.tsx
Line 77:3:  defaultProp "desc" defined for isRequired propType  react/default-props-match-prop-types

**Comment by cryptojoejoe** [comment]
got it all figured out!

**Comment by cryptojoejoe** [comment]
figured it out
