### ISSUE TITLE
when you uninstal then dependencies are not uninstalled ?

### ISSUE THREAD

**Issue by 1blackbar** [Sanster/lama-cleaner#88]
this leaves no room to fix the installation in case it goes southways, in my case i have to wipe all lama-ceaner piped stuff cause it conflicts with others tuff i have , so id suggest to perform uninstall in a cleaner way than just removing the code without removing dependencies, or at least give us an option to choose, now i have to waste a lot of time to remove manually

Had to use  pip uninstall -r requirements.txt -y

torch installed without cuda

 Ok instaled by pip install lama-cleaner from 0, it installs wrong numpy that doesnt work and installs torch without cuda....

`:\lamanew>lama-cleaner --model=zits --device=cuda --port=8080
C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\model\utils.py:225: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  def setup_filter(f, device=torch.device('cpu'), normalize=True, flip_filter=False, gain=1, separable=None):
C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\amp\autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\amp\autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')`

Ok got cuda working by installing this
pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113

but now numpy is wrong 

`lama-cleaner --model=zits --device=cuda --port=8080
C:\Users\BAZO\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\model\utils.py:225: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  def setup_filter(f, device=torch.device('cpu'), normalize=True, flip_filter=False, gain=1, separable=None):
2022-10-12 01:10:36.185 | INFO     | lama_cleaner.helper:load_jit_model:44 - Load model from: C:\Users\BAZO/.cac`

So... fixed this crap with    pip install numpy --upgrade

**Comment by Sanster** [comment]
No, dependencies are not uninstalled, it's how pip works.
