### ISSUE TITLE
Error when editing images above 2k

### ISSUE THREAD

**Issue by amooose** [Sanster/lama-cleaner#9]
It seems to error out on larger images when editing the original size.
3840x2880
3648x5472
2299x3065

I've attached the error outputs:
[err2.txt](https://github.com/Sanster/lama-cleaner/files/7885971/err2.txt)
[err1.txt](https://github.com/Sanster/lama-cleaner/files/7885972/err1.txt)

I'm on CUDA 11.1 (I've tried 11.3/11.5 too) and have also tried torch 1.9-1.10, with the same errors occurring on my
RTX 3080 GPU. I'm using the Docker setup but with the torch replaced with the cuda 11.1+ version. Selecting 2k or 1080p usually results in it working properly (I believe sometimes 2k will throw an error, but then will work)

**Comment by Sanster** [comment]
I use torch 1.8 to convert torchscript model, maybe you can try convert it using 1.9 or 1.10. https://github.com/saic-mdal/lama/pull/63

**Comment by amooose** [comment]
> I use torch 1.8 to convert torchscript model, maybe you can try convert it using 1.9 or 1.10. [saic-mdal/lama#63](https://github.com/saic-mdal/lama/pull/63)

Thanks for the tip, I used your script, had to modify it a bit to run,


    image = torch.rand(1, 3, 120, 120).to(device)  
    mask = torch.rand(1, 1, 120, 120).to(device)  
    output = jit_model_wrapper(image, mask)
and had an output successfully generated on 1.10 with "diff: 0.0".

Unfortunately with this new model installed, the same error occurs. Would there be anything else that I could try?

**Comment by Eidenz** [comment]
You seems to be running into memory issues (RAM, not GPU). I get the same error on some servers with low memory. Please not than images higher than 2k will use up or even more than 32GB of RAM.

Depending on yout system, consuming all available RAM will result in a CUDA error just like yours or a task kill being returned.
I mainly noticed these errors on linux systems. Windows seems to try and free as much as memory as possible to avoid a crash.

**Comment by Sanster** [comment]
Why your image take up so much memory?

```python
# rgb image
np_img = np.ones((2000,2000,3), dtype=np.uint8)
np_img.nbytes / 1024 / 1024 # ~= 11MB
```

**Comment by Eidenz** [comment]
That's a good question. All I know is that LaMa uses a lot of memory with big images on my setup, no matter the system.

I tried it on 3 different OS (Windows, Debian, Ubuntu), with various configurations and it has always been using a lot of memory with high-quality input (starting from 2k).

**Comment by 2blackbar** [comment]
> Why your image take up so much memory?
> 
> ```python
> # rgb image
> np_img = np.ones((2000,2000,3), dtype=np.uint8)
> np_img.nbytes / 1024 / 1024 # ~= 11MB
> ```

lazy coding

**Comment by Sanster** [comment]
I can't reproduce in my environment(RTX3090 + pytorch1.8.2)

This is the result of [benchmark](https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/benchmark.py) script

<img width="680" alt="截屏2022-03-20 下午10 24 46" src="https://user-images.githubusercontent.com/3998421/159167978-8c390faf-49e8-4c54-b1bf-c2fa685f1bf1.png">

**Comment by Sanster** [comment]
Add crop mode for very large image, this helps with memory issues.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/3998421/159610609-0b935220-aae0-4fe2-8d84-fbe88a805514.png">
