### ISSUE TITLE
EMPTY RESPONSE.

### ISSUE THREAD

**Issue by ZeroCool22** [Sanster/lama-cleaner#92]
https://user-images.githubusercontent.com/13344308/197093456-10be3611-18b9-4c6b-b0d4-41769d634ba7.mp4

![Screenshot_8](https://user-images.githubusercontent.com/13344308/197098365-7a69224b-51d4-48ba-a030-e43f6abac021.jpg)

![Screenshot_10](https://user-images.githubusercontent.com/13344308/197098242-8d7f83f0-f2ad-4e35-a4eb-924e30c9c360.jpg)

**FireFox 106.0.1 (64-bit)**

**Comment by ZeroCool22** [comment]
lol, how much **VRAM** we need to use the in paint 1.5?

**Comment by ZeroCool22** [comment]
@Sanster Some idea what is happening?

**Comment by Sanster** [comment]
Fixed in https://github.com/Sanster/lama-cleaner/commit/e2e2f5f853bb9bc28b4da2487f57b0105afa71dc . Please try `0.24.2`
