### ISSUE TITLE
1.5 model - need some help

### ISSUE THREAD

**Issue by casidias** [Sanster/lama-cleaner#96]
Hi! 

I can't download the 1.5 model - I accepted terms at
https://huggingface.co/runwayml/stable-diffusion-inpainting
and followed the instructions - after typing the command
`lama-cleaner --model=sd1.5 --hf_access_token=hf_XXX `
I am getting the following error:

`lama-cleaner: error: argument --model: invalid choice: 'sd1.5' (choose from 'lama', 'ldm', 'zits', 'mat', 'fcf', 'sd1.4', 'cv2')`

**Comment by Sanster** [comment]
You also need to get an access token from here [huggingface access token](https://huggingface.co/docs/hub/security-tokens) and update to the newest version `pip install lama-cleaner==0.24.2`

**Comment by casidias** [comment]
Shame on me. I was sure I had downloaded the update. Thanks a lot!
