### ISSUE TITLE
Keep object inside mask

### ISSUE THREAD

**Issue by Atsui75** [Sanster/lama-cleaner#98]
Hi:

Is it possible to use lama-cleaner to do the opposite of inpainting, that is, to keep the object selected with a mask?

I have tried substracting the inpainted image to the original, but that process leaves a lot of noise. Since the model is trained to remove structures, what is needed to train another model which leaves them (and removes the background)?

I would be very grateful for any hint on how to solve this problem.

(PD: I don't know if this is the appropiate space for this kind of question, I apologize in advance if that is not the case)

Thanks in advance!

**Comment by Sanster** [comment]
I'm not sure I understood your need, is it something like what [rembg](https://github.com/danielgatis/rembg) does?

**Comment by Atsui75** [comment]
Well, that certainly does seem like what I want to achive, but I cannot find how to give a mask to rembg or how it selects the object. Over all it is not nearly as interactive as lama-cleaner but I will check it out in more depth.

Thank you very much for your time :)

**Comment by Atsui75** [comment]
I have found this tool: [CascadePSP ](https://github.com/hkchengrex/CascadePSP) that may be exactly what I need but interactivity remains a problem. I will keep looking, thanks for pointing me in the right direction.

**Comment by Sanster** [comment]
If you are looking for the best **salient semantic segmentation** project, perhaps this project would be of interest to you as well：https://github.com/xuebinqin/DIS
![image](https://user-images.githubusercontent.com/3998421/198857134-38bd89df-a8ce-4fb9-8204-5fd724f33115.png)

If you really care about interaction, there is a niche discipline in deep learning called **interactive semantic segmentation**. The flow of the interaction is shown in the following demo. As far as I know [ClickSEG](https://github.com/XavierCHEN34/ClickSEG) is the current SOTA method

![teaser](https://user-images.githubusercontent.com/3998421/198857239-858f22e7-7b3c-468d-9d7c-8b46192dc46a.gif)

example from: https://github.com/saic-vul/ritm_interactive_segmentation

![1-hch_tqmnjsjlrjaxms3wua](https://user-images.githubusercontent.com/3998421/198857304-ec3b0994-18da-409d-a6f7-a9e4bb011043.gif)

example from: https://research.runwayml.com/building-a-web-based-real-time-video-editing-tool-with-machine-learning

**Comment by Atsui75** [comment]
Wow, that really seems to be what I have been looking for, I will try them out as soon as I can.

Thank you very much again :)
